import type { A1Day } from './types';

export const days16to20: A1Day[] = [
  {
    day: 16, emoji: '🎸', title: 'Hobbies', titleVi: 'Sở thích',
    goal: 'Nói về sở thích, việc mình làm được và không làm được.',
    words: [
      { word: 'hobby', vi: 'sở thích', emoji: '🎨', forms: ['hobbies'], examples: ['My hobby is reading.', 'What are your hobbies?'] },
      { word: 'free time', vi: 'thời gian rảnh', emoji: '🕹️', examples: ['What do you do in your free time?', 'I read in my free time.'] },
      { word: 'play', vi: 'chơi (thể thao, nhạc cụ)', emoji: '⚽', forms: ['plays', 'playing'], examples: ['I play football.', 'She plays the guitar.'] },
      { word: 'swim', vi: 'bơi', emoji: '🏊', forms: ['swimming'], examples: ['I can swim.', 'I like swimming.'] },
      { word: 'can', vi: 'có thể, biết (làm gì)', emoji: '💪', examples: ['I can cook.', 'Can you swim?'] },
      { word: "can't", vi: 'không thể, không biết', emoji: '🚫', examples: ["I can't sing.", "He can't drive."] },
      { word: 'music', vi: 'âm nhạc', emoji: '🎵', examples: ['I listen to music every day.', 'What music do you like?'] },
      { word: 'cook', vi: 'nấu ăn', emoji: '👨‍🍳', forms: ['cooking', 'cooks'], examples: ['I like cooking.', 'My dad cooks on Sunday.'] },
    ],
    story: {
      title: 'Bao and his hobbies',
      sentences: [
        { en: 'Bao works hard, but he has a lot of hobbies.', vi: 'Bảo làm việc chăm chỉ, nhưng anh có nhiều sở thích.' },
        { en: 'In his free time, he plays football with his friends.', vi: 'Lúc rảnh, anh đá bóng với bạn bè.' },
        { en: 'He also likes music. He can play the guitar.', vi: 'Anh cũng thích âm nhạc. Anh biết chơi guitar.' },
        { en: 'But he can\'t sing. His friends laugh when he sings!', vi: 'Nhưng anh không biết hát. Bạn bè cười khi anh hát!' },
        { en: 'On Sunday, Bao likes cooking.', vi: 'Chủ nhật, Bảo thích nấu ăn.' },
        { en: 'He can cook pho and spring rolls.', vi: 'Anh biết nấu phở và nem.' },
        { en: 'Bao can\'t swim. He wants to learn this summer.', vi: 'Bảo không biết bơi. Anh muốn học vào mùa hè này.' },
        { en: 'His sister can swim very well. She is his teacher!', vi: 'Em gái anh bơi rất giỏi. Cô ấy là giáo viên của anh!' },
      ],
      questions: [
        { q: 'Does Bao play football?', vi: 'Bảo chơi bóng đá phải không?', answer: true },
        { q: 'Can Bao sing well?', vi: 'Bảo hát hay phải không?', answer: false },
        { q: 'Can Bao cook pho?', vi: 'Bảo biết nấu phở phải không?', answer: true },
        { q: 'Can Bao swim?', vi: 'Bảo biết bơi phải không?', answer: false },
      ],
    },
    dialogue: {
      context: 'Hỏi sở thích của bạn mới.',
      lines: [
        { speaker: 'Lisa', text: 'What do you do in your free time?', vi: 'Lúc rảnh bạn làm gì?' },
        { speaker: 'You', text: 'I like reading and listening to music.', vi: 'Tôi thích đọc sách và nghe nhạc.' },
        { speaker: 'Lisa', text: 'Cool! Can you play an instrument?', vi: 'Hay đấy! Bạn chơi nhạc cụ không?' },
        { speaker: 'You', text: "No, I can't. But I can sing a little.", vi: 'Không. Nhưng tôi hát được chút chút.' },
        { speaker: 'Lisa', text: "Let's go to karaoke on Friday!", vi: 'Thứ Sáu đi karaoke nhé!' },
        { speaker: 'You', text: 'Sounds fun!', vi: 'Nghe vui đấy!' },
      ],
    },
    speak: [
      { q: 'What do you do in your free time?', vi: 'Lúc rảnh bạn làm gì?', model: 'I watch movies and play badminton.', modelVi: 'Tôi xem phim và chơi cầu lông.' },
      { q: 'Can you swim?', vi: 'Bạn biết bơi không?', model: 'Yes, I can.', modelVi: 'Có, tôi biết.' },
      { q: "What can't you do?", vi: 'Bạn không biết làm gì?', model: "I can't drive a car.", modelVi: 'Tôi không biết lái ô tô.' },
      { q: 'What music do you like?', vi: 'Bạn thích nhạc gì?', model: 'I like pop music.', modelVi: 'Tôi thích nhạc pop.' },
    ],
    tip: 'Sau "can / can\'t" động từ giữ nguyên: she can swim (không nói "she can swims").',
  },

  {
    day: 17, emoji: '🤒', title: 'Health', titleVi: 'Sức khoẻ',
    goal: 'Nói mình bị đau ở đâu, cảm thấy thế nào và xin giúp đỡ.',
    words: [
      { word: 'feel', vi: 'cảm thấy', emoji: '🫠', forms: ['feels', 'feeling'], examples: ["I don't feel well.", 'How do you feel?'] },
      { word: 'sick', vi: 'ốm', emoji: '🤒', examples: ["I'm sick today.", 'She is sick at home.'] },
      { word: 'headache', vi: 'đau đầu', emoji: '🤕', examples: ['I have a headache.', 'Too much coffee gives me a headache.'] },
      { word: 'stomachache', vi: 'đau bụng', emoji: '🤢', examples: ['I have a stomachache.', 'He has a stomachache after lunch.'] },
      { word: 'fever', vi: 'sốt', emoji: '🌡️', examples: ['I have a fever.', 'The child has a high fever.'] },
      { word: 'medicine', vi: 'thuốc', emoji: '💊', examples: ['Take this medicine.', 'I need some medicine.'] },
      { word: 'rest', vi: 'nghỉ ngơi', emoji: '🛌', examples: ['You need to rest.', 'Rest at home today.'] },
      { word: 'better', vi: 'khá hơn', emoji: '📈', examples: ['I feel better now.', 'Get better soon!'] },
    ],
    story: {
      title: 'A bad Monday',
      sentences: [
        { en: 'On Monday morning, Tam does not feel well.', vi: 'Sáng thứ Hai, Tâm thấy không khoẻ.' },
        { en: 'He has a headache and a fever.', vi: 'Anh bị đau đầu và sốt.' },
        { en: 'He calls his boss. "I am sick. I can\'t come to work today."', vi: 'Anh gọi sếp. "Tôi bị ốm. Hôm nay tôi không đi làm được."' },
        { en: 'His boss says, "No problem. Rest at home."', vi: 'Sếp nói: "Không sao. Nghỉ ở nhà đi."' },
        { en: 'Tam goes to the pharmacy. He buys some medicine.', vi: 'Tâm ra hiệu thuốc. Anh mua ít thuốc.' },
        { en: 'He takes the medicine and drinks a lot of water.', vi: 'Anh uống thuốc và uống nhiều nước.' },
        { en: 'He sleeps all day.', vi: 'Anh ngủ cả ngày.' },
        { en: 'In the evening, he feels better.', vi: 'Buổi tối, anh thấy khá hơn.' },
        { en: 'On Tuesday, he goes back to work.', vi: 'Thứ Ba, anh đi làm lại.' },
      ],
      questions: [
        { q: 'Does Tam have a headache?', vi: 'Tâm bị đau đầu phải không?', answer: true },
        { q: 'Does Tam go to work on Monday?', vi: 'Tâm đi làm vào thứ Hai phải không?', answer: false },
        { q: 'Does he buy medicine?', vi: 'Anh có mua thuốc phải không?', answer: true },
        { q: 'Does he feel worse in the evening?', vi: 'Buổi tối anh thấy tệ hơn phải không?', answer: false },
      ],
    },
    dialogue: {
      context: 'Đồng nghiệp hỏi thăm khi bạn mệt.',
      lines: [
        { speaker: 'Joe', text: 'Are you OK? You look tired.', vi: 'Bạn ổn không? Trông bạn mệt.' },
        { speaker: 'You', text: "I don't feel well. I have a stomachache.", vi: 'Tôi thấy không khoẻ. Tôi bị đau bụng.' },
        { speaker: 'Joe', text: 'Oh no. Do you need some medicine?', vi: 'Ôi. Bạn cần thuốc không?' },
        { speaker: 'You', text: "No, thanks. I think I need to rest.", vi: 'Không, cảm ơn. Chắc tôi cần nghỉ.' },
        { speaker: 'Joe', text: 'Go home and rest. Get better soon!', vi: 'Về nhà nghỉ đi. Mau khoẻ nhé!' },
        { speaker: 'You', text: 'Thank you. See you tomorrow.', vi: 'Cảm ơn. Hẹn gặp ngày mai.' },
      ],
    },
    speak: [
      { q: 'How do you feel today?', vi: 'Hôm nay bạn thấy thế nào?', model: 'I feel great, thank you.', modelVi: 'Tôi thấy rất khoẻ, cảm ơn.' },
      { q: 'Tell someone you have a headache.', vi: 'Nói bạn bị đau đầu.', model: 'I have a headache.', modelVi: 'Tôi bị đau đầu.' },
      { q: "Call your boss: you can't come to work.", vi: 'Gọi sếp: bạn không đi làm được.', model: "I'm sick. I can't come to work today.", modelVi: 'Tôi bị ốm. Hôm nay tôi không đi làm được.' },
      { q: 'Say something kind to a sick friend.', vi: 'Nói lời hỏi thăm bạn bị ốm.', model: 'Get better soon!', modelVi: 'Mau khoẻ nhé!' },
    ],
    tip: 'Bệnh dùng "I have a …": I have a headache / a fever / a cold.',
  },

  {
    day: 18, emoji: '🏨', title: 'At the Hotel', titleVi: 'Ở khách sạn',
    goal: 'Nhận phòng, hỏi thông tin và báo sự cố ở khách sạn.',
    words: [
      { word: 'reservation', vi: 'đặt chỗ trước', emoji: '📝', forms: ['booking'], examples: ['I have a reservation.', 'My booking is for two nights.'] },
      { word: 'night', vi: 'đêm', emoji: '🌃', forms: ['nights'], examples: ['One room for three nights.', 'Good night!'] },
      { word: 'key', vi: 'chìa khoá', emoji: '🔑', forms: ['keys', 'key card'], examples: ['Here is your key.', 'I lost my key.'] },
      { word: 'floor', vi: 'tầng', emoji: '🛗', examples: ['Your room is on the fifth floor.', 'Which floor?'] },
      { word: 'breakfast', vi: 'bữa sáng', emoji: '🥐', examples: ['Breakfast is from six to ten.', 'Is breakfast included?'] },
      { word: 'Wi-Fi', vi: 'wifi', emoji: '📶', examples: ["What's the Wi-Fi password?", "The Wi-Fi doesn't work."] },
      { word: "doesn't work", vi: 'không hoạt động', emoji: '⚠️', examples: ["The air conditioner doesn't work.", "The TV doesn't work."] },
      { word: 'check out', vi: 'trả phòng', emoji: '🧳', forms: ['check-out'], examples: ['What time is check-out?', 'I want to check out.'] },
    ],
    story: {
      title: 'A night in Da Lat',
      sentences: [
        { en: 'Minh arrives at a hotel in Da Lat.', vi: 'Minh đến một khách sạn ở Đà Lạt.' },
        { en: 'He says, "Hello. I have a reservation for two nights."', vi: 'Anh nói: "Xin chào. Tôi có đặt phòng hai đêm."' },
        { en: 'The receptionist gives him a key. "Room 305, on the third floor."', vi: 'Lễ tân đưa chìa khoá. "Phòng 305, tầng ba."' },
        { en: '"Breakfast is from six to ten."', vi: '"Bữa sáng từ 6 đến 10 giờ."' },
        { en: 'The room is nice, but the Wi-Fi doesn\'t work.', vi: 'Phòng đẹp, nhưng wifi không chạy.' },
        { en: 'Minh calls the front desk. "The Wi-Fi doesn\'t work."', vi: 'Minh gọi lễ tân. "Wifi không chạy."' },
        { en: '"Sorry! We can fix it in five minutes."', vi: '"Xin lỗi! Chúng tôi sửa trong năm phút."' },
        { en: 'Five minutes later, it works. Minh is happy.', vi: 'Năm phút sau, nó chạy. Minh vui.' },
        { en: 'Check-out is at twelve on Sunday.', vi: 'Trả phòng lúc 12 giờ Chủ nhật.' },
      ],
      questions: [
        { q: 'Does Minh have a reservation?', vi: 'Minh có đặt phòng trước phải không?', answer: true },
        { q: 'Is his room on the fifth floor?', vi: 'Phòng anh ở tầng năm phải không?', answer: false },
        { q: 'Does the Wi-Fi work at first?', vi: 'Lúc đầu wifi chạy phải không?', answer: false },
        { q: 'Is check-out at twelve?', vi: 'Trả phòng lúc 12 giờ phải không?', answer: true },
      ],
    },
    dialogue: {
      context: 'Nhận phòng khách sạn.',
      lines: [
        { speaker: 'Receptionist', text: 'Good evening. Can I help you?', vi: 'Chào buổi tối. Tôi giúp gì được?' },
        { speaker: 'You', text: 'Hi. I have a reservation. My name is Nguyen.', vi: 'Chào. Tôi có đặt phòng. Tên tôi là Nguyễn.' },
        { speaker: 'Receptionist', text: 'Yes, one room for three nights. Here is your key.', vi: 'Vâng, một phòng ba đêm. Đây là chìa khoá.' },
        { speaker: 'You', text: 'Thank you. Is breakfast included?', vi: 'Cảm ơn. Có kèm bữa sáng không?' },
        { speaker: 'Receptionist', text: "Yes, it's from six to ten on the first floor.", vi: 'Có, từ 6 đến 10 giờ ở tầng một.' },
        { speaker: 'You', text: "Great. What's the Wi-Fi password?", vi: 'Tuyệt. Mật khẩu wifi là gì?' },
      ],
    },
    speak: [
      { q: 'Check in at a hotel.', vi: 'Nhận phòng khách sạn.', model: 'Hi, I have a reservation. My name is Lan.', modelVi: 'Chào, tôi có đặt phòng. Tên tôi là Lan.' },
      { q: 'Ask about breakfast.', vi: 'Hỏi về bữa sáng.', model: 'What time is breakfast?', modelVi: 'Mấy giờ có bữa sáng?' },
      { q: 'Say the air conditioner is broken.', vi: 'Báo máy lạnh hỏng.', model: "The air conditioner doesn't work.", modelVi: 'Máy lạnh không chạy.' },
      { q: 'Ask about check-out time.', vi: 'Hỏi giờ trả phòng.', model: 'What time is check-out?', modelVi: 'Mấy giờ trả phòng?' },
    ],
    tip: '"…doesn\'t work" dùng cho mọi thứ bị hỏng: the TV / the shower / the light doesn\'t work.',
  },

  {
    day: 19, emoji: '📸', title: 'Last Weekend', titleVi: 'Kể chuyện cuối tuần trước',
    goal: 'Kể việc đã làm trong quá khứ bằng các động từ thường gặp.',
    words: [
      { word: 'was', vi: 'đã là, đã (quá khứ của is)', emoji: '⏪', forms: ['were'], examples: ['It was fun.', 'The weather was nice.'] },
      { word: 'went', vi: 'đã đi (quá khứ của go)', emoji: '🚶‍♂️', examples: ['I went to the beach.', 'We went to a café.'] },
      { word: 'ate', vi: 'đã ăn (quá khứ của eat)', emoji: '🍽️', examples: ['I ate seafood.', 'We ate dinner at home.'] },
      { word: 'saw', vi: 'đã xem, đã thấy (quá khứ của see)', emoji: '👀', examples: ['I saw a good movie.', 'We saw our friends.'] },
      { word: 'visited', vi: 'đã thăm', emoji: '🏡', forms: ['visit'], examples: ['I visited my grandmother.', 'We visited Hoi An.'] },
      { word: 'yesterday', vi: 'hôm qua', emoji: '⬅️', examples: ['I was tired yesterday.', 'Yesterday was Sunday.'] },
      { word: 'last weekend', vi: 'cuối tuần trước', emoji: '📆', examples: ['What did you do last weekend?', 'Last weekend I stayed home.'] },
      { word: 'fun', vi: 'vui', emoji: '🎉', examples: ['It was really fun!', 'The party was fun.'] },
    ],
    story: {
      title: 'A weekend in Vung Tau',
      sentences: [
        { en: 'Last weekend, Chi went to Vung Tau with her friends.', vi: 'Cuối tuần trước, Chi đi Vũng Tàu với bạn bè.' },
        { en: 'They went by bus. It was two hours.', vi: 'Họ đi xe buýt. Mất hai tiếng.' },
        { en: 'The weather was sunny and hot.', vi: 'Thời tiết nắng và nóng.' },
        { en: 'They swam in the sea in the morning.', vi: 'Buổi sáng họ bơi ở biển.' },
        { en: 'For lunch, they ate seafood. It was delicious.', vi: 'Bữa trưa họ ăn hải sản. Rất ngon.' },
        { en: 'In the afternoon, they visited the lighthouse.', vi: 'Buổi chiều họ thăm ngọn hải đăng.' },
        { en: 'They saw the sunset from the top.', vi: 'Họ ngắm hoàng hôn từ trên đỉnh.' },
        { en: 'On Sunday evening, they went home.', vi: 'Tối Chủ nhật họ về nhà.' },
        { en: 'Chi was tired, but the weekend was really fun.', vi: 'Chi mệt, nhưng cuối tuần rất vui.' },
      ],
      questions: [
        { q: 'Did Chi go to Vung Tau?', vi: 'Chi đi Vũng Tàu phải không?', answer: true },
        { q: 'Was the weather rainy?', vi: 'Thời tiết mưa phải không?', answer: false },
        { q: 'Did they eat seafood?', vi: 'Họ ăn hải sản phải không?', answer: true },
        { q: 'Did they go home on Saturday?', vi: 'Họ về nhà vào thứ Bảy phải không?', answer: false },
      ],
    },
    dialogue: {
      context: 'Thứ Hai, đồng nghiệp hỏi về cuối tuần.',
      lines: [
        { speaker: 'Dan', text: 'What did you do last weekend?', vi: 'Cuối tuần trước bạn làm gì?' },
        { speaker: 'You', text: 'I visited my parents in Can Tho.', vi: 'Tôi về thăm bố mẹ ở Cần Thơ.' },
        { speaker: 'Dan', text: 'Nice! How was it?', vi: 'Hay quá! Thế nào?' },
        { speaker: 'You', text: 'It was great. We ate a lot and went to the floating market.', vi: 'Rất tuyệt. Cả nhà ăn nhiều và đi chợ nổi.' },
        { speaker: 'Dan', text: 'Sounds fun!', vi: 'Nghe vui đấy!' },
        { speaker: 'You', text: 'And you? What did you do?', vi: 'Còn bạn? Bạn làm gì?' },
      ],
    },
    speak: [
      { q: 'What did you do last weekend?', vi: 'Cuối tuần trước bạn làm gì?', model: 'I went to the cinema with my friends.', modelVi: 'Tôi đi xem phim với bạn bè.' },
      { q: 'What did you eat yesterday?', vi: 'Hôm qua bạn ăn gì?', model: 'I ate chicken rice.', modelVi: 'Tôi ăn cơm gà.' },
      { q: 'How was your weekend?', vi: 'Cuối tuần của bạn thế nào?', model: 'It was fun!', modelVi: 'Rất vui!' },
      { q: 'Where did you go yesterday?', vi: 'Hôm qua bạn đi đâu?', model: 'I went to the supermarket.', modelVi: 'Tôi đi siêu thị.' },
    ],
    tip: 'Nhiều động từ quá khứ phải học thuộc: go → went, eat → ate, see → saw. Động từ thường thêm -ed: visit → visited.',
  },

  {
    day: 20, emoji: '🌟', title: 'All About Me', titleVi: 'Tổng ôn: giới thiệu bản thân và dự định',
    goal: 'Tự giới thiệu đầy đủ trong 1 phút và nói dự định sắp tới.',
    words: [
      { word: 'going to', vi: 'sẽ, dự định', emoji: '🎯', examples: ["I'm going to learn English.", "She's going to visit Japan."] },
      { word: 'learn', vi: 'học', emoji: '📖', forms: ['learning'], examples: ["I'm learning English.", 'I want to learn to swim.'] },
      { word: 'want to', vi: 'muốn', emoji: '💭', forms: ['want', 'wants'], examples: ['I want to travel.', 'He wants to be a doctor.'] },
      { word: 'next year', vi: 'năm sau', emoji: '📅', examples: ["I'm going to travel next year.", 'Next year I will be thirty.'] },
      { word: 'travel', vi: 'đi du lịch', emoji: '✈️', examples: ['I love to travel.', "I'm going to travel to Korea."] },
      { word: 'dream', vi: 'ước mơ', emoji: '🌈', examples: ['My dream is to live by the sea.', 'What is your dream?'] },
      { word: 'every day', vi: 'mỗi ngày', emoji: '🔁', examples: ['I study English every day.', 'I drink coffee every day.'] },
      { word: 'about me', vi: 'về tôi', emoji: '🙋', examples: ['Let me tell you about me.', 'This is all about me.'] },
    ],
    story: {
      title: "Huong's plan",
      sentences: [
        { en: 'Hi! My name is Huong. I am twenty-seven years old.', vi: 'Chào! Tôi tên Hương. Tôi 27 tuổi.' },
        { en: 'I am from Nghe An, but I live in Hanoi.', vi: 'Tôi đến từ Nghệ An, nhưng sống ở Hà Nội.' },
        { en: 'I am a nurse. I work at a big hospital.', vi: 'Tôi là y tá. Tôi làm ở một bệnh viện lớn.' },
        { en: 'I live with my sister in a small apartment.', vi: 'Tôi sống với em gái trong một căn hộ nhỏ.' },
        { en: 'In my free time, I like cooking and swimming.', vi: 'Lúc rảnh tôi thích nấu ăn và bơi.' },
        { en: 'I am learning English every day.', vi: 'Tôi đang học tiếng Anh mỗi ngày.' },
        { en: 'My dream is to work in Australia.', vi: 'Ước mơ của tôi là làm việc ở Úc.' },
        { en: 'Next year, I am going to take an English test.', vi: 'Năm sau, tôi sẽ thi một bài kiểm tra tiếng Anh.' },
        { en: 'I want to speak English well. I am going to try hard!', vi: 'Tôi muốn nói tiếng Anh giỏi. Tôi sẽ cố gắng hết sức!' },
      ],
      questions: [
        { q: 'Is Huong a nurse?', vi: 'Hương là y tá phải không?', answer: true },
        { q: 'Does Huong live in Nghe An?', vi: 'Hương sống ở Nghệ An phải không?', answer: false },
        { q: 'Is she learning English every day?', vi: 'Cô học tiếng Anh mỗi ngày phải không?', answer: true },
        { q: 'Is her dream to work in Japan?', vi: 'Ước mơ của cô là làm ở Nhật phải không?', answer: false },
      ],
    },
    dialogue: {
      context: 'Phỏng vấn ngắn ở một câu lạc bộ tiếng Anh.',
      lines: [
        { speaker: 'Host', text: 'Welcome! Can you tell us about yourself?', vi: 'Chào mừng! Bạn giới thiệu về mình nhé?' },
        { speaker: 'You', text: "Sure. I'm Nam. I'm thirty and I'm from Da Nang.", vi: 'Vâng. Tôi là Nam. Tôi 30 tuổi, đến từ Đà Nẵng.' },
        { speaker: 'Host', text: 'What do you do?', vi: 'Bạn làm nghề gì?' },
        { speaker: 'You', text: "I'm a designer. I work for a small company.", vi: 'Tôi là nhà thiết kế. Tôi làm cho một công ty nhỏ.' },
        { speaker: 'Host', text: 'Why are you learning English?', vi: 'Sao bạn học tiếng Anh?' },
        { speaker: 'You', text: "I want to travel. Next year I'm going to visit Europe.", vi: 'Tôi muốn đi du lịch. Năm sau tôi sẽ đi châu Âu.' },
      ],
    },
    speak: [
      { q: 'Tell us about yourself: name, age, city.', vi: 'Giới thiệu: tên, tuổi, thành phố.', model: "I'm Lan. I'm twenty-five and I live in Hanoi.", modelVi: 'Tôi là Lan. Tôi 25 tuổi và sống ở Hà Nội.' },
      { q: 'What do you do and what do you like?', vi: 'Bạn làm gì và thích gì?', model: "I'm an office worker. I like music and cooking.", modelVi: 'Tôi là nhân viên văn phòng. Tôi thích âm nhạc và nấu ăn.' },
      { q: 'Why are you learning English?', vi: 'Sao bạn học tiếng Anh?', model: 'I want to talk to people from other countries.', modelVi: 'Tôi muốn nói chuyện với người nước ngoài.' },
      { q: 'What are you going to do next year?', vi: 'Năm sau bạn định làm gì?', model: "I'm going to travel to Thailand.", modelVi: 'Tôi sẽ đi du lịch Thái Lan.' },
    ],
    tip: 'Dự định dùng "be going to + động từ": I\'m going to travel. Hãy ghép các câu của 20 ngày thành một bài giới thiệu 1 phút.',
  },
];
