import type { A1Day } from './types';

export const days6to10: A1Day[] = [
  {
    day: 6, emoji: '⏰', title: 'My Day', titleVi: 'Một ngày của tôi',
    goal: 'Kể lịch sinh hoạt hằng ngày và nói giờ.',
    words: [
      { word: 'get up', vi: 'thức dậy', emoji: '🛏️', forms: ['gets up'], examples: ['I get up at six.', 'She gets up early.'] },
      { word: 'breakfast', vi: 'bữa sáng', emoji: '🍳', examples: ['I have breakfast at seven.', 'Breakfast is bread and eggs.'] },
      { word: "o'clock", vi: 'giờ đúng', emoji: '🕗', examples: ["It's eight o'clock.", "I start work at nine o'clock."] },
      { word: 'go to work', vi: 'đi làm', emoji: '🚶', forms: ['goes to work'], examples: ['I go to work by bus.', 'He goes to work at eight.'] },
      { word: 'lunch', vi: 'bữa trưa', emoji: '🥪', examples: ['I have lunch at twelve.', 'Lunch is rice and chicken.'] },
      { word: 'go home', vi: 'về nhà', emoji: '🏠', forms: ['goes home'], examples: ['I go home at six.', 'She goes home late.'] },
      { word: 'dinner', vi: 'bữa tối', emoji: '🍲', examples: ['We have dinner at seven.', 'Dinner is ready!'] },
      { word: 'go to bed', vi: 'đi ngủ', emoji: '😴', forms: ['goes to bed'], examples: ['I go to bed at eleven.', 'He goes to bed late.'] },
    ],
    story: {
      title: "Long's day",
      sentences: [
        { en: 'Long gets up at six o\'clock.', vi: 'Long thức dậy lúc 6 giờ.' },
        { en: 'He has breakfast with his wife. Breakfast is pho.', vi: 'Anh ăn sáng với vợ. Bữa sáng là phở.' },
        { en: 'He goes to work at seven thirty.', vi: 'Anh đi làm lúc 7 giờ 30.' },
        { en: 'He works in an office from eight to five.', vi: 'Anh làm ở văn phòng từ 8 đến 5 giờ.' },
        { en: 'He has lunch at twelve with his friends.', vi: 'Anh ăn trưa lúc 12 giờ với bạn bè.' },
        { en: 'He goes home at five thirty.', vi: 'Anh về nhà lúc 5 giờ 30.' },
        { en: 'He has dinner with his family at seven.', vi: 'Anh ăn tối với gia đình lúc 7 giờ.' },
        { en: 'After dinner, he watches TV.', vi: 'Sau bữa tối, anh xem TV.' },
        { en: 'He goes to bed at eleven o\'clock. He is very tired.', vi: 'Anh đi ngủ lúc 11 giờ. Anh rất mệt.' },
      ],
      questions: [
        { q: 'Does Long get up at six?', vi: 'Long dậy lúc 6 giờ phải không?', answer: true },
        { q: 'Is breakfast bread?', vi: 'Bữa sáng là bánh mì phải không?', answer: false },
        { q: 'Does Long have lunch at twelve?', vi: 'Long ăn trưa lúc 12 giờ phải không?', answer: true },
        { q: 'Does Long go to bed at ten?', vi: 'Long đi ngủ lúc 10 giờ phải không?', answer: false },
      ],
    },
    dialogue: {
      context: 'Bạn bè hỏi về lịch hằng ngày.',
      lines: [
        { speaker: 'Kate', text: 'What time do you get up?', vi: 'Bạn dậy lúc mấy giờ?' },
        { speaker: 'You', text: 'I get up at six thirty.', vi: 'Tôi dậy lúc 6 rưỡi.' },
        { speaker: 'Kate', text: "Wow, that's early! What time do you start work?", vi: 'Wow, sớm vậy! Mấy giờ bạn bắt đầu làm?' },
        { speaker: 'You', text: "At eight o'clock. And you?", vi: 'Lúc 8 giờ. Còn bạn?' },
        { speaker: 'Kate', text: 'I start at ten. I get up at nine!', vi: 'Tôi bắt đầu lúc 10. Tôi dậy lúc 9!' },
        { speaker: 'You', text: 'Lucky you!', vi: 'Sướng thế!' },
      ],
    },
    speak: [
      { q: 'What time do you get up?', vi: 'Bạn dậy lúc mấy giờ?', model: 'I get up at six.', modelVi: 'Tôi dậy lúc 6 giờ.' },
      { q: 'What do you have for breakfast?', vi: 'Bạn ăn sáng món gì?', model: 'I have bread and coffee.', modelVi: 'Tôi ăn bánh mì và uống cà phê.' },
      { q: 'What time do you go home?', vi: 'Mấy giờ bạn về nhà?', model: 'I go home at half past five.', modelVi: 'Tôi về nhà lúc 5 rưỡi.' },
      { q: 'What time do you go to bed?', vi: 'Mấy giờ bạn đi ngủ?', model: 'I go to bed at eleven.', modelVi: 'Tôi đi ngủ lúc 11 giờ.' },
    ],
    tip: 'Giờ dùng "at": at six, at seven thirty. "Half past five" = 5 rưỡi.',
  },

  {
    day: 7, emoji: '🍜', title: 'Food & Drinks', titleVi: 'Đồ ăn và thức uống',
    goal: 'Nói mình thích và không thích ăn uống gì.',
    words: [
      { word: 'like', vi: 'thích', emoji: '❤️', forms: ['likes'], examples: ['I like coffee.', 'She likes fish.'] },
      { word: "don't like", vi: 'không thích', emoji: '🙅', forms: ["doesn't like", 'does not like'], examples: ["I don't like milk.", "He doesn't like spicy food."] },
      { word: 'rice', vi: 'cơm, gạo', emoji: '🍚', examples: ['We eat rice every day.', 'Rice and chicken, please.'] },
      { word: 'chicken', vi: 'thịt gà', emoji: '🍗', examples: ['I like chicken.', 'Chicken soup is good.'] },
      { word: 'fruit', vi: 'trái cây', emoji: '🍎', examples: ['I eat fruit every day.', 'Mango is my favorite fruit.'] },
      { word: 'water', vi: 'nước', emoji: '💧', examples: ['Can I have some water?', 'I drink a lot of water.'] },
      { word: 'spicy', vi: 'cay', emoji: '🌶️', examples: ['This soup is spicy!', 'I love spicy food.'] },
      { word: 'favorite', vi: 'yêu thích nhất', emoji: '⭐', forms: ['favourite'], examples: ['My favorite food is pho.', "What's your favorite drink?"] },
    ],
    story: {
      title: 'Peter likes Vietnamese food',
      sentences: [
        { en: 'Peter is from Canada. He lives in Saigon.', vi: 'Peter đến từ Canada. Anh sống ở Sài Gòn.' },
        { en: 'Peter likes Vietnamese food.', vi: 'Peter thích đồ ăn Việt Nam.' },
        { en: 'He likes rice, chicken and fish.', vi: 'Anh thích cơm, gà và cá.' },
        { en: 'His favorite food is broken rice.', vi: 'Món anh thích nhất là cơm tấm.' },
        { en: 'But Peter does not like spicy food.', vi: 'Nhưng Peter không thích đồ cay.' },
        { en: 'His friend Thu loves spicy food.', vi: 'Bạn anh, Thu, rất thích đồ cay.' },
        { en: 'Thu eats chili every day!', vi: 'Thu ăn ớt mỗi ngày!' },
        { en: 'Peter drinks a lot of water. Thu drinks iced tea.', vi: 'Peter uống nhiều nước. Thu uống trà đá.' },
        { en: 'After lunch, they eat fruit. They both like mango.', vi: 'Sau bữa trưa, họ ăn trái cây. Cả hai đều thích xoài.' },
      ],
      questions: [
        { q: 'Does Peter like Vietnamese food?', vi: 'Peter thích đồ ăn Việt phải không?', answer: true },
        { q: 'Does Peter like spicy food?', vi: 'Peter thích đồ cay phải không?', answer: false },
        { q: 'Does Thu drink iced tea?', vi: 'Thu uống trà đá phải không?', answer: true },
        { q: 'Do they both like mango?', vi: 'Cả hai đều thích xoài phải không?', answer: true },
      ],
    },
    dialogue: {
      context: 'Rủ đồng nghiệp đi ăn trưa.',
      lines: [
        { speaker: 'Ben', text: "I'm hungry. Let's have lunch!", vi: 'Tôi đói. Đi ăn trưa thôi!' },
        { speaker: 'You', text: 'Good idea. Do you like noodles?', vi: 'Ý hay. Bạn thích mì/bún không?' },
        { speaker: 'Ben', text: 'Yes, I love noodles. But not spicy, please.', vi: 'Có, tôi rất thích. Nhưng đừng cay nhé.' },
        { speaker: 'You', text: 'No problem. What do you want to drink?', vi: 'Không sao. Bạn muốn uống gì?' },
        { speaker: 'Ben', text: 'Just water. And you?', vi: 'Nước lọc thôi. Còn bạn?' },
        { speaker: 'You', text: "I'd like an iced coffee.", vi: 'Tôi muốn một ly cà phê đá.' },
      ],
    },
    speak: [
      { q: 'What is your favorite food?', vi: 'Món ăn yêu thích của bạn là gì?', model: 'My favorite food is pho.', modelVi: 'Món tôi thích nhất là phở.' },
      { q: 'Do you like spicy food?', vi: 'Bạn thích đồ cay không?', model: 'Yes, I like spicy food.', modelVi: 'Có, tôi thích đồ cay.' },
      { q: "What food don't you like?", vi: 'Bạn không thích món gì?', model: "I don't like milk.", modelVi: 'Tôi không thích sữa.' },
      { q: 'What do you drink every day?', vi: 'Bạn uống gì mỗi ngày?', model: 'I drink coffee and water every day.', modelVi: 'Tôi uống cà phê và nước mỗi ngày.' },
    ],
    tip: 'Phủ định: I don\'t like…, nhưng he/she doesn\'t like… (động từ sau doesn\'t không thêm s).',
  },

  {
    day: 8, emoji: '☕', title: 'At the Café', titleVi: 'Gọi món ở quán',
    goal: 'Gọi đồ uống, đồ ăn và thanh toán ở quán.',
    words: [
      { word: 'can I have', vi: 'cho tôi…', emoji: '🙋', examples: ['Can I have a coffee, please?', 'Can I have the menu?'] },
      { word: 'please', vi: 'làm ơn (lịch sự)', emoji: '🙏', examples: ['A tea, please.', 'Water, please.'] },
      { word: 'menu', vi: 'thực đơn', emoji: '📋', examples: ['Can I see the menu?', 'The menu is in English.'] },
      { word: 'cup', vi: 'tách, ly', emoji: '☕', forms: ['cups'], examples: ['A cup of tea, please.', 'Two cups of coffee.'] },
      { word: 'small', vi: 'nhỏ', emoji: '🔹', examples: ['A small coffee, please.', 'This cup is small.'] },
      { word: 'large', vi: 'lớn', emoji: '🔷', examples: ['A large tea, please.', 'Large or small?'] },
      { word: 'how much', vi: 'bao nhiêu tiền', emoji: '💰', examples: ['How much is it?', 'How much is the cake?'] },
      { word: 'here you are', vi: 'đây ạ (khi đưa đồ)', emoji: '🫴', examples: ['Your coffee. Here you are.', 'Here you are. Thank you!'] },
    ],
    story: {
      title: 'A busy morning at the café',
      sentences: [
        { en: 'It is eight o\'clock. The café is busy.', vi: 'Bây giờ là 8 giờ. Quán đang đông.' },
        { en: 'Ana looks at the menu.', vi: 'Ana nhìn thực đơn.' },
        { en: 'She says, "Can I have a large coffee, please?"', vi: 'Cô nói: "Cho tôi một ly cà phê lớn nhé?"' },
        { en: 'The waiter asks, "With milk?"', vi: 'Người phục vụ hỏi: "Có sữa không?"' },
        { en: 'Ana says, "No milk, please. And a small cake."', vi: 'Ana nói: "Không sữa nhé. Và một cái bánh nhỏ."' },
        { en: 'She asks, "How much is it?"', vi: 'Cô hỏi: "Bao nhiêu tiền?"' },
        { en: 'The waiter says, "Five dollars, please."', vi: 'Người phục vụ nói: "Năm đô ạ."' },
        { en: 'Ana gives him the money. "Here you are."', vi: 'Ana đưa tiền. "Đây ạ."' },
        { en: 'The waiter says, "Thank you! Have a nice day!"', vi: 'Người phục vụ nói: "Cảm ơn! Chúc một ngày tốt lành!"' },
      ],
      questions: [
        { q: 'Is the café busy?', vi: 'Quán đông phải không?', answer: true },
        { q: 'Does Ana want a small coffee?', vi: 'Ana muốn cà phê nhỏ phải không?', answer: false },
        { q: 'Does Ana want milk?', vi: 'Ana muốn có sữa phải không?', answer: false },
        { q: 'Is it five dollars?', vi: 'Tổng là năm đô phải không?', answer: true },
      ],
    },
    dialogue: {
      context: 'Gọi đồ ở quán cà phê.',
      lines: [
        { speaker: 'Waiter', text: 'Hi! What would you like?', vi: 'Chào! Bạn muốn dùng gì?' },
        { speaker: 'You', text: 'Can I have a cup of tea, please?', vi: 'Cho tôi một tách trà nhé?' },
        { speaker: 'Waiter', text: 'Small or large?', vi: 'Nhỏ hay lớn?' },
        { speaker: 'You', text: 'Small, please. How much is it?', vi: 'Nhỏ nhé. Bao nhiêu tiền?' },
        { speaker: 'Waiter', text: "It's three dollars.", vi: 'Ba đô.' },
        { speaker: 'You', text: 'Here you are. Thank you!', vi: 'Đây ạ. Cảm ơn!' },
      ],
    },
    speak: [
      { q: 'Order a coffee.', vi: 'Gọi một ly cà phê.', model: 'Can I have a coffee, please?', modelVi: 'Cho tôi một ly cà phê nhé?' },
      { q: 'Ask for the menu.', vi: 'Xin thực đơn.', model: 'Can I see the menu, please?', modelVi: 'Cho tôi xem thực đơn nhé?' },
      { q: 'Ask the price.', vi: 'Hỏi giá.', model: 'How much is it?', modelVi: 'Bao nhiêu tiền?' },
      { q: 'Small or large?', vi: 'Nhỏ hay lớn?', model: 'Large, please.', modelVi: 'Lớn nhé.' },
    ],
    tip: '"Can I have…, please?" là câu gọi món lịch sự và dễ nhất. Thêm "please" ở cuối là đủ lịch sự.',
  },

  {
    day: 9, emoji: '🛒', title: 'Shopping', titleVi: 'Mua sắm và giá cả',
    goal: 'Hỏi giá, chọn món và trả tiền khi đi chợ, siêu thị.',
    words: [
      { word: 'buy', vi: 'mua', emoji: '🛍️', forms: ['buys'], examples: ['I want to buy a bag.', 'She buys fruit at the market.'] },
      { word: 'cheap', vi: 'rẻ', emoji: '🪙', examples: ['This shirt is cheap.', 'The market is cheap.'] },
      { word: 'expensive', vi: 'đắt', emoji: '💎', examples: ['That phone is expensive.', "It's too expensive!"] },
      { word: 'this', vi: 'cái này', emoji: '👇', forms: ['these'], examples: ['How much is this?', 'I like this one.'] },
      { word: 'that', vi: 'cái kia', emoji: '👉', forms: ['those'], examples: ['How much is that bag?', 'I want that one.'] },
      { word: 'market', vi: 'chợ', emoji: '🧺', examples: ['I go to the market on Sunday.', 'The market is near my house.'] },
      { word: 'card', vi: 'thẻ', emoji: '💳', examples: ['Can I pay by card?', 'I only have a card.'] },
      { word: 'cash', vi: 'tiền mặt', emoji: '💵', examples: ['Do you have cash?', 'I pay in cash.'] },
    ],
    story: {
      title: 'At the market',
      sentences: [
        { en: 'On Sunday, Hien goes to the market.', vi: 'Chủ nhật, Hiền đi chợ.' },
        { en: 'She wants to buy fruit and a bag.', vi: 'Cô muốn mua trái cây và một cái túi.' },
        { en: 'She asks, "How much are these mangoes?"', vi: 'Cô hỏi: "Xoài này bao nhiêu?"' },
        { en: 'The man says, "Thirty thousand a kilo." That is cheap!', vi: 'Người bán nói: "Ba mươi nghìn một ký." Rẻ quá!' },
        { en: 'Hien buys two kilos.', vi: 'Hiền mua hai ký.' },
        { en: 'Then she sees a red bag. "How much is that bag?"', vi: 'Rồi cô thấy một cái túi đỏ. "Cái túi kia bao nhiêu?"' },
        { en: '"Five hundred thousand." That is expensive!', vi: '"Năm trăm nghìn." Đắt quá!' },
        { en: 'Hien says, "Can you make it cheaper?"', vi: 'Hiền nói: "Bớt được không?"' },
        { en: 'The woman says, "OK, four hundred." Hien pays in cash.', vi: 'Người bán nói: "Ok, bốn trăm." Hiền trả tiền mặt.' },
      ],
      questions: [
        { q: 'Does Hien go to the market on Sunday?', vi: 'Hiền đi chợ vào Chủ nhật phải không?', answer: true },
        { q: 'Are the mangoes expensive?', vi: 'Xoài đắt phải không?', answer: false },
        { q: 'Is the bag blue?', vi: 'Cái túi màu xanh phải không?', answer: false },
        { q: 'Does Hien pay by card?', vi: 'Hiền trả bằng thẻ phải không?', answer: false },
      ],
    },
    dialogue: {
      context: 'Mua áo ở cửa hàng.',
      lines: [
        { speaker: 'Seller', text: 'Hello! Can I help you?', vi: 'Xin chào! Tôi giúp gì được?' },
        { speaker: 'You', text: 'Yes. How much is this T-shirt?', vi: 'Vâng. Áo thun này bao nhiêu?' },
        { speaker: 'Seller', text: "It's twelve dollars.", vi: 'Mười hai đô.' },
        { speaker: 'You', text: "OK, I'll take it. Can I pay by card?", vi: 'Ok, tôi lấy. Tôi trả thẻ được không?' },
        { speaker: 'Seller', text: 'Sorry, cash only.', vi: 'Xin lỗi, chỉ nhận tiền mặt.' },
        { speaker: 'You', text: 'No problem. Here you are.', vi: 'Không sao. Đây ạ.' },
      ],
    },
    speak: [
      { q: 'Ask the price of a bag.', vi: 'Hỏi giá cái túi.', model: 'How much is this bag?', modelVi: 'Cái túi này bao nhiêu?' },
      { q: "Say it's too expensive.", vi: 'Nói là đắt quá.', model: "It's too expensive.", modelVi: 'Đắt quá.' },
      { q: 'Ask to pay by card.', vi: 'Hỏi trả bằng thẻ.', model: 'Can I pay by card?', modelVi: 'Tôi trả bằng thẻ được không?' },
      { q: 'Say you want to buy it.', vi: 'Nói bạn mua nó.', model: "OK, I'll take it.", modelVi: 'Ok, tôi lấy cái này.' },
    ],
    tip: 'How much is this? (1 cái) — How much are these? (nhiều cái). "I\'ll take it" = tôi lấy cái này.',
  },

  {
    day: 10, emoji: '👕', title: 'Clothes & Colors', titleVi: 'Quần áo và màu sắc',
    goal: 'Tả quần áo, màu sắc và nói mình đang mặc gì.',
    words: [
      { word: 'wear', vi: 'mặc, đội, đeo', emoji: '🧥', forms: ['wears', 'wearing'], examples: ["I'm wearing a blue shirt.", 'She wears glasses.'] },
      { word: 'shirt', vi: 'áo sơ mi', emoji: '👔', forms: ['T-shirt', 'shirts'], examples: ['A white shirt.', 'I like your T-shirt.'] },
      { word: 'dress', vi: 'váy liền', emoji: '👗', examples: ['She is wearing a red dress.', 'This dress is beautiful.'] },
      { word: 'shoes', vi: 'giày', emoji: '👟', examples: ['My shoes are black.', 'I need new shoes.'] },
      { word: 'black', vi: 'màu đen', emoji: '⚫', examples: ['A black bag.', 'My hair is black.'] },
      { word: 'white', vi: 'màu trắng', emoji: '⚪', examples: ['White shoes.', 'The wall is white.'] },
      { word: 'red', vi: 'màu đỏ', emoji: '🔴', examples: ['A red dress.', 'I like red.'] },
      { word: 'blue', vi: 'màu xanh dương', emoji: '🔵', examples: ['Blue jeans.', 'The sky is blue.'] },
    ],
    story: {
      title: 'The party',
      sentences: [
        { en: 'Tonight there is a party.', vi: 'Tối nay có một bữa tiệc.' },
        { en: 'Vy is wearing a red dress and white shoes.', vi: 'Vy mặc váy đỏ và giày trắng.' },
        { en: 'Her friend Tuan is wearing a blue shirt and black jeans.', vi: 'Bạn cô, Tuấn, mặc áo sơ mi xanh và quần jean đen.' },
        { en: 'Vy says, "I like your shirt, Tuan!"', vi: 'Vy nói: "Mình thích áo của bạn, Tuấn!"' },
        { en: 'Tuan says, "Thanks! Your dress is beautiful."', vi: 'Tuấn nói: "Cảm ơn! Váy của bạn đẹp quá."' },
        { en: 'Then Mike comes. Mike is wearing a red dress too!', vi: 'Rồi Mike đến. Mike cũng mặc váy đỏ!' },
        { en: 'Everyone laughs.', vi: 'Mọi người cười.' },
        { en: 'Mike says, "It is a joke! My real shirt is in the car."', vi: 'Mike nói: "Đùa thôi! Áo thật của mình trong xe."' },
      ],
      questions: [
        { q: 'Is Vy wearing a red dress?', vi: 'Vy mặc váy đỏ phải không?', answer: true },
        { q: 'Are Vy\'s shoes black?', vi: 'Giày của Vy màu đen phải không?', answer: false },
        { q: 'Is Tuan wearing a blue shirt?', vi: 'Tuấn mặc áo xanh phải không?', answer: true },
        { q: 'Is Mike\'s red dress a joke?', vi: 'Váy đỏ của Mike là trò đùa phải không?', answer: true },
      ],
    },
    dialogue: {
      context: 'Khen đồ của bạn bè.',
      lines: [
        { speaker: 'Lucy', text: 'I love your jacket!', vi: 'Mình rất thích áo khoác của bạn!' },
        { speaker: 'You', text: "Thanks! It's new.", vi: 'Cảm ơn! Nó mới đấy.' },
        { speaker: 'Lucy', text: 'The color is great. Is it dark blue?', vi: 'Màu đẹp quá. Xanh đậm à?' },
        { speaker: 'You', text: "Yes, it's my favorite color.", vi: 'Ừ, màu mình thích nhất.' },
        { speaker: 'Lucy', text: 'Where is it from?', vi: 'Mua ở đâu vậy?' },
        { speaker: 'You', text: "It's from a small shop near my house.", vi: 'Từ một cửa hàng nhỏ gần nhà mình.' },
      ],
    },
    speak: [
      { q: 'What are you wearing today?', vi: 'Hôm nay bạn mặc gì?', model: "I'm wearing a white T-shirt and black jeans.", modelVi: 'Tôi mặc áo thun trắng và quần jean đen.' },
      { q: 'What is your favorite color?', vi: 'Màu yêu thích của bạn là gì?', model: 'My favorite color is blue.', modelVi: 'Màu tôi thích nhất là xanh dương.' },
      { q: 'Say something nice about a friend\'s clothes.', vi: 'Khen quần áo của bạn bè.', model: 'I like your shirt!', modelVi: 'Mình thích áo của bạn!' },
      { q: 'What color are your shoes?', vi: 'Giày của bạn màu gì?', model: 'My shoes are black.', modelVi: 'Giày tôi màu đen.' },
    ],
    tip: 'Tính từ đứng trước danh từ: a red dress (không nói "a dress red").',
  },
];
