import type { A1Day } from './types';

export const days1to5: A1Day[] = [
  {
    day: 1, emoji: '👋', title: 'Hello!', titleVi: 'Chào hỏi và giới thiệu tên',
    goal: 'Chào hỏi, nói tên mình, hỏi tên người khác và hỏi thăm sức khoẻ.',
    words: [
      { word: 'hello', vi: 'xin chào', emoji: '👋', forms: ['hi'], examples: ['Hello! I am Nam.', 'Hi, Anna!'] },
      { word: 'name', vi: 'tên', emoji: '📛', forms: ['names'], examples: ['My name is Nam.', 'What is your name?'] },
      { word: 'nice to meet you', vi: 'rất vui được gặp bạn', emoji: '🤝', examples: ['Hi, Anna. Nice to meet you.', 'Nice to meet you too.'] },
      { word: 'how are you', vi: 'bạn khoẻ không', emoji: '🙂', examples: ['Hello, Tom. How are you?', 'How are you today?'] },
      { word: 'fine', vi: 'khoẻ, ổn', emoji: '👍', examples: ["I'm fine, thank you.", 'I am fine. And you?'] },
      { word: 'thank you', vi: 'cảm ơn', emoji: '🙏', forms: ['thanks'], examples: ['Thank you!', "I'm fine, thanks."] },
      { word: 'friend', vi: 'bạn bè', emoji: '🧑‍🤝‍🧑', forms: ['friends'], examples: ['Tom is my friend.', 'This is my friend, Lan.'] },
      { word: 'goodbye', vi: 'tạm biệt', emoji: '🖐️', forms: ['bye'], examples: ['Goodbye, Anna!', 'Bye! See you tomorrow.'] },
    ],
    story: {
      title: 'Nam and Anna',
      sentences: [
        { en: 'This is Nam.', vi: 'Đây là Nam.' },
        { en: 'Nam is from Vietnam.', vi: 'Nam đến từ Việt Nam.' },
        { en: 'This is Anna.', vi: 'Đây là Anna.' },
        { en: 'Anna is from England.', vi: 'Anna đến từ Anh.' },
        { en: 'Nam says, "Hello! My name is Nam."', vi: 'Nam nói: "Xin chào! Tên tôi là Nam."' },
        { en: 'Anna says, "Hi, Nam! My name is Anna. Nice to meet you."', vi: 'Anna nói: "Chào Nam! Tên tôi là Anna. Rất vui được gặp bạn."' },
        { en: 'Nam says, "Nice to meet you too. How are you?"', vi: 'Nam nói: "Tôi cũng rất vui. Bạn khoẻ không?"' },
        { en: 'Anna is fine. Nam is fine too.', vi: 'Anna khoẻ. Nam cũng khoẻ.' },
        { en: 'Now Nam and Anna are friends.', vi: 'Bây giờ Nam và Anna là bạn bè.' },
        { en: 'They say goodbye. "Bye, Anna!" "Bye, Nam!"', vi: 'Họ chào tạm biệt. "Tạm biệt Anna!" "Tạm biệt Nam!"' },
      ],
      questions: [
        { q: 'Is Nam from Vietnam?', vi: 'Nam đến từ Việt Nam phải không?', answer: true },
        { q: 'Is Anna from Vietnam?', vi: 'Anna đến từ Việt Nam phải không?', answer: false },
        { q: 'Is Anna fine?', vi: 'Anna có khoẻ không?', answer: true },
        { q: 'Are Nam and Anna friends now?', vi: 'Bây giờ Nam và Anna là bạn phải không?', answer: true },
      ],
    },
    dialogue: {
      context: 'Gặp một người mới ở lớp học.',
      lines: [
        { speaker: 'Tom', text: 'Hi! My name is Tom.', vi: 'Chào! Tên tôi là Tom.' },
        { speaker: 'You', text: 'Hello, Tom. My name is Lan.', vi: 'Xin chào Tom. Tên tôi là Lan.' },
        { speaker: 'Tom', text: 'Nice to meet you, Lan.', vi: 'Rất vui được gặp bạn, Lan.' },
        { speaker: 'You', text: 'Nice to meet you too. How are you?', vi: 'Tôi cũng rất vui. Bạn khoẻ không?' },
        { speaker: 'Tom', text: "I'm fine, thanks. And you?", vi: 'Tôi khoẻ, cảm ơn. Còn bạn?' },
        { speaker: 'You', text: "I'm fine too. Thank you.", vi: 'Tôi cũng khoẻ. Cảm ơn.' },
      ],
    },
    speak: [
      { q: 'What is your name?', vi: 'Tên bạn là gì?', model: 'My name is Lan.', modelVi: 'Tên tôi là Lan.' },
      { q: 'How are you?', vi: 'Bạn khoẻ không?', model: "I'm fine, thank you. And you?", modelVi: 'Tôi khoẻ, cảm ơn. Còn bạn?' },
      { q: 'Say hello to a new friend.', vi: 'Chào một người bạn mới.', model: 'Hi! Nice to meet you.', modelVi: 'Chào! Rất vui được gặp bạn.' },
      { q: 'Say goodbye.', vi: 'Nói lời tạm biệt.', model: 'Goodbye! See you tomorrow.', modelVi: 'Tạm biệt! Hẹn gặp ngày mai.' },
    ],
    tip: '"I\'m" = "I am". Khi nói, người bản xứ gần như luôn dùng dạng rút gọn: I\'m fine, I\'m Lan.',
  },

  {
    day: 2, emoji: '🔢', title: 'Numbers & Age', titleVi: 'Số đếm, tuổi và số điện thoại',
    goal: 'Đếm từ 1 đến 100, nói tuổi và đọc số điện thoại.',
    words: [
      { word: 'one', vi: 'một', emoji: '1️⃣', examples: ['I have one cat.', 'One, two, three.'] },
      { word: 'ten', vi: 'mười', emoji: '🔟', examples: ['I have ten fingers.', 'Ten, eleven, twelve.'] },
      { word: 'twenty', vi: 'hai mươi', emoji: '2️⃣0️⃣', forms: ['twenty-five'], examples: ['She is twenty.', 'Twenty, thirty, forty.'] },
      { word: 'old', vi: 'tuổi (… years old)', emoji: '🎂', examples: ['I am twenty-five years old.', 'How old are you?'] },
      { word: 'year', vi: 'năm', emoji: '📅', forms: ['years'], examples: ['He is ten years old.', 'One year has twelve months.'] },
      { word: 'phone number', vi: 'số điện thoại', emoji: '📱', examples: ["What's your phone number?", 'My phone number is 0912 345 678.'] },
      { word: 'birthday', vi: 'sinh nhật', emoji: '🎉', examples: ['Today is my birthday!', 'Happy birthday, Anna!'] },
      { word: 'how many', vi: 'bao nhiêu (đếm được)', emoji: '❓', examples: ['How many brothers do you have?', 'How many cats? Two cats.'] },
    ],
    story: {
      title: "Mai's birthday",
      sentences: [
        { en: 'This is Mai.', vi: 'Đây là Mai.' },
        { en: 'Today is her birthday.', vi: 'Hôm nay là sinh nhật cô ấy.' },
        { en: 'Mai is twenty-five years old.', vi: 'Mai hai mươi lăm tuổi.' },
        { en: 'Her friend Ben is thirty years old.', vi: 'Bạn của cô, Ben, ba mươi tuổi.' },
        { en: 'Ben says, "Happy birthday, Mai! How old are you?"', vi: 'Ben nói: "Chúc mừng sinh nhật Mai! Bạn bao nhiêu tuổi?"' },
        { en: 'Mai says, "I am twenty-five."', vi: 'Mai nói: "Mình hai mươi lăm tuổi."' },
        { en: 'There is one cake and ten candles.', vi: 'Có một cái bánh và mười cây nến.' },
        { en: 'Ben asks, "How many friends are here?" Mai says, "Twenty friends!"', vi: 'Ben hỏi: "Có bao nhiêu bạn ở đây?" Mai nói: "Hai mươi người bạn!"' },
        { en: 'Ben asks, "What is your phone number?"', vi: 'Ben hỏi: "Số điện thoại của bạn là gì?"' },
        { en: 'Mai says, "It is 0987 654 321."', vi: 'Mai nói: "Là 0987 654 321."' },
      ],
      questions: [
        { q: 'Is Mai twenty-five years old?', vi: 'Mai 25 tuổi phải không?', answer: true },
        { q: 'Is Ben twenty years old?', vi: 'Ben 20 tuổi phải không?', answer: false },
        { q: 'Are there ten candles?', vi: 'Có mười cây nến phải không?', answer: true },
        { q: 'Is it Ben\'s birthday?', vi: 'Hôm nay là sinh nhật Ben phải không?', answer: false },
      ],
    },
    dialogue: {
      context: 'Làm quen và xin số điện thoại.',
      lines: [
        { speaker: 'Sara', text: 'How old are you, Minh?', vi: 'Minh bao nhiêu tuổi?' },
        { speaker: 'You', text: "I'm twenty-eight. And you?", vi: 'Mình 28. Còn bạn?' },
        { speaker: 'Sara', text: "I'm thirty-one.", vi: 'Mình 31.' },
        { speaker: 'You', text: "What's your phone number?", vi: 'Số điện thoại của bạn là gì?' },
        { speaker: 'Sara', text: "It's 0903 112 456.", vi: 'Là 0903 112 456.' },
        { speaker: 'You', text: 'Sorry, can you say that again?', vi: 'Xin lỗi, bạn nói lại được không?' },
        { speaker: 'Sara', text: 'Sure. 0903 112 456.', vi: 'Được. 0903 112 456.' },
      ],
    },
    speak: [
      { q: 'How old are you?', vi: 'Bạn bao nhiêu tuổi?', model: "I'm twenty-six years old.", modelVi: 'Tôi 26 tuổi.' },
      { q: 'What is your phone number?', vi: 'Số điện thoại của bạn là gì?', model: "It's 0912 345 678.", modelVi: 'Là 0912 345 678.' },
      { q: 'When is your birthday?', vi: 'Sinh nhật bạn khi nào?', model: 'My birthday is in May.', modelVi: 'Sinh nhật tôi vào tháng Năm.' },
      { q: 'Count from one to ten.', vi: 'Đếm từ 1 đến 10.', model: 'One, two, three, four, five, six, seven, eight, nine, ten.', modelVi: 'Một đến mười.' },
    ],
    tip: 'Số điện thoại đọc từng chữ số, số 0 thường đọc là "oh": 0912 → "oh nine one two".',
  },

  {
    day: 3, emoji: '🌏', title: 'Where Are You From?', titleVi: 'Quốc gia và quê quán',
    goal: 'Nói mình đến từ đâu, sống ở đâu, nói được ngôn ngữ gì.',
    words: [
      { word: 'from', vi: 'đến từ', emoji: '📍', examples: ["I'm from Vietnam.", 'Where are you from?'] },
      { word: 'country', vi: 'đất nước', emoji: '🗺️', forms: ['countries'], examples: ['Vietnam is a beautiful country.', 'Japan is a country in Asia.'] },
      { word: 'city', vi: 'thành phố', emoji: '🏙️', forms: ['cities'], examples: ['Hanoi is a big city.', 'I live in a small city.'] },
      { word: 'live', vi: 'sống', emoji: '🏠', forms: ['lives', 'living'], examples: ['I live in Da Nang.', 'She lives in London.'] },
      { word: 'speak', vi: 'nói (ngôn ngữ)', emoji: '🗣️', forms: ['speaks'], examples: ['I speak Vietnamese.', 'He speaks English and French.'] },
      { word: 'Vietnamese', vi: 'người / tiếng Việt', emoji: '🇻🇳', examples: ["I'm Vietnamese.", 'Do you speak Vietnamese?'] },
      { word: 'English', vi: 'tiếng Anh / người Anh', emoji: '🇬🇧', examples: ['I speak a little English.', 'English is not easy.'] },
      { word: 'a little', vi: 'một chút', emoji: '🤏', examples: ['I speak a little English.', 'A little, not a lot.'] },
    ],
    story: {
      title: 'Kenji in Hanoi',
      sentences: [
        { en: 'Kenji is from Japan.', vi: 'Kenji đến từ Nhật Bản.' },
        { en: 'He is Japanese, but he lives in Vietnam.', vi: 'Anh ấy là người Nhật, nhưng sống ở Việt Nam.' },
        { en: 'He lives in Hanoi. Hanoi is a big city.', vi: 'Anh ấy sống ở Hà Nội. Hà Nội là một thành phố lớn.' },
        { en: 'Kenji speaks Japanese and English.', vi: 'Kenji nói tiếng Nhật và tiếng Anh.' },
        { en: 'He speaks a little Vietnamese.', vi: 'Anh ấy nói một chút tiếng Việt.' },
        { en: 'His friend Linh is Vietnamese.', vi: 'Bạn anh ấy, Linh, là người Việt.' },
        { en: 'Linh is from Hue, but she lives in Hanoi too.', vi: 'Linh đến từ Huế, nhưng cũng sống ở Hà Nội.' },
        { en: 'Linh speaks Vietnamese and English.', vi: 'Linh nói tiếng Việt và tiếng Anh.' },
        { en: 'Kenji and Linh speak English together.', vi: 'Kenji và Linh nói tiếng Anh với nhau.' },
        { en: 'English is their bridge.', vi: 'Tiếng Anh là cầu nối của họ.' },
      ],
      questions: [
        { q: 'Is Kenji from Japan?', vi: 'Kenji đến từ Nhật phải không?', answer: true },
        { q: 'Does Kenji live in Japan?', vi: 'Kenji sống ở Nhật phải không?', answer: false },
        { q: 'Is Linh from Hue?', vi: 'Linh đến từ Huế phải không?', answer: true },
        { q: 'Does Kenji speak a lot of Vietnamese?', vi: 'Kenji nói nhiều tiếng Việt phải không?', answer: false },
      ],
    },
    dialogue: {
      context: 'Nói chuyện với một du khách.',
      lines: [
        { speaker: 'Emma', text: 'Where are you from?', vi: 'Bạn đến từ đâu?' },
        { speaker: 'You', text: "I'm from Vietnam. And you?", vi: 'Tôi đến từ Việt Nam. Còn bạn?' },
        { speaker: 'Emma', text: "I'm from Australia. Where do you live?", vi: 'Tôi đến từ Úc. Bạn sống ở đâu?' },
        { speaker: 'You', text: 'I live in Ho Chi Minh City.', vi: 'Tôi sống ở TP Hồ Chí Minh.' },
        { speaker: 'Emma', text: 'Do you speak English?', vi: 'Bạn nói tiếng Anh không?' },
        { speaker: 'You', text: 'Yes, a little.', vi: 'Có, một chút.' },
      ],
    },
    speak: [
      { q: 'Where are you from?', vi: 'Bạn đến từ đâu?', model: "I'm from Vietnam.", modelVi: 'Tôi đến từ Việt Nam.' },
      { q: 'Where do you live?', vi: 'Bạn sống ở đâu?', model: 'I live in Hanoi.', modelVi: 'Tôi sống ở Hà Nội.' },
      { q: 'What languages do you speak?', vi: 'Bạn nói những ngôn ngữ nào?', model: 'I speak Vietnamese and a little English.', modelVi: 'Tôi nói tiếng Việt và một chút tiếng Anh.' },
      { q: 'Is your city big or small?', vi: 'Thành phố của bạn lớn hay nhỏ?', model: 'My city is big.', modelVi: 'Thành phố của tôi lớn.' },
    ],
    tip: 'Với he/she, động từ thêm "s": I live → she lives, I speak → he speaks.',
  },

  {
    day: 4, emoji: '👨‍👩‍👧', title: 'My Family', titleVi: 'Gia đình',
    goal: 'Giới thiệu các thành viên trong gia đình.',
    words: [
      { word: 'family', vi: 'gia đình', emoji: '👨‍👩‍👧', examples: ['I love my family.', 'My family is small.'] },
      { word: 'mother', vi: 'mẹ', emoji: '👩', forms: ['mom', 'mum'], examples: ['My mother is a nurse.', 'This is my mom.'] },
      { word: 'father', vi: 'bố', emoji: '👨', forms: ['dad'], examples: ['My father is fifty.', 'My dad likes coffee.'] },
      { word: 'brother', vi: 'anh / em trai', emoji: '👦', forms: ['brothers'], examples: ['I have one brother.', 'My brother is tall.'] },
      { word: 'sister', vi: 'chị / em gái', emoji: '👧', forms: ['sisters'], examples: ['My sister is a student.', 'I have two sisters.'] },
      { word: 'have', vi: 'có', emoji: '🤲', forms: ['has'], examples: ['I have a big family.', 'She has a cat.'] },
      { word: 'married', vi: 'đã kết hôn', emoji: '💍', examples: ['My sister is married.', 'Are you married?'] },
      { word: 'children', vi: 'con cái', emoji: '👶', forms: ['child', 'kids'], examples: ['They have two children.', 'I have no children.'] },
    ],
    story: {
      title: "Hoa's family",
      sentences: [
        { en: 'Hoa has a big family.', vi: 'Hoa có một gia đình lớn.' },
        { en: 'Her father is a teacher. Her mother is a doctor.', vi: 'Bố cô là giáo viên. Mẹ cô là bác sĩ.' },
        { en: 'Hoa has one brother and two sisters.', vi: 'Hoa có một anh trai và hai chị em gái.' },
        { en: 'Her brother is Duc. He is thirty.', vi: 'Anh trai cô là Đức. Anh ấy ba mươi tuổi.' },
        { en: 'Duc is married. He has two children.', vi: 'Đức đã kết hôn. Anh có hai con.' },
        { en: 'Her sisters are students.', vi: 'Hai em gái cô là sinh viên.' },
        { en: 'Hoa is not married. She has a cat.', vi: 'Hoa chưa kết hôn. Cô có một con mèo.' },
        { en: 'On Sunday, the family has dinner together.', vi: 'Chủ nhật, cả nhà ăn tối cùng nhau.' },
        { en: 'Hoa loves her family.', vi: 'Hoa yêu gia đình mình.' },
      ],
      questions: [
        { q: 'Is Hoa\'s father a teacher?', vi: 'Bố của Hoa là giáo viên phải không?', answer: true },
        { q: 'Does Hoa have two brothers?', vi: 'Hoa có hai anh em trai phải không?', answer: false },
        { q: 'Is Duc married?', vi: 'Đức đã kết hôn phải không?', answer: true },
        { q: 'Does Hoa have children?', vi: 'Hoa có con phải không?', answer: false },
      ],
    },
    dialogue: {
      context: 'Đồng nghiệp hỏi về gia đình bạn.',
      lines: [
        { speaker: 'Jack', text: 'Do you have a big family?', vi: 'Gia đình bạn có đông không?' },
        { speaker: 'You', text: 'Not really. I have one sister.', vi: 'Không lắm. Tôi có một chị gái.' },
        { speaker: 'Jack', text: 'Is she older or younger?', vi: 'Chị ấy lớn hơn hay nhỏ hơn?' },
        { speaker: 'You', text: "She's older. She's married and has a son.", vi: 'Chị lớn hơn. Chị đã kết hôn và có một con trai.' },
        { speaker: 'Jack', text: 'Nice! Do you live with your parents?', vi: 'Hay quá! Bạn sống với bố mẹ không?' },
        { speaker: 'You', text: 'Yes, I live with my mom and dad.', vi: 'Có, tôi sống với bố mẹ.' },
      ],
    },
    speak: [
      { q: 'Do you have a big family?', vi: 'Gia đình bạn có đông không?', model: 'Yes, I have a big family.', modelVi: 'Có, gia đình tôi đông.' },
      { q: 'Do you have brothers or sisters?', vi: 'Bạn có anh chị em không?', model: 'I have one brother and one sister.', modelVi: 'Tôi có một anh trai và một chị gái.' },
      { q: 'What does your mother do?', vi: 'Mẹ bạn làm nghề gì?', model: 'My mother is a teacher.', modelVi: 'Mẹ tôi là giáo viên.' },
      { q: 'Are you married?', vi: 'Bạn đã kết hôn chưa?', model: "No, I'm not married.", modelVi: 'Chưa, tôi chưa kết hôn.' },
    ],
    tip: 'I have → he/she has. "Hoa has a cat", không nói "Hoa have".',
  },

  {
    day: 5, emoji: '💼', title: 'Jobs', titleVi: 'Nghề nghiệp',
    goal: 'Nói mình làm nghề gì, làm ở đâu và hỏi nghề người khác.',
    words: [
      { word: 'job', vi: 'công việc', emoji: '💼', forms: ['jobs'], examples: ['I like my job.', 'What is your job?'] },
      { word: 'work', vi: 'làm việc', emoji: '🧑‍💻', forms: ['works', 'working'], examples: ['I work in an office.', 'She works at a hospital.'] },
      { word: 'teacher', vi: 'giáo viên', emoji: '👩‍🏫', examples: ['My mother is a teacher.', 'The teacher is kind.'] },
      { word: 'doctor', vi: 'bác sĩ', emoji: '👨‍⚕️', examples: ['He is a doctor.', 'The doctor works at night.'] },
      { word: 'student', vi: 'sinh viên, học sinh', emoji: '🎓', forms: ['students'], examples: ["I'm a student.", 'The students are in class.'] },
      { word: 'office', vi: 'văn phòng', emoji: '🏢', examples: ['I work in an office.', 'The office is on the 5th floor.'] },
      { word: 'engineer', vi: 'kỹ sư', emoji: '👷', forms: ['engineers'], examples: ["She's a software engineer.", 'He is an engineer.'] },
      { word: 'company', vi: 'công ty', emoji: '🏬', examples: ['I work for a big company.', 'Her company is in Hanoi.'] },
    ],
    story: {
      title: 'Three friends, three jobs',
      sentences: [
        { en: 'Lan, Huy and Sam are friends.', vi: 'Lan, Huy và Sam là bạn bè.' },
        { en: 'Lan is a teacher. She works at a school.', vi: 'Lan là giáo viên. Cô làm ở một trường học.' },
        { en: 'She likes her job. Her students are nice.', vi: 'Cô thích công việc. Học sinh của cô dễ thương.' },
        { en: 'Huy is an engineer. He works in an office.', vi: 'Huy là kỹ sư. Anh làm ở văn phòng.' },
        { en: 'His company is big. He works from nine to six.', vi: 'Công ty anh lớn. Anh làm từ 9 đến 6 giờ.' },
        { en: 'Sam is a doctor. He works at a hospital.', vi: 'Sam là bác sĩ. Anh làm ở bệnh viện.' },
        { en: 'Sam works at night. He is always tired.', vi: 'Sam làm đêm. Anh lúc nào cũng mệt.' },
        { en: 'Lan asks Sam, "Do you like your job?"', vi: 'Lan hỏi Sam: "Bạn có thích công việc không?"' },
        { en: 'Sam says, "Yes! But I want more sleep."', vi: 'Sam nói: "Có! Nhưng mình muốn ngủ nhiều hơn."' },
      ],
      questions: [
        { q: 'Is Lan a teacher?', vi: 'Lan là giáo viên phải không?', answer: true },
        { q: 'Does Huy work at a hospital?', vi: 'Huy làm ở bệnh viện phải không?', answer: false },
        { q: 'Does Sam work at night?', vi: 'Sam làm đêm phải không?', answer: true },
        { q: 'Does Sam like his job?', vi: 'Sam thích công việc phải không?', answer: true },
      ],
    },
    dialogue: {
      context: 'Hỏi về công việc khi mới quen.',
      lines: [
        { speaker: 'Mia', text: 'What do you do?', vi: 'Bạn làm nghề gì?' },
        { speaker: 'You', text: "I'm an accountant. And you?", vi: 'Tôi là kế toán. Còn bạn?' },
        { speaker: 'Mia', text: "I'm a nurse. Where do you work?", vi: 'Tôi là y tá. Bạn làm ở đâu?' },
        { speaker: 'You', text: 'I work for a bank in District 1.', vi: 'Tôi làm cho một ngân hàng ở Quận 1.' },
        { speaker: 'Mia', text: 'Do you like your job?', vi: 'Bạn thích công việc không?' },
        { speaker: 'You', text: "Yes, it's interesting.", vi: 'Có, nó thú vị.' },
      ],
    },
    speak: [
      { q: 'What do you do?', vi: 'Bạn làm nghề gì?', model: "I'm an office worker.", modelVi: 'Tôi là nhân viên văn phòng.' },
      { q: 'Where do you work?', vi: 'Bạn làm ở đâu?', model: 'I work for a small company in Hanoi.', modelVi: 'Tôi làm cho một công ty nhỏ ở Hà Nội.' },
      { q: 'Do you like your job?', vi: 'Bạn thích công việc không?', model: 'Yes, I like my job.', modelVi: 'Có, tôi thích công việc của mình.' },
      { q: 'What time do you start work?', vi: 'Mấy giờ bạn bắt đầu làm việc?', model: 'I start work at eight.', modelVi: 'Tôi bắt đầu làm lúc 8 giờ.' },
    ],
    tip: 'Trước nghề nghiệp luôn có "a/an": I\'m a teacher, I\'m an engineer ("an" khi từ sau bắt đầu bằng nguyên âm).',
  },
];
