import type { A1Day } from './types';

export const days11to15: A1Day[] = [
  {
    day: 11, emoji: '🏡', title: 'My Home', titleVi: 'Nhà của tôi',
    goal: 'Tả nhà, các phòng và đồ vật trong nhà.',
    words: [
      { word: 'house', vi: 'ngôi nhà', emoji: '🏠', examples: ['My house is small.', 'This is my house.'] },
      { word: 'apartment', vi: 'căn hộ', emoji: '🏢', forms: ['flat'], examples: ['I live in an apartment.', 'The apartment is on the 8th floor.'] },
      { word: 'room', vi: 'phòng', emoji: '🚪', forms: ['rooms'], examples: ['My house has four rooms.', 'This is my room.'] },
      { word: 'kitchen', vi: 'nhà bếp', emoji: '🍳', examples: ['The kitchen is small.', 'Mom is in the kitchen.'] },
      { word: 'bedroom', vi: 'phòng ngủ', emoji: '🛏️', forms: ['bedrooms'], examples: ['There are two bedrooms.', 'My bedroom is quiet.'] },
      { word: 'there is', vi: 'có (1 cái)', emoji: '☝️', forms: ['there are'], examples: ['There is a TV in the living room.', 'There are two chairs.'] },
      { word: 'table', vi: 'cái bàn', emoji: '🪑', forms: ['tables'], examples: ['The keys are on the table.', 'A big table.'] },
      { word: 'window', vi: 'cửa sổ', emoji: '🪟', forms: ['windows'], examples: ['Open the window, please.', 'My room has a big window.'] },
    ],
    story: {
      title: "Quang's new apartment",
      sentences: [
        { en: 'Quang has a new apartment.', vi: 'Quang có một căn hộ mới.' },
        { en: 'It is on the tenth floor.', vi: 'Nó ở tầng mười.' },
        { en: 'There are three rooms: a living room, a kitchen and a bedroom.', vi: 'Có ba phòng: phòng khách, bếp và phòng ngủ.' },
        { en: 'The kitchen is small, but it is clean.', vi: 'Bếp nhỏ nhưng sạch.' },
        { en: 'There is a big table in the living room.', vi: 'Có một cái bàn lớn ở phòng khách.' },
        { en: 'The bedroom has a big window.', vi: 'Phòng ngủ có cửa sổ lớn.' },
        { en: 'From the window, Quang can see the river.', vi: 'Từ cửa sổ, Quang có thể nhìn thấy dòng sông.' },
        { en: 'There is no TV. Quang reads books.', vi: 'Không có TV. Quang đọc sách.' },
        { en: 'He loves his new home.', vi: 'Anh rất thích ngôi nhà mới.' },
      ],
      questions: [
        { q: 'Is the apartment on the tenth floor?', vi: 'Căn hộ ở tầng 10 phải không?', answer: true },
        { q: 'Is the kitchen big?', vi: 'Bếp lớn phải không?', answer: false },
        { q: 'Is there a TV?', vi: 'Có TV phải không?', answer: false },
        { q: 'Can Quang see the river?', vi: 'Quang nhìn thấy sông phải không?', answer: true },
      ],
    },
    dialogue: {
      context: 'Bạn hỏi về chỗ ở của bạn.',
      lines: [
        { speaker: 'Nick', text: 'Do you live in a house or an apartment?', vi: 'Bạn sống ở nhà riêng hay căn hộ?' },
        { speaker: 'You', text: 'An apartment. It has two bedrooms.', vi: 'Căn hộ. Có hai phòng ngủ.' },
        { speaker: 'Nick', text: 'Is it big?', vi: 'Có rộng không?' },
        { speaker: 'You', text: "Not very big, but it's nice. There is a small balcony.", vi: 'Không rộng lắm, nhưng đẹp. Có một ban công nhỏ.' },
        { speaker: 'Nick', text: 'Who do you live with?', vi: 'Bạn sống với ai?' },
        { speaker: 'You', text: 'I live with my sister.', vi: 'Tôi sống với chị gái.' },
      ],
    },
    speak: [
      { q: 'Do you live in a house or an apartment?', vi: 'Bạn sống ở nhà hay căn hộ?', model: 'I live in a house.', modelVi: 'Tôi sống ở nhà riêng.' },
      { q: 'How many rooms are there?', vi: 'Có bao nhiêu phòng?', model: 'There are four rooms.', modelVi: 'Có bốn phòng.' },
      { q: 'What is in your bedroom?', vi: 'Trong phòng ngủ của bạn có gì?', model: 'There is a bed, a table and a window.', modelVi: 'Có một cái giường, một cái bàn và cửa sổ.' },
      { q: 'Who do you live with?', vi: 'Bạn sống với ai?', model: 'I live with my parents.', modelVi: 'Tôi sống với bố mẹ.' },
    ],
    tip: 'There is + 1 vật (there is a table). There are + nhiều vật (there are two chairs).',
  },

  {
    day: 12, emoji: '🏙️', title: 'In Town', titleVi: 'Địa điểm trong thành phố',
    goal: 'Hỏi và chỉ đường đơn giản tới các địa điểm.',
    words: [
      { word: 'where is', vi: '… ở đâu', emoji: '❓', examples: ['Where is the bank?', 'Excuse me, where is the station?'] },
      { word: 'bank', vi: 'ngân hàng', emoji: '🏦', examples: ['The bank is open.', 'Is there a bank near here?'] },
      { word: 'hospital', vi: 'bệnh viện', emoji: '🏥', examples: ['The hospital is big.', 'Where is the hospital?'] },
      { word: 'supermarket', vi: 'siêu thị', emoji: '🛒', examples: ['I buy food at the supermarket.', 'The supermarket is near my house.'] },
      { word: 'near', vi: 'gần', emoji: '📍', examples: ['The park is near here.', 'I live near the school.'] },
      { word: 'next to', vi: 'bên cạnh', emoji: '↔️', examples: ['The café is next to the bank.', 'Sit next to me.'] },
      { word: 'turn left', vi: 'rẽ trái', emoji: '⬅️', forms: ['left'], examples: ['Turn left here.', 'Turn left at the bank.'] },
      { word: 'go straight', vi: 'đi thẳng', emoji: '⬆️', forms: ['straight'], examples: ['Go straight for two minutes.', 'Go straight, then turn right.'] },
    ],
    story: {
      title: 'Lost in the city',
      sentences: [
        { en: 'Maria is new in the city.', vi: 'Maria mới đến thành phố.' },
        { en: 'She needs a supermarket.', vi: 'Cô cần một siêu thị.' },
        { en: 'She asks a man, "Excuse me, where is the supermarket?"', vi: 'Cô hỏi một người đàn ông: "Xin lỗi, siêu thị ở đâu?"' },
        { en: 'The man says, "Go straight. Then turn left at the bank."', vi: 'Ông nói: "Đi thẳng. Rồi rẽ trái ở ngân hàng."' },
        { en: '"The supermarket is next to the hospital."', vi: '"Siêu thị ở cạnh bệnh viện."' },
        { en: 'Maria goes straight. She turns left at the bank.', vi: 'Maria đi thẳng. Cô rẽ trái ở ngân hàng.' },
        { en: 'She sees the hospital. Next to it, there is the supermarket!', vi: 'Cô thấy bệnh viện. Bên cạnh là siêu thị!' },
        { en: 'It is near her house. Only five minutes.', vi: 'Nó gần nhà cô. Chỉ năm phút.' },
      ],
      questions: [
        { q: 'Is Maria new in the city?', vi: 'Maria mới đến thành phố phải không?', answer: true },
        { q: 'Does she turn right at the bank?', vi: 'Cô rẽ phải ở ngân hàng phải không?', answer: false },
        { q: 'Is the supermarket next to the hospital?', vi: 'Siêu thị ở cạnh bệnh viện phải không?', answer: true },
        { q: 'Is the supermarket far from her house?', vi: 'Siêu thị xa nhà cô phải không?', answer: false },
      ],
    },
    dialogue: {
      context: 'Hỏi đường tới ngân hàng.',
      lines: [
        { speaker: 'You', text: 'Excuse me, is there a bank near here?', vi: 'Xin lỗi, gần đây có ngân hàng không?' },
        { speaker: 'Woman', text: "Yes. Go straight and turn right. It's next to the park.", vi: 'Có. Đi thẳng rồi rẽ phải. Nó cạnh công viên.' },
        { speaker: 'You', text: 'Is it far?', vi: 'Có xa không?' },
        { speaker: 'Woman', text: 'No, about five minutes on foot.', vi: 'Không, đi bộ khoảng năm phút.' },
        { speaker: 'You', text: 'Thank you very much!', vi: 'Cảm ơn rất nhiều!' },
        { speaker: 'Woman', text: "You're welcome.", vi: 'Không có chi.' },
      ],
    },
    speak: [
      { q: 'Ask where the hospital is.', vi: 'Hỏi bệnh viện ở đâu.', model: 'Excuse me, where is the hospital?', modelVi: 'Xin lỗi, bệnh viện ở đâu?' },
      { q: 'Ask if there is a supermarket near here.', vi: 'Hỏi gần đây có siêu thị không.', model: 'Is there a supermarket near here?', modelVi: 'Gần đây có siêu thị không?' },
      { q: 'Tell someone to go straight and turn left.', vi: 'Chỉ đường: đi thẳng rồi rẽ trái.', model: 'Go straight and turn left.', modelVi: 'Đi thẳng rồi rẽ trái.' },
      { q: 'What is near your house?', vi: 'Gần nhà bạn có gì?', model: 'There is a park near my house.', modelVi: 'Gần nhà tôi có một công viên.' },
    ],
    tip: 'Mở đầu bằng "Excuse me" khi hỏi người lạ. Đáp lại cảm ơn: "You\'re welcome."',
  },

  {
    day: 13, emoji: '🚌', title: 'Getting Around', titleVi: 'Phương tiện đi lại',
    goal: 'Nói đi lại bằng gì, mất bao lâu, và mua vé.',
    words: [
      { word: 'by bus', vi: 'bằng xe buýt', emoji: '🚌', forms: ['bus'], examples: ['I go to work by bus.', 'The bus is late.'] },
      { word: 'motorbike', vi: 'xe máy', emoji: '🛵', examples: ['I ride a motorbike.', 'There are many motorbikes in Vietnam.'] },
      { word: 'taxi', vi: 'taxi', emoji: '🚕', examples: ["Let's take a taxi.", 'The taxi is here.'] },
      { word: 'train', vi: 'tàu hoả', emoji: '🚆', examples: ['The train to Hue is slow.', 'I like the train.'] },
      { word: 'on foot', vi: 'đi bộ', emoji: '🚶', forms: ['walk'], examples: ['I go to school on foot.', 'I walk to work.'] },
      { word: 'how long', vi: 'mất bao lâu', emoji: '⏳', examples: ['How long does it take?', 'How long is the trip?'] },
      { word: 'take', vi: 'mất (thời gian); đi (phương tiện)', emoji: '⏱️', forms: ['takes'], examples: ['It takes twenty minutes.', 'I take the bus.'] },
      { word: 'ticket', vi: 'vé', emoji: '🎫', forms: ['tickets'], examples: ['One ticket to Da Nang, please.', 'How much is a ticket?'] },
    ],
    story: {
      title: 'Three ways to work',
      sentences: [
        { en: 'Nga, Phong and Kim work in the same office.', vi: 'Nga, Phong và Kim làm cùng văn phòng.' },
        { en: 'Nga goes to work by motorbike. It takes fifteen minutes.', vi: 'Nga đi làm bằng xe máy. Mất mười lăm phút.' },
        { en: 'Phong goes by bus. It takes forty minutes.', vi: 'Phong đi xe buýt. Mất bốn mươi phút.' },
        { en: 'On the bus, Phong reads and listens to English.', vi: 'Trên xe buýt, Phong đọc và nghe tiếng Anh.' },
        { en: 'Kim lives near the office. She goes on foot.', vi: 'Kim sống gần văn phòng. Cô đi bộ.' },
        { en: 'It takes only five minutes.', vi: 'Chỉ mất năm phút.' },
        { en: 'One day, it rains a lot.', vi: 'Một hôm, trời mưa to.' },
        { en: 'Nga takes a taxi. Phong is late. Kim is wet!', vi: 'Nga đi taxi. Phong bị trễ. Kim bị ướt!' },
        { en: 'Next month, Phong wants to visit Hue by train.', vi: 'Tháng sau, Phong muốn đi Huế bằng tàu hoả.' },
        { en: 'He buys a ticket. He asks, "How long does it take?"', vi: 'Anh mua vé. Anh hỏi: "Đi mất bao lâu?"' },
        { en: '"Twelve hours." Phong laughs. "Longer than the bus to work!"', vi: '"Mười hai tiếng." Phong cười. "Còn lâu hơn đi xe buýt tới chỗ làm!"' },
      ],
      questions: [
        { q: 'Does Nga go to work by motorbike?', vi: 'Nga đi làm bằng xe máy phải không?', answer: true },
        { q: 'Does the bus take fifteen minutes?', vi: 'Xe buýt mất 15 phút phải không?', answer: false },
        { q: 'Does Kim live near the office?', vi: 'Kim sống gần văn phòng phải không?', answer: true },
        { q: 'Does Kim take a taxi in the rain?', vi: 'Kim đi taxi khi trời mưa phải không?', answer: false },
      ],
    },
    dialogue: {
      context: 'Mua vé tàu.',
      lines: [
        { speaker: 'You', text: 'One ticket to Da Nang, please.', vi: 'Cho một vé đi Đà Nẵng.' },
        { speaker: 'Clerk', text: 'One way or return?', vi: 'Một chiều hay khứ hồi?' },
        { speaker: 'You', text: 'One way. How much is it?', vi: 'Một chiều. Bao nhiêu tiền?' },
        { speaker: 'Clerk', text: 'Twenty dollars. The train leaves at nine.', vi: 'Hai mươi đô. Tàu chạy lúc 9 giờ.' },
        { speaker: 'You', text: 'How long does it take?', vi: 'Đi mất bao lâu?' },
        { speaker: 'Clerk', text: 'About six hours.', vi: 'Khoảng sáu tiếng.' },
      ],
    },
    speak: [
      { q: 'How do you go to work?', vi: 'Bạn đi làm bằng gì?', model: 'I go to work by motorbike.', modelVi: 'Tôi đi làm bằng xe máy.' },
      { q: 'How long does it take?', vi: 'Mất bao lâu?', model: 'It takes about twenty minutes.', modelVi: 'Mất khoảng hai mươi phút.' },
      { q: 'Buy a bus ticket.', vi: 'Mua vé xe buýt.', model: 'One ticket, please.', modelVi: 'Cho một vé.' },
      { q: 'Suggest taking a taxi.', vi: 'Rủ đi taxi.', model: "Let's take a taxi.", modelVi: 'Mình đi taxi đi.' },
    ],
    tip: '"by" + phương tiện (by bus, by train), nhưng "on foot" khi đi bộ.',
  },

  {
    day: 14, emoji: '🌦️', title: 'Weather', titleVi: 'Thời tiết và mùa',
    goal: 'Nói chuyện về thời tiết hôm nay và các mùa.',
    words: [
      { word: 'weather', vi: 'thời tiết', emoji: '🌤️', examples: ["How's the weather today?", 'The weather is nice.'] },
      { word: 'hot', vi: 'nóng', emoji: '🥵', examples: ["It's very hot today.", 'Summer is hot.'] },
      { word: 'cold', vi: 'lạnh', emoji: '🥶', examples: ["It's cold in Hanoi in winter.", 'I am cold.'] },
      { word: 'rain', vi: 'mưa', emoji: '🌧️', forms: ['raining', 'rains', 'rainy'], examples: ["It's raining.", 'It rains a lot in July.'] },
      { word: 'sunny', vi: 'nắng', emoji: '☀️', forms: ['sun'], examples: ["It's sunny today.", 'A sunny day.'] },
      { word: 'umbrella', vi: 'cái ô', emoji: '☂️', examples: ['Take an umbrella!', 'I have no umbrella.'] },
      { word: 'summer', vi: 'mùa hè', emoji: '🏖️', examples: ['I love summer.', 'Summer is hot.'] },
      { word: 'winter', vi: 'mùa đông', emoji: '❄️', examples: ['Winter in Hanoi is cold.', 'I don\'t like winter.'] },
    ],
    story: {
      title: 'Two cities, two kinds of weather',
      sentences: [
        { en: 'Trang lives in Saigon. Her sister Ha lives in Hanoi.', vi: 'Trang sống ở Sài Gòn. Em gái Hà sống ở Hà Nội.' },
        { en: 'In Saigon, it is hot all year.', vi: 'Ở Sài Gòn, trời nóng quanh năm.' },
        { en: 'There is no winter in Saigon.', vi: 'Sài Gòn không có mùa đông.' },
        { en: 'But it rains a lot in summer.', vi: 'Nhưng mùa hè mưa nhiều.' },
        { en: 'Trang always has an umbrella in her bag.', vi: 'Trang luôn có cái ô trong túi.' },
        { en: 'In Hanoi, the summer is hot, and the winter is cold.', vi: 'Ở Hà Nội, mùa hè nóng và mùa đông lạnh.' },
        { en: 'Today Ha calls Trang. "It is cold here! Ten degrees!"', vi: 'Hôm nay Hà gọi Trang. "Ở đây lạnh! Mười độ!"' },
        { en: 'Trang laughs. "Here it is sunny and thirty-two degrees!"', vi: 'Trang cười. "Ở đây nắng và 32 độ!"' },
      ],
      questions: [
        { q: 'Is it hot all year in Saigon?', vi: 'Sài Gòn nóng quanh năm phải không?', answer: true },
        { q: 'Is there a winter in Saigon?', vi: 'Sài Gòn có mùa đông phải không?', answer: false },
        { q: 'Is it cold in Hanoi today?', vi: 'Hôm nay Hà Nội lạnh phải không?', answer: true },
        { q: 'Is it raining in Saigon today?', vi: 'Hôm nay Sài Gòn mưa phải không?', answer: false },
      ],
    },
    dialogue: {
      context: 'Nói chuyện thời tiết với đồng nghiệp.',
      lines: [
        { speaker: 'Amy', text: "It's so hot today!", vi: 'Hôm nay nóng quá!' },
        { speaker: 'You', text: 'Yes, it is. Is it hot in your country?', vi: 'Ừ đúng vậy. Ở nước bạn có nóng không?' },
        { speaker: 'Amy', text: "No, it's cold in England. It rains a lot.", vi: 'Không, ở Anh lạnh. Mưa nhiều.' },
        { speaker: 'You', text: 'Do you like the weather here?', vi: 'Bạn thích thời tiết ở đây không?' },
        { speaker: 'Amy', text: 'I love the sun, but not the rain!', vi: 'Mình thích nắng, nhưng không thích mưa!' },
        { speaker: 'You', text: 'Me too. Take an umbrella this afternoon.', vi: 'Mình cũng vậy. Chiều nay mang ô nhé.' },
      ],
    },
    speak: [
      { q: "How's the weather today?", vi: 'Hôm nay thời tiết thế nào?', model: "It's sunny and hot.", modelVi: 'Trời nắng và nóng.' },
      { q: 'Do you like hot or cold weather?', vi: 'Bạn thích trời nóng hay lạnh?', model: 'I like cold weather.', modelVi: 'Tôi thích trời lạnh.' },
      { q: 'What is your favorite season?', vi: 'Bạn thích mùa nào nhất?', model: 'My favorite season is autumn.', modelVi: 'Tôi thích mùa thu nhất.' },
      { q: 'Tell a friend to take an umbrella.', vi: 'Nhắc bạn mang ô.', model: "Take an umbrella. It's going to rain.", modelVi: 'Mang ô đi. Trời sắp mưa.' },
    ],
    tip: 'Nói thời tiết luôn bắt đầu bằng "It\'s…": It\'s hot, It\'s raining, It\'s sunny.',
  },

  {
    day: 15, emoji: '🗓️', title: 'Days & Plans', titleVi: 'Ngày trong tuần và hẹn gặp',
    goal: 'Nói các ngày trong tuần, hỏi rảnh không và hẹn gặp.',
    words: [
      { word: 'Monday', vi: 'thứ Hai', emoji: '1️⃣', examples: ['I work on Monday.', 'See you on Monday!'] },
      { word: 'weekend', vi: 'cuối tuần', emoji: '🎈', examples: ['What do you do on the weekend?', 'I love weekends.'] },
      { word: 'free', vi: 'rảnh', emoji: '🆓', examples: ['Are you free on Saturday?', "I'm free tonight."] },
      { word: 'busy', vi: 'bận', emoji: '📚', examples: ["Sorry, I'm busy.", 'Monday is a busy day.'] },
      { word: "let's", vi: 'cùng … nhé', emoji: '🤝', examples: ["Let's go to the cinema.", "Let's meet at seven."] },
      { word: 'meet', vi: 'gặp', emoji: '🙌', forms: ['meets'], examples: ["Let's meet at the café.", 'Nice to meet you.'] },
      { word: 'tomorrow', vi: 'ngày mai', emoji: '➡️', examples: ['See you tomorrow!', 'Are you free tomorrow?'] },
      { word: 'tonight', vi: 'tối nay', emoji: '🌙', examples: ['What are you doing tonight?', "Let's eat out tonight."] },
    ],
    story: {
      title: 'When are you free?',
      sentences: [
        { en: 'Dung wants to see a movie with Linh.', vi: 'Dũng muốn đi xem phim với Linh.' },
        { en: 'He asks, "Are you free tonight?"', vi: 'Anh hỏi: "Tối nay bạn rảnh không?"' },
        { en: 'Linh says, "Sorry, I am busy tonight. I have English class."', vi: 'Linh nói: "Xin lỗi, tối nay mình bận. Mình có lớp tiếng Anh."' },
        { en: 'Dung asks, "What about tomorrow?"', vi: 'Dũng hỏi: "Còn ngày mai thì sao?"' },
        { en: 'Linh says, "Tomorrow is Friday. I work late on Friday."', vi: 'Linh nói: "Mai là thứ Sáu. Thứ Sáu mình làm muộn."' },
        { en: '"Are you free on the weekend?"', vi: '"Cuối tuần bạn rảnh không?"' },
        { en: 'Linh smiles. "Yes! I am free on Saturday."', vi: 'Linh cười. "Có! Thứ Bảy mình rảnh."' },
        { en: 'Dung says, "Great! Let\'s meet at seven on Saturday."', vi: 'Dũng nói: "Tuyệt! Mình gặp nhau lúc 7 giờ thứ Bảy nhé."' },
      ],
      questions: [
        { q: 'Is Linh free tonight?', vi: 'Tối nay Linh rảnh phải không?', answer: false },
        { q: 'Does Linh have English class tonight?', vi: 'Tối nay Linh có lớp tiếng Anh phải không?', answer: true },
        { q: 'Is tomorrow Friday?', vi: 'Ngày mai là thứ Sáu phải không?', answer: true },
        { q: 'Do they meet on Sunday?', vi: 'Họ gặp nhau vào Chủ nhật phải không?', answer: false },
      ],
    },
    dialogue: {
      context: 'Hẹn bạn đi ăn.',
      lines: [
        { speaker: 'Sam', text: 'Are you free on Sunday?', vi: 'Chủ nhật bạn rảnh không?' },
        { speaker: 'You', text: 'Yes, I am. Why?', vi: 'Có. Sao thế?' },
        { speaker: 'Sam', text: "Let's have lunch together.", vi: 'Đi ăn trưa cùng nhau nhé.' },
        { speaker: 'You', text: 'Good idea! What time?', vi: 'Ý hay! Mấy giờ?' },
        { speaker: 'Sam', text: 'At twelve. Is that OK?', vi: 'Lúc 12 giờ. Được không?' },
        { speaker: 'You', text: 'Perfect. See you on Sunday!', vi: 'Hoàn hảo. Hẹn gặp Chủ nhật!' },
      ],
    },
    speak: [
      { q: 'What day is it today?', vi: 'Hôm nay thứ mấy?', model: "It's Monday.", modelVi: 'Hôm nay thứ Hai.' },
      { q: 'Are you free tonight?', vi: 'Tối nay bạn rảnh không?', model: "Sorry, I'm busy tonight.", modelVi: 'Xin lỗi, tối nay tôi bận.' },
      { q: 'Invite a friend to the cinema.', vi: 'Rủ bạn đi xem phim.', model: "Let's go to the cinema on Saturday.", modelVi: 'Thứ Bảy đi xem phim nhé.' },
      { q: 'What do you do on the weekend?', vi: 'Cuối tuần bạn làm gì?', model: 'I meet my friends and I rest.', modelVi: 'Tôi gặp bạn bè và nghỉ ngơi.' },
    ],
    tip: 'Ngày trong tuần dùng "on": on Monday, on Saturday. Nhưng "tonight", "tomorrow" không cần giới từ.',
  },
];
