import type { FastTalkUnit } from './types';

export const unitsB1: FastTalkUnit[] = [
  {
    id: 11, level: 'B1', track: 'work', emoji: '💬',
    title: 'Sharing Your Opinion in a Meeting', titleVi: 'Nêu ý kiến trong cuộc họp',
    situation: 'Team đang bàn có nên ra mắt tính năng mới tuần sau không.',
    dialogue: [
      { speaker: 'Manager', text: "So, should we launch next week or wait? What do you think?", vi: 'Vậy ta nên ra mắt tuần sau hay đợi? Bạn nghĩ sao?' },
      { speaker: 'You', text: "If you ask me, we should wait a bit. There are still a few bugs.", vi: 'Theo mình thì nên đợi thêm chút. Vẫn còn vài lỗi.' },
      { speaker: 'Tom', text: "I see your point, but the client is expecting it soon.", vi: 'Mình hiểu ý bạn, nhưng khách hàng đang chờ sớm.' },
      { speaker: 'You', text: "That's true. Maybe we could launch a smaller version first?", vi: 'Đúng vậy. Hay là ra mắt bản nhỏ hơn trước?' },
      { speaker: 'Manager', text: "Interesting. How would that work?", vi: 'Hay đấy. Cụ thể thì thế nào?' },
      { speaker: 'You', text: "We'd release the main features and fix the rest the week after.", vi: 'Ta ra các tính năng chính, phần còn lại sửa vào tuần sau.' },
      { speaker: 'Tom', text: "Actually, I think that could work.", vi: 'Thật ra mình nghĩ cách đó được.' },
    ],
    questions: [
      { q: 'Why does the speaker want to wait?', options: ['The team is tired', 'There are still bugs', 'The client said so'], answer: 1 },
      { q: 'What compromise do they suggest?', options: ['Cancel the launch', 'Launch a smaller version first', 'Hire more people'], answer: 1 },
    ],
    connectedSpeech: [
      { written: 'What do you think?', spoken: '/ˈwʌ-də-jə-ˈθɪŋk/', note: '"What do you" rút thành "whad-da-ya" — gần như một từ.' },
      { written: 'I see your point', spoken: '/aɪ-ˈsi-jər-ˈpɔɪnt/', note: '"your" đọc nhẹ thành "yer"; nhấn vào "point".' },
    ],
    chunks: [
      { en: 'If you ask me, …', vi: 'Theo mình thì…', example: 'If you ask me, the price is too high.', exampleVi: 'Theo mình thì giá quá cao.' },
      { en: 'I see your point, but…', vi: 'Mình hiểu ý bạn, nhưng…', example: "I see your point, but we don't have time.", exampleVi: 'Mình hiểu ý bạn, nhưng ta không có thời gian.' },
      { en: "That's true.", vi: 'Đúng vậy.', example: "That's true, but it's still risky.", exampleVi: 'Đúng vậy, nhưng vẫn rủi ro.' },
      { en: 'Maybe we could…?', vi: 'Hay là ta…?', example: 'Maybe we could ask the client first?', exampleVi: 'Hay là ta hỏi khách hàng trước?' },
      { en: 'How would that work?', vi: 'Cụ thể thì thế nào?', example: 'A four-day week? How would that work?', exampleVi: 'Làm bốn ngày một tuần? Cụ thể thế nào?' },
      { en: 'I think that could work.', vi: 'Mình nghĩ cách đó được.', example: 'Splitting the task? I think that could work.', exampleVi: 'Chia nhỏ việc ra à? Mình nghĩ được đấy.' },
      { en: "I'm not sure about that.", vi: 'Mình không chắc lắm.', example: "Hmm, I'm not sure about that idea.", exampleVi: 'Hmm, mình không chắc lắm về ý đó.' },
      { en: 'The main reason is…', vi: 'Lý do chính là…', example: 'The main reason is that we lack data.', exampleVi: 'Lý do chính là ta thiếu dữ liệu.' },
    ],
    drills: [
      { vi: 'Theo mình thì ta nên đợi.', en: 'If you ask me, we should wait.' },
      { vi: 'Mình hiểu ý bạn, nhưng nó quá đắt.', en: "I see your point, but it's too expensive." },
      { vi: 'Hay là ta thử cách khác?', en: 'Maybe we could try another way?', accept: ['Maybe we could try a different approach?'] },
      { vi: 'Cụ thể thì thế nào?', en: 'How would that work?' },
      { vi: 'Mình không chắc lắm về điều đó.', en: "I'm not sure about that." },
      { vi: 'Lý do chính là ta không có đủ thời gian.', en: "The main reason is that we don't have enough time." },
    ],
    pattern: {
      frame: "I see your point, but ___.", meaning: 'Mình hiểu ý bạn, nhưng ___.',
      slots: [
        { vi: 'Mình hiểu ý bạn, nhưng khách hàng sẽ không đồng ý.', en: "I see your point, but the client won't agree." },
        { vi: 'Mình hiểu ý bạn, nhưng ta cần thêm dữ liệu.', en: 'I see your point, but we need more data.' },
        { vi: 'Mình hiểu ý bạn, nhưng như vậy rủi ro quá.', en: "I see your point, but that's too risky." },
        { vi: 'Mình hiểu ý bạn, nhưng ngân sách có hạn.', en: 'I see your point, but the budget is limited.' },
      ],
    },
    roleplay: {
      scenario: 'Sếp hỏi ý kiến bạn về việc chuyển sang làm từ xa.',
      lines: [
        { speaker: 'them', text: 'Should we let everyone work from home on Fridays? What do you think?', vi: 'Có nên cho mọi người làm ở nhà vào thứ Sáu không? Bạn nghĩ sao?' },
        { speaker: 'you', text: 'If you ask me, it is a great idea.', vi: 'Theo mình thì đó là ý hay.' },
        { speaker: 'them', text: "But some people won't be as productive.", vi: 'Nhưng vài người sẽ làm kém hiệu quả hơn.' },
        { speaker: 'you', text: 'I see your point, but maybe we could try it for a month?', vi: 'Mình hiểu ý bạn, nhưng hay là thử một tháng?' },
        { speaker: 'them', text: 'Hmm, a trial. How would that work?', vi: 'Hmm, thử nghiệm à. Cụ thể thế nào?' },
        { speaker: 'you', text: 'We would track results and decide after that.', vi: 'Ta theo dõi kết quả rồi quyết định sau.' },
      ],
    },
  },

  {
    id: 12, level: 'B1', track: 'life', emoji: '🙅',
    title: 'Saying No Politely', titleVi: 'Từ chối khéo léo',
    situation: 'Một người bạn rủ đi chơi nhưng bạn bận, và đồng nghiệp nhờ việc khi bạn quá tải.',
    dialogue: [
      { speaker: 'Sam', text: "We're going to a karaoke bar tonight. You should come!", vi: 'Tối nay bọn mình đi karaoke. Đi cùng đi!' },
      { speaker: 'You', text: "Thanks for asking, but I can't make it tonight. I've got an early start tomorrow.", vi: 'Cảm ơn đã rủ, nhưng tối nay mình không đi được. Mai mình phải dậy sớm.' },
      { speaker: 'Sam', text: "Aw, come on! Just for an hour?", vi: 'Ôi thôi mà! Một tiếng thôi?' },
      { speaker: 'You', text: "I'd love to, but I really need to rest. Maybe next time?", vi: 'Mình rất muốn, nhưng thật sự cần nghỉ. Để lần sau nhé?' },
      { speaker: 'Sam', text: "Okay, fair enough. Next time for sure.", vi: 'Ok, cũng phải. Lần sau nhất định nhé.' },
      { speaker: 'You', text: "Definitely. Have fun tonight!", vi: 'Chắc chắn rồi. Tối nay chơi vui nhé!' },
    ],
    questions: [
      { q: "Why can't the speaker go?", options: ['They are sick', 'They have to get up early', "They don't like karaoke"], answer: 1 },
      { q: 'How does Sam react in the end?', options: ['Gets angry', 'Accepts it', 'Cancels the plan'], answer: 1 },
    ],
    connectedSpeech: [
      { written: "I can't make it", spoken: '/aɪ-ˈkæn-ˈmeɪ-kɪt/', note: '"can\'t" gần như mất chữ t cuối: "can\'". Phân biệt "can" bằng nguyên âm dài và nhấn mạnh hơn.' },
      { written: "I'd love to", spoken: '/aɪd-ˈlʌv-tə/', note: '"to" đọc nhẹ, câu dừng ở "to" — không lặp lại động từ.' },
    ],
    chunks: [
      { en: 'Thanks for asking, but…', vi: 'Cảm ơn đã rủ/hỏi, nhưng…', example: "Thanks for asking, but I'm busy that day.", exampleVi: 'Cảm ơn đã rủ, nhưng hôm đó mình bận.' },
      { en: "I can't make it.", vi: 'Mình không đến được.', example: "Sorry, I can't make it to the party.", exampleVi: 'Xin lỗi, mình không đến bữa tiệc được.' },
      { en: "I've got an early start.", vi: 'Mình phải dậy sớm.', example: "I'll head home. I've got an early start.", exampleVi: 'Mình về đây. Mai phải dậy sớm.' },
      { en: "I'd love to, but…", vi: 'Mình rất muốn, nhưng…', example: "I'd love to, but I already have plans.", exampleVi: 'Mình rất muốn, nhưng mình có hẹn rồi.' },
      { en: 'Maybe next time?', vi: 'Để lần sau nhé?', example: "Not this week. Maybe next time?", exampleVi: 'Tuần này không được. Để lần sau nhé?' },
      { en: "I'm afraid I can't…", vi: 'E là mình không thể…', example: "I'm afraid I can't take on more work right now.", exampleVi: 'E là giờ mình không nhận thêm việc được.' },
      { en: "I've got a lot on my plate.", vi: 'Mình đang ngập việc.', example: "Sorry, I've got a lot on my plate this week.", exampleVi: 'Xin lỗi, tuần này mình ngập việc.' },
      { en: 'Fair enough.', vi: 'Cũng phải / Hợp lý.', example: "You're tired? Fair enough.", exampleVi: 'Bạn mệt à? Cũng phải.' },
    ],
    drills: [
      { vi: 'Cảm ơn đã rủ, nhưng tối nay mình không đi được.', en: "Thanks for asking, but I can't make it tonight." },
      { vi: 'Mình rất muốn, nhưng mình có hẹn rồi.', en: "I'd love to, but I already have plans." },
      { vi: 'Để lần sau nhé?', en: 'Maybe next time?' },
      { vi: 'Tuần này mình đang ngập việc.', en: "I've got a lot on my plate this week." },
      { vi: 'E là giờ mình không giúp được.', en: "I'm afraid I can't help right now." },
      { vi: 'Mai mình phải dậy sớm.', en: "I've got an early start tomorrow." },
    ],
    pattern: {
      frame: "I'd love to, but ___.", meaning: 'Mình rất muốn, nhưng ___.',
      slots: [
        { vi: 'Mình rất muốn, nhưng mình phải làm thêm giờ.', en: "I'd love to, but I have to work late." },
        { vi: 'Mình rất muốn, nhưng mình đang ăn kiêng.', en: "I'd love to, but I'm on a diet." },
        { vi: 'Mình rất muốn, nhưng mình hết tiền rồi.', en: "I'd love to, but I'm out of money.", accept: ["I'd love to, but I'm broke."] },
        { vi: 'Mình rất muốn, nhưng mình không khoẻ.', en: "I'd love to, but I'm not feeling well." },
      ],
    },
    roleplay: {
      scenario: 'Đồng nghiệp nhờ bạn làm thêm một dự án khi bạn đã quá tải.',
      lines: [
        { speaker: 'them', text: 'Hey, could you help me with the marketing report this week?', vi: 'Này, tuần này bạn giúp mình báo cáo marketing được không?' },
        { speaker: 'you', text: "I'd love to, but I've got a lot on my plate this week.", vi: 'Mình rất muốn, nhưng tuần này mình ngập việc.' },
        { speaker: 'them', text: "Oh, I see. It's only a small part.", vi: 'À, hiểu rồi. Chỉ một phần nhỏ thôi mà.' },
        { speaker: 'you', text: "I'm afraid I can't right now. Maybe next week?", vi: 'E là giờ mình không được. Tuần sau nhé?' },
        { speaker: 'them', text: 'Fair enough. I will ask someone else.', vi: 'Cũng phải. Mình sẽ hỏi người khác.' },
      ],
    },
  },

  {
    id: 13, level: 'B1', track: 'life', emoji: '🏨',
    title: 'Complaining Politely', titleVi: 'Phàn nàn lịch sự',
    situation: 'Phòng khách sạn có vấn đề và bạn gọi lễ tân.',
    dialogue: [
      { speaker: 'Reception', text: "Front desk, how can I help?", vi: 'Lễ tân xin nghe, tôi giúp gì được?' },
      { speaker: 'You', text: "Hi, I'm calling from room 508. I'm afraid there's a problem with the air conditioning.", vi: 'Chào, tôi gọi từ phòng 508. E là máy lạnh có vấn đề.' },
      { speaker: 'Reception', text: "I'm sorry to hear that. What seems to be the problem?", vi: 'Rất tiếc. Vấn đề cụ thể là gì ạ?' },
      { speaker: 'You', text: "It's not working at all, and it's really hot in here.", vi: 'Nó không chạy chút nào, và trong phòng rất nóng.' },
      { speaker: 'Reception', text: "I'll send someone up to take a look right away.", vi: 'Tôi sẽ cho người lên xem ngay.' },
      { speaker: 'You', text: "Thanks. If it can't be fixed, would it be possible to change rooms?", vi: 'Cảm ơn. Nếu không sửa được, có thể đổi phòng không?' },
      { speaker: 'Reception', text: "Absolutely. We'll sort it out for you.", vi: 'Hoàn toàn được. Chúng tôi sẽ xử lý cho bạn.' },
    ],
    questions: [
      { q: 'What is the problem?', options: ['The TV is broken', 'The air conditioning is not working', 'The room is noisy'], answer: 1 },
      { q: 'What does the guest ask for if it cannot be fixed?', options: ['A refund', 'A different room', 'A free dinner'], answer: 1 },
    ],
    connectedSpeech: [
      { written: "I'm afraid there's a problem", spoken: '/aɪm-ə-ˈfreɪd-ðer-zə-ˈprɑ-bləm/', note: '"there\'s a" nối thành "ther-zə".' },
      { written: 'sort it out', spoken: '/ˈsɔr-dɪ-ˈdaʊt/', note: 'Ba từ nối thành một: "sor-di-dout" (giọng Mỹ).' },
    ],
    chunks: [
      { en: "I'm afraid there's a problem with…", vi: 'E là … có vấn đề.', example: "I'm afraid there's a problem with my bill.", exampleVi: 'E là hoá đơn của tôi có vấn đề.' },
      { en: "It's not working at all.", vi: 'Nó hoàn toàn không chạy.', example: "The Wi-Fi isn't working at all.", exampleVi: 'Wi-Fi hoàn toàn không vào được.' },
      { en: 'What seems to be the problem?', vi: 'Vấn đề có vẻ là gì?', example: 'Hello, what seems to be the problem?', exampleVi: 'Xin chào, có vấn đề gì vậy?' },
      { en: 'Would it be possible to…?', vi: 'Có thể … được không?', example: 'Would it be possible to get a late checkout?', exampleVi: 'Có thể trả phòng muộn được không?' },
      { en: 'This is not what I ordered.', vi: 'Đây không phải món tôi gọi.', example: "Excuse me, this is not what I ordered.", exampleVi: 'Xin lỗi, đây không phải món tôi gọi.' },
      { en: 'sort it out', vi: 'giải quyết, xử lý', example: "Don't worry, we'll sort it out.", exampleVi: 'Đừng lo, chúng tôi sẽ xử lý.' },
      { en: "I'd appreciate it if…", vi: 'Tôi sẽ rất cảm kích nếu…', example: "I'd appreciate it if you could check again.", exampleVi: 'Tôi sẽ rất cảm kích nếu bạn kiểm tra lại.' },
      { en: "It's been … and still…", vi: 'Đã … rồi mà vẫn…', example: "It's been forty minutes and still no food.", exampleVi: 'Đã bốn mươi phút rồi mà vẫn chưa có đồ ăn.' },
    ],
    drills: [
      { vi: 'E là Wi-Fi có vấn đề.', en: "I'm afraid there's a problem with the Wi-Fi." },
      { vi: 'Nó hoàn toàn không chạy.', en: "It's not working at all." },
      { vi: 'Có thể đổi phòng được không?', en: 'Would it be possible to change rooms?' },
      { vi: 'Xin lỗi, đây không phải món tôi gọi.', en: 'Excuse me, this is not what I ordered.', accept: ["Excuse me, this isn't what I ordered."] },
      { vi: 'Đã ba mươi phút rồi mà vẫn chưa có đồ ăn.', en: "It's been thirty minutes and still no food." },
      { vi: 'Tôi sẽ rất cảm kích nếu bạn kiểm tra lại.', en: "I'd appreciate it if you could check again." },
    ],
    pattern: {
      frame: 'Would it be possible to ___?', meaning: 'Có thể ___ được không?',
      slots: [
        { vi: 'Có thể trả phòng muộn được không?', en: 'Would it be possible to check out late?', accept: ['Would it be possible to get a late checkout?'] },
        { vi: 'Có thể đổi bàn được không?', en: 'Would it be possible to change tables?' },
        { vi: 'Có thể được giảm giá không?', en: 'Would it be possible to get a discount?' },
        { vi: 'Có thể nói chuyện với quản lý không?', en: 'Would it be possible to speak to the manager?' },
      ],
    },
    roleplay: {
      scenario: 'Nhà hàng mang sai món và bạn đã đợi lâu.',
      lines: [
        { speaker: 'them', text: 'Here you go, the beef noodles.', vi: 'Đây ạ, phở bò.' },
        { speaker: 'you', text: "Excuse me, I'm afraid this is not what I ordered.", vi: 'Xin lỗi, e là đây không phải món tôi gọi.' },
        { speaker: 'them', text: "Oh, I'm so sorry. What did you order?", vi: 'Ôi, xin lỗi. Bạn đã gọi món gì?' },
        { speaker: 'you', text: "The chicken rice. And it's been forty minutes already.", vi: 'Cơm gà. Và đã bốn mươi phút rồi.' },
        { speaker: 'them', text: "I'm really sorry. I'll sort it out right away.", vi: 'Thật sự xin lỗi. Tôi sẽ xử lý ngay.' },
        { speaker: 'you', text: "Thanks, I'd appreciate it.", vi: 'Cảm ơn, tôi rất cảm kích.' },
      ],
    },
  },

  {
    id: 14, level: 'B1', track: 'work', emoji: '🔧',
    title: 'Explaining a Problem', titleVi: 'Giải thích một vấn đề',
    situation: 'Hệ thống bị lỗi và bạn giải thích cho quản lý chuyện gì đã xảy ra.',
    dialogue: [
      { speaker: 'Manager', text: "I heard the app went down this morning. What happened?", vi: 'Nghe nói sáng nay app bị sập. Chuyện gì vậy?' },
      { speaker: 'You', text: "Basically, the server ran out of memory during the update.", vi: 'Tóm lại là server bị hết bộ nhớ trong lúc cập nhật.' },
      { speaker: 'Manager', text: "How did that happen?", vi: 'Sao lại thế?' },
      { speaker: 'You', text: "It turns out a new feature was loading too much data at once.", vi: 'Hoá ra một tính năng mới tải quá nhiều dữ liệu cùng lúc.' },
      { speaker: 'Manager', text: "Is it fixed now?", vi: 'Giờ sửa xong chưa?' },
      { speaker: 'You', text: "Yes, it's back up. We're looking into a long-term fix so it doesn't happen again.", vi: 'Rồi, đã chạy lại. Bọn mình đang tìm cách sửa lâu dài để không lặp lại.' },
      { speaker: 'Manager', text: "Good. Keep me posted.", vi: 'Tốt. Cập nhật cho tôi nhé.' },
    ],
    questions: [
      { q: 'What caused the problem?', options: ['A hacker attack', 'A feature loading too much data', 'A power cut'], answer: 1 },
      { q: 'What is the team doing now?', options: ['Looking for a long-term fix', 'Nothing', 'Rolling back everything'], answer: 0 },
    ],
    connectedSpeech: [
      { written: 'It turns out', spoken: '/ɪt-ˈtɜrn-zaʊt/', note: '"turns out" nối thành "tur-nzout".' },
      { written: 'looking into', spoken: '/ˈlʊ-kɪn-ˈɪn-tə/', note: '"looking" thành "lookin\'", "into" đọc nhẹ "in-tə".' },
    ],
    chunks: [
      { en: 'Basically, …', vi: 'Tóm lại là…', example: 'Basically, we ran out of time.', exampleVi: 'Tóm lại là bọn mình hết thời gian.' },
      { en: 'It turns out (that)…', vi: 'Hoá ra là…', example: 'It turns out the file was corrupted.', exampleVi: 'Hoá ra là file bị hỏng.' },
      { en: 'ran out of…', vi: 'bị hết…', example: 'We ran out of budget.', exampleVi: 'Bọn mình hết ngân sách.' },
      { en: "It's back up.", vi: 'Nó chạy lại rồi.', example: 'The website is back up now.', exampleVi: 'Trang web chạy lại rồi.' },
      { en: "We're looking into it.", vi: 'Bọn mình đang xem xét.', example: "Thanks for reporting. We're looking into it.", exampleVi: 'Cảm ơn đã báo. Bọn mình đang xem xét.' },
      { en: "so it doesn't happen again", vi: 'để không lặp lại', example: "We added a test so it doesn't happen again.", exampleVi: 'Bọn mình thêm test để không lặp lại.' },
      { en: 'Keep me posted.', vi: 'Cập nhật cho tôi nhé.', example: 'Sounds good. Keep me posted.', exampleVi: 'Ổn đấy. Cập nhật cho tôi nhé.' },
      { en: 'The issue is that…', vi: 'Vấn đề là…', example: "The issue is that nobody owns this task.", exampleVi: 'Vấn đề là không ai phụ trách việc này.' },
    ],
    drills: [
      { vi: 'Tóm lại là bọn mình hết thời gian.', en: 'Basically, we ran out of time.' },
      { vi: 'Hoá ra là mật khẩu bị sai.', en: 'It turns out the password was wrong.' },
      { vi: 'Bọn mình đang xem xét.', en: "We're looking into it." },
      { vi: 'Trang web chạy lại rồi.', en: "The website is back up.", accept: ["It's back up."] },
      { vi: 'Vấn đề là không ai kiểm tra nó.', en: 'The issue is that nobody checked it.' },
      { vi: 'Cập nhật cho tôi nhé.', en: 'Keep me posted.' },
    ],
    pattern: {
      frame: 'It turns out ___.', meaning: 'Hoá ra là ___.',
      slots: [
        { vi: 'Hoá ra là khách hàng đã đổi ý.', en: 'It turns out the client changed their mind.' },
        { vi: 'Hoá ra là đường link bị hỏng.', en: 'It turns out the link was broken.' },
        { vi: 'Hoá ra là anh ấy đang nghỉ phép.', en: 'It turns out he was on leave.', accept: ['It turns out he was on vacation.', 'It turns out he was on holiday.'] },
        { vi: 'Hoá ra là đó là lỗi của mình.', en: 'It turns out it was my mistake.' },
      ],
    },
    roleplay: {
      scenario: 'Khách hàng hỏi vì sao đơn hàng bị giao trễ.',
      lines: [
        { speaker: 'them', text: 'My order is three days late. What happened?', vi: 'Đơn hàng của tôi trễ ba ngày. Chuyện gì vậy?' },
        { speaker: 'you', text: "I'm sorry. Basically, there was a problem at the warehouse.", vi: 'Xin lỗi. Tóm lại là có sự cố ở kho.' },
        { speaker: 'them', text: 'What kind of problem?', vi: 'Sự cố gì?' },
        { speaker: 'you', text: 'It turns out some orders were sent to the wrong address.', vi: 'Hoá ra một số đơn bị gửi sai địa chỉ.' },
        { speaker: 'them', text: 'So when will I get it?', vi: 'Vậy khi nào tôi nhận được?' },
        { speaker: 'you', text: "We're looking into it. I'll keep you posted.", vi: 'Bọn tôi đang xem xét. Tôi sẽ cập nhật cho bạn.' },
      ],
    },
  },

  {
    id: 15, level: 'B1', track: 'life', emoji: '📖',
    title: 'Telling a Story', titleVi: 'Kể một câu chuyện',
    situation: 'Bạn kể cho bạn bè chuyện xui xẻo khi đi sân bay.',
    dialogue: [
      { speaker: 'You', text: "You won't believe what happened to me yesterday.", vi: 'Bạn sẽ không tin chuyện xảy ra với mình hôm qua đâu.' },
      { speaker: 'Kim', text: "Oh no, what happened?", vi: 'Ôi, chuyện gì thế?' },
      { speaker: 'You', text: "So I was on my way to the airport, and suddenly the taxi broke down.", vi: 'Mình đang trên đường ra sân bay thì đột nhiên taxi bị hỏng.' },
      { speaker: 'Kim', text: "Seriously? What did you do?", vi: 'Thật á? Rồi bạn làm gì?' },
      { speaker: 'You', text: "I had to run to the main road and grab another one. Long story short, I made it with five minutes to spare.", vi: 'Mình phải chạy ra đường lớn bắt xe khác. Nói ngắn gọn là mình kịp, dư đúng năm phút.' },
      { speaker: 'Kim', text: "No way! That was close.", vi: 'Không thể nào! Suýt nữa thì trễ.' },
      { speaker: 'You', text: "Tell me about it. I was so stressed out.", vi: 'Đừng nói nữa. Mình căng thẳng muốn chết.' },
    ],
    questions: [
      { q: 'What went wrong?', options: ['The flight was cancelled', 'The taxi broke down', 'They lost their passport'], answer: 1 },
      { q: 'Did the speaker catch the flight?', options: ['Yes, just in time', 'No, they missed it', 'The flight was delayed'], answer: 0 },
    ],
    connectedSpeech: [
      { written: 'What did you do?', spoken: '/ˈwʌ-dɪ-dʒə-ˈdu/', note: '"did you" thành "did-ja" — nghe như "whadidja do".' },
      { written: 'Long story short', spoken: '/ˈlɔŋ-ˈstɔ-ri-ˈʃɔrt/', note: 'Nói nhanh như một cụm, nhấn đều vào "long", "sto", "short".' },
    ],
    chunks: [
      { en: "You won't believe…", vi: 'Bạn sẽ không tin…', example: "You won't believe who I saw today.", exampleVi: 'Bạn sẽ không tin hôm nay mình gặp ai đâu.' },
      { en: 'So I was …-ing, and suddenly…', vi: 'Mình đang … thì đột nhiên…', example: 'So I was cooking, and suddenly the power went out.', exampleVi: 'Mình đang nấu ăn thì đột nhiên mất điện.' },
      { en: 'Seriously?', vi: 'Thật á?', example: 'He quit? Seriously?', exampleVi: 'Anh ấy nghỉ việc? Thật á?' },
      { en: 'I had to…', vi: 'Mình phải…', example: 'I had to walk home in the rain.', exampleVi: 'Mình phải đi bộ về nhà dưới mưa.' },
      { en: 'Long story short, …', vi: 'Nói ngắn gọn là…', example: 'Long story short, we got the job.', exampleVi: 'Nói ngắn gọn là bọn mình được nhận.' },
      { en: 'No way!', vi: 'Không thể nào!', example: 'You won the lottery? No way!', exampleVi: 'Bạn trúng số à? Không thể nào!' },
      { en: 'That was close.', vi: 'Suýt nữa thì toang.', example: 'We almost missed the train. That was close.', exampleVi: 'Suýt lỡ tàu. Suýt nữa thì toang.' },
      { en: 'Tell me about it.', vi: 'Đúng thế / Đừng nói nữa.', example: "This traffic is terrible. — Tell me about it.", exampleVi: 'Kẹt xe kinh khủng. — Đúng thế.' },
    ],
    drills: [
      { vi: 'Bạn sẽ không tin chuyện xảy ra hôm qua đâu.', en: "You won't believe what happened yesterday." },
      { vi: 'Mình đang đi làm thì đột nhiên trời mưa.', en: 'So I was going to work, and suddenly it started raining.' },
      { vi: 'Mình phải đợi hai tiếng.', en: 'I had to wait for two hours.', accept: ['I had to wait two hours.'] },
      { vi: 'Nói ngắn gọn là mọi thứ ổn.', en: 'Long story short, everything was fine.' },
      { vi: 'Suýt nữa thì toang.', en: 'That was close.' },
      { vi: 'Thật á? Không thể nào!', en: 'Seriously? No way!' },
    ],
    pattern: {
      frame: 'So I was ___, and suddenly ___.', meaning: 'Mình đang ___ thì đột nhiên ___.',
      slots: [
        { vi: 'Mình đang tắm thì đột nhiên mất nước.', en: 'So I was taking a shower, and suddenly the water stopped.' },
        { vi: 'Mình đang họp thì đột nhiên mất mạng.', en: 'So I was in a meeting, and suddenly the internet went down.' },
        { vi: 'Mình đang ngủ thì đột nhiên điện thoại reo.', en: 'So I was sleeping, and suddenly my phone rang.' },
        { vi: 'Mình đang lái xe thì đột nhiên một con chó chạy ra.', en: 'So I was driving, and suddenly a dog ran out.' },
      ],
    },
    roleplay: {
      scenario: 'Bạn kể cho đồng nghiệp chuyện bị mất ví.',
      lines: [
        { speaker: 'you', text: "You won't believe what happened this morning.", vi: 'Bạn sẽ không tin chuyện sáng nay đâu.' },
        { speaker: 'them', text: 'What happened?', vi: 'Chuyện gì vậy?' },
        { speaker: 'you', text: 'So I was on the bus, and suddenly I realized my wallet was gone.', vi: 'Mình đang trên xe buýt thì đột nhiên nhận ra mất ví.' },
        { speaker: 'them', text: 'Seriously? Did you find it?', vi: 'Thật á? Tìm được không?' },
        { speaker: 'you', text: 'Long story short, a kind woman gave it back to me.', vi: 'Nói ngắn gọn là một chị tốt bụng trả lại cho mình.' },
        { speaker: 'them', text: 'No way! That was lucky.', vi: 'Không thể nào! May thật.' },
      ],
    },
  },

  {
    id: 16, level: 'B1', track: 'life', emoji: '🤝',
    title: 'Negotiating a Better Deal', titleVi: 'Trả giá và thương lượng',
    situation: 'Bạn đi xem căn hộ thuê và thương lượng giá.',
    dialogue: [
      { speaker: 'Landlord', text: "So, what do you think of the apartment?", vi: 'Bạn thấy căn hộ thế nào?' },
      { speaker: 'You', text: "I really like it, but the rent is a bit out of my budget.", vi: 'Mình rất thích, nhưng tiền thuê hơi vượt ngân sách.' },
      { speaker: 'Landlord', text: "I see. What did you have in mind?", vi: 'Tôi hiểu. Bạn dự tính bao nhiêu?' },
      { speaker: 'You', text: "Would you be willing to go down to twelve hundred if I sign for a year?", vi: 'Nếu mình ký một năm thì bác có thể giảm xuống 1.200 không?' },
      { speaker: 'Landlord', text: "Hmm, that's quite low. The best I can do is thirteen hundred.", vi: 'Hmm, thấp quá. Tốt nhất tôi giảm được là 1.300.' },
      { speaker: 'You', text: "How about twelve fifty, and I can move in next week?", vi: 'Hay 1.250, và mình dọn vào tuần sau được?' },
      { speaker: 'Landlord', text: "Alright, you've got a deal.", vi: 'Được rồi, chốt vậy.' },
    ],
    questions: [
      { q: 'What is the problem with the apartment?', options: ['It is too small', 'The rent is too high', 'It is too far'], answer: 1 },
      { q: 'What is the final price?', options: ['1,200', '1,250', '1,300'], answer: 1 },
    ],
    connectedSpeech: [
      { written: 'What did you have in mind?', spoken: '/ˈwʌ-dɪ-dʒə-ˈhæ-vɪn-ˈmaɪnd/', note: '"have in" nối thành "ha-vin".' },
      { written: "you've got a deal", spoken: '/juv-ˈgɑ-də-ˈdil/', note: '"got a" thành "ga-də" — giống bài 9.' },
    ],
    chunks: [
      { en: "It's a bit out of my budget.", vi: 'Hơi vượt ngân sách của mình.', example: 'The car is nice, but a bit out of my budget.', exampleVi: 'Xe đẹp, nhưng hơi vượt ngân sách.' },
      { en: 'What did you have in mind?', vi: 'Bạn dự tính thế nào?', example: 'A different price? What did you have in mind?', exampleVi: 'Giá khác à? Bạn dự tính bao nhiêu?' },
      { en: 'Would you be willing to…?', vi: 'Bạn có sẵn lòng … không?', example: 'Would you be willing to include parking?', exampleVi: 'Bạn có sẵn lòng tính luôn chỗ đỗ xe không?' },
      { en: 'go down to…', vi: 'giảm xuống…', example: 'Can you go down to fifty dollars?', exampleVi: 'Bạn giảm xuống năm mươi đô được không?' },
      { en: 'The best I can do is…', vi: 'Tốt nhất tôi làm được là…', example: 'The best I can do is ten percent off.', exampleVi: 'Tốt nhất tôi giảm được mười phần trăm.' },
      { en: 'if I…', vi: 'nếu mình…', example: "I'll take two if you give me a discount.", exampleVi: 'Mình lấy hai cái nếu bạn giảm giá.' },
      { en: "You've got a deal.", vi: 'Chốt vậy.', example: 'Forty dollars? Okay, you\'ve got a deal.', exampleVi: 'Bốn mươi đô à? Ok, chốt.' },
      { en: "Is that your final price?", vi: 'Đó là giá cuối chưa?', example: "Hmm, is that your final price?", exampleVi: 'Hmm, đó là giá cuối chưa?' },
    ],
    drills: [
      { vi: 'Hơi vượt ngân sách của mình.', en: "It's a bit out of my budget." },
      { vi: 'Bạn giảm xuống một trăm đô được không?', en: 'Can you go down to a hundred dollars?', accept: ['Could you go down to one hundred dollars?'] },
      { vi: 'Bạn có sẵn lòng giảm giá không?', en: 'Would you be willing to lower the price?', accept: ['Would you be willing to give me a discount?'] },
      { vi: 'Đó là giá cuối chưa?', en: 'Is that your final price?' },
      { vi: 'Mình lấy hai cái nếu bạn giảm giá.', en: "I'll take two if you give me a discount." },
      { vi: 'Ok, chốt vậy.', en: "Okay, you've got a deal.", accept: ["Okay, it's a deal."] },
    ],
    pattern: {
      frame: 'Would you be willing to ___?', meaning: 'Bạn có sẵn lòng ___ không?',
      slots: [
        { vi: 'Bạn có sẵn lòng giao hàng miễn phí không?', en: 'Would you be willing to deliver for free?', accept: ['Would you be willing to offer free delivery?'] },
        { vi: 'Bạn có sẵn lòng chờ thêm một tuần không?', en: 'Would you be willing to wait one more week?' },
        { vi: 'Bạn có sẵn lòng chia đôi chi phí không?', en: 'Would you be willing to split the cost?' },
        { vi: 'Bạn có sẵn lòng thử lại không?', en: 'Would you be willing to try again?' },
      ],
    },
    roleplay: {
      scenario: 'Bạn mua một chiếc xe máy cũ.',
      lines: [
        { speaker: 'them', text: "It's in great condition. Two thousand dollars.", vi: 'Xe còn rất tốt. Hai nghìn đô.' },
        { speaker: 'you', text: "I like it, but it's a bit out of my budget.", vi: 'Mình thích, nhưng hơi vượt ngân sách.' },
        { speaker: 'them', text: 'What did you have in mind?', vi: 'Bạn dự tính bao nhiêu?' },
        { speaker: 'you', text: 'Would you be willing to go down to fifteen hundred?', vi: 'Bạn có thể giảm xuống 1.500 không?' },
        { speaker: 'them', text: 'The best I can do is seventeen hundred.', vi: 'Tốt nhất tôi giảm được 1.700.' },
        { speaker: 'you', text: "How about sixteen hundred? I can pay cash today.", vi: '1.600 thì sao? Mình trả tiền mặt hôm nay.' },
      ],
    },
  },

  {
    id: 17, level: 'B1', track: 'work', emoji: '🗓️',
    title: 'Giving Updates at Stand-up', titleVi: 'Báo cáo tiến độ trong buổi họp ngắn',
    situation: 'Buổi họp đứng hằng ngày, mỗi người báo cáo nhanh công việc.',
    dialogue: [
      { speaker: 'Lead', text: "Okay, quick round. What are you working on?", vi: 'Ok, báo cáo nhanh. Bạn đang làm gì?' },
      { speaker: 'You', text: "Yesterday I finished the login page. Today I'm working on the payment flow.", vi: 'Hôm qua mình làm xong trang đăng nhập. Hôm nay làm luồng thanh toán.' },
      { speaker: 'Lead', text: "Great. Any blockers?", vi: 'Tốt. Có gì cản trở không?' },
      { speaker: 'You', text: "Yeah, I'm blocked on the API. I'm still waiting for access from the backend team.", vi: 'Có, mình bị kẹt ở API. Vẫn đang chờ quyền truy cập từ team backend.' },
      { speaker: 'Lead', text: "I'll follow up with them after this.", vi: 'Mình sẽ hỏi lại họ sau buổi này.' },
      { speaker: 'You', text: "Thanks. Other than that, I'm on track to finish by Thursday.", vi: 'Cảm ơn. Ngoài ra thì mình đúng tiến độ, xong trước thứ Năm.' },
    ],
    questions: [
      { q: 'What is the speaker working on today?', options: ['The login page', 'The payment flow', 'The API'], answer: 1 },
      { q: 'What is blocking the speaker?', options: ['Waiting for API access', 'A sick teammate', 'No design yet'], answer: 0 },
    ],
    connectedSpeech: [
      { written: 'What are you working on?', spoken: '/ˈwʌ-dər-jə-ˈwɜr-kɪ-nɑn/', note: '"What are you" thành "whadda-ya"; "working on" nối "workin-on".' },
      { written: 'follow up with them', spoken: '/ˈfɑ-loʊ-ˈʌp-wɪ-ðəm/', note: '"them" đọc nhẹ thành "əm": "with \'em".' },
    ],
    chunks: [
      { en: "I'm working on…", vi: 'Mình đang làm…', example: "I'm working on the new dashboard.", exampleVi: 'Mình đang làm dashboard mới.' },
      { en: 'Yesterday I finished…', vi: 'Hôm qua mình làm xong…', example: 'Yesterday I finished the user tests.', exampleVi: 'Hôm qua mình làm xong phần test người dùng.' },
      { en: 'Any blockers?', vi: 'Có gì cản trở không?', example: 'Before we finish, any blockers?', exampleVi: 'Trước khi kết thúc, có gì cản trở không?' },
      { en: "I'm blocked on…", vi: 'Mình bị kẹt ở…', example: "I'm blocked on the design review.", exampleVi: 'Mình bị kẹt ở khâu duyệt thiết kế.' },
      { en: "I'm still waiting for…", vi: 'Mình vẫn đang chờ…', example: "I'm still waiting for feedback from the client.", exampleVi: 'Mình vẫn đang chờ phản hồi từ khách.' },
      { en: "I'll follow up with…", vi: 'Mình sẽ hỏi lại / nhắc…', example: "I'll follow up with HR about it.", exampleVi: 'Mình sẽ hỏi lại HR về việc đó.' },
      { en: "I'm on track to…", vi: 'Mình đúng tiến độ để…', example: "I'm on track to finish by Friday.", exampleVi: 'Mình đúng tiến độ, xong trước thứ Sáu.' },
      { en: 'Other than that, …', vi: 'Ngoài ra thì…', example: 'Other than that, everything is fine.', exampleVi: 'Ngoài ra thì mọi thứ ổn.' },
    ],
    drills: [
      { vi: 'Hôm nay mình đang làm trang chủ.', en: "Today I'm working on the home page." },
      { vi: 'Hôm qua mình làm xong báo cáo.', en: 'Yesterday I finished the report.' },
      { vi: 'Mình bị kẹt ở phần thiết kế.', en: "I'm blocked on the design." },
      { vi: 'Mình vẫn đang chờ phản hồi.', en: "I'm still waiting for feedback." },
      { vi: 'Mình đúng tiến độ, xong trước thứ Sáu.', en: "I'm on track to finish by Friday." },
      { vi: 'Ngoài ra thì mọi thứ ổn.', en: 'Other than that, everything is fine.', accept: ["Other than that, everything's fine."] },
    ],
    pattern: {
      frame: "I'm still waiting for ___.", meaning: 'Mình vẫn đang chờ ___.',
      slots: [
        { vi: 'Mình vẫn đang chờ sếp duyệt.', en: "I'm still waiting for my manager's approval.", accept: ["I'm still waiting for approval from my manager."] },
        { vi: 'Mình vẫn đang chờ dữ liệu.', en: "I'm still waiting for the data." },
        { vi: 'Mình vẫn đang chờ bản thiết kế cuối.', en: "I'm still waiting for the final design." },
        { vi: 'Mình vẫn đang chờ họ trả lời.', en: "I'm still waiting for them to reply.", accept: ["I'm still waiting for their reply."] },
      ],
    },
    roleplay: {
      scenario: 'Đến lượt bạn báo cáo trong stand-up.',
      lines: [
        { speaker: 'them', text: "Your turn. What's your update?", vi: 'Tới lượt bạn. Có gì mới?' },
        { speaker: 'you', text: "Yesterday I finished the search feature. Today I'm working on the filters.", vi: 'Hôm qua mình xong tính năng tìm kiếm. Hôm nay làm bộ lọc.' },
        { speaker: 'them', text: 'Nice. Any blockers?', vi: 'Tốt. Có gì cản trở không?' },
        { speaker: 'you', text: "I'm still waiting for the final design.", vi: 'Mình vẫn đang chờ bản thiết kế cuối.' },
        { speaker: 'them', text: "I'll follow up with the design team.", vi: 'Mình sẽ nhắc team thiết kế.' },
        { speaker: 'you', text: "Thanks. Other than that, I'm on track.", vi: 'Cảm ơn. Ngoài ra mình đúng tiến độ.' },
      ],
    },
  },

  {
    id: 18, level: 'B1', track: 'work', emoji: '❓',
    title: 'Asking for Clarification', titleVi: 'Hỏi lại cho rõ',
    situation: 'Sếp giao việc nhưng bạn chưa hiểu rõ yêu cầu.',
    dialogue: [
      { speaker: 'Boss', text: "Can you put together a quick summary of the survey results?", vi: 'Bạn tổng hợp nhanh kết quả khảo sát được không?' },
      { speaker: 'You', text: "Sure. Sorry, what do you mean by quick? Like one page?", vi: 'Được. Xin lỗi, "nhanh" là thế nào? Khoảng một trang?' },
      { speaker: 'Boss', text: "Yeah, just the main points. Nothing fancy.", vi: 'Ừ, chỉ ý chính thôi. Không cần cầu kỳ.' },
      { speaker: 'You', text: "Got it. Just to make sure I understand, you want the key numbers and a short conclusion?", vi: 'Hiểu rồi. Để chắc mình hiểu đúng, anh cần số liệu chính và một kết luận ngắn?' },
      { speaker: 'Boss', text: "Exactly. And can you have it ready by tomorrow morning?", vi: 'Đúng vậy. Sáng mai xong được không?' },
      { speaker: 'You', text: "No problem. Should I send it to you or the whole team?", vi: 'Không vấn đề. Mình gửi cho anh hay cả team?' },
      { speaker: 'Boss', text: "Just me for now.", vi: 'Tạm thời gửi mình thôi.' },
    ],
    questions: [
      { q: 'How long should the summary be?', options: ['About one page', 'Ten pages', 'Just one sentence'], answer: 0 },
      { q: 'Who should receive it?', options: ['The whole team', 'Only the boss', 'The client'], answer: 1 },
    ],
    connectedSpeech: [
      { written: 'What do you mean', spoken: '/ˈwʌ-də-jə-ˈmin/', note: 'Giống "What do you think" ở bài 11: "whaddaya mean".' },
      { written: 'put together', spoken: '/ˈpʊ-tə-ˈge-ðər/', note: 'Chữ t cuối của "put" gần như bị nuốt.' },
    ],
    chunks: [
      { en: 'What do you mean by…?', vi: '… nghĩa là sao?', example: 'What do you mean by "urgent"?', exampleVi: '"Gấp" nghĩa là gấp cỡ nào?' },
      { en: 'Just to make sure I understand, …', vi: 'Để chắc mình hiểu đúng…', example: 'Just to make sure I understand, the deadline is Monday?', exampleVi: 'Để chắc mình hiểu đúng, hạn là thứ Hai?' },
      { en: 'put together', vi: 'tổng hợp, soạn', example: "I'll put together a plan.", exampleVi: 'Mình sẽ soạn một kế hoạch.' },
      { en: 'Should I … or …?', vi: 'Mình nên … hay …?', example: 'Should I call them or send an email?', exampleVi: 'Mình nên gọi hay gửi email?' },
      { en: 'Could you give me an example?', vi: 'Bạn cho mình ví dụ được không?', example: "I'm not sure I follow. Could you give me an example?", exampleVi: 'Mình chưa hiểu lắm. Cho mình ví dụ được không?' },
      { en: "I'm not sure I follow.", vi: 'Mình chưa theo kịp lắm.', example: "Sorry, I'm not sure I follow.", exampleVi: 'Xin lỗi, mình chưa theo kịp lắm.' },
      { en: 'have it ready by…', vi: 'xong trước…', example: 'Can you have it ready by noon?', exampleVi: 'Trước trưa xong được không?' },
      { en: 'Nothing fancy.', vi: 'Không cần cầu kỳ.', example: 'Just a simple design, nothing fancy.', exampleVi: 'Thiết kế đơn giản thôi, không cần cầu kỳ.' },
    ],
    drills: [
      { vi: 'Xin lỗi, "sớm" nghĩa là khi nào?', en: 'Sorry, what do you mean by soon?' },
      { vi: 'Để chắc mình hiểu đúng, bạn cần hai bản?', en: 'Just to make sure I understand, you need two copies?' },
      { vi: 'Mình chưa theo kịp lắm.', en: "I'm not sure I follow." },
      { vi: 'Bạn cho mình ví dụ được không?', en: 'Could you give me an example?' },
      { vi: 'Mình nên gửi cho bạn hay cho cả team?', en: 'Should I send it to you or the whole team?' },
      { vi: 'Sáng mai mình sẽ xong.', en: "I'll have it ready by tomorrow morning." },
    ],
    pattern: {
      frame: 'Just to make sure I understand, ___?', meaning: 'Để chắc mình hiểu đúng, ___?',
      slots: [
        { vi: 'Để chắc mình hiểu đúng, họp đã bị huỷ?', en: 'Just to make sure I understand, the meeting is cancelled?' },
        { vi: 'Để chắc mình hiểu đúng, mình bắt đầu từ thứ Hai?', en: 'Just to make sure I understand, I start on Monday?' },
        { vi: 'Để chắc mình hiểu đúng, ngân sách là năm nghìn đô?', en: 'Just to make sure I understand, the budget is five thousand dollars?' },
        { vi: 'Để chắc mình hiểu đúng, bạn muốn bản tiếng Anh?', en: 'Just to make sure I understand, you want the English version?' },
      ],
    },
    roleplay: {
      scenario: 'Đồng nghiệp nhờ bạn "dọn dẹp" file dữ liệu nhưng không rõ ý.',
      lines: [
        { speaker: 'them', text: 'Could you clean up the customer list?', vi: 'Bạn dọn lại danh sách khách hàng được không?' },
        { speaker: 'you', text: 'Sure. Sorry, what do you mean by clean up?', vi: 'Được. Xin lỗi, "dọn lại" nghĩa là sao?' },
        { speaker: 'them', text: 'Remove duplicates and fix the phone numbers.', vi: 'Xoá trùng và sửa số điện thoại.' },
        { speaker: 'you', text: 'Just to make sure I understand, I should not delete any customers?', vi: 'Để chắc mình hiểu đúng, mình không xoá khách hàng nào?' },
        { speaker: 'them', text: 'Right, only the duplicates.', vi: 'Đúng, chỉ xoá bản trùng.' },
        { speaker: 'you', text: 'Got it. Should I send it to you when it is done?', vi: 'Hiểu rồi. Xong mình gửi cho bạn nhé?' },
      ],
    },
  },

  {
    id: 19, level: 'B1', track: 'life', emoji: '✈️',
    title: 'Travel Problems', titleVi: 'Sự cố khi du lịch',
    situation: 'Chuyến bay bị huỷ và bạn cần quầy hãng bay đổi vé.',
    dialogue: [
      { speaker: 'Agent', text: "Next, please. How can I help?", vi: 'Người tiếp theo. Tôi giúp gì được?' },
      { speaker: 'You', text: "Hi, my flight to Singapore just got cancelled. What are my options?", vi: 'Chào, chuyến bay đi Singapore của tôi vừa bị huỷ. Tôi có những lựa chọn nào?' },
      { speaker: 'Agent', text: "I'm sorry about that. I can put you on the next flight at six p.m.", vi: 'Rất tiếc. Tôi có thể chuyển bạn sang chuyến tiếp theo lúc 6 giờ chiều.' },
      { speaker: 'You', text: "That's quite late. Is there anything earlier?", vi: 'Khá trễ. Có chuyến nào sớm hơn không?' },
      { speaker: 'Agent', text: "There's one at two, but it has a stopover in Kuala Lumpur.", vi: 'Có chuyến lúc 2 giờ, nhưng quá cảnh ở Kuala Lumpur.' },
      { speaker: 'You', text: "I'd rather take the direct one, then. Am I entitled to a meal voucher?", vi: 'Vậy tôi chọn chuyến bay thẳng. Tôi có được phiếu ăn không?' },
      { speaker: 'Agent', text: "Yes, here you go. You can use it at any restaurant in the terminal.", vi: 'Có, đây bạn. Bạn dùng ở bất kỳ nhà hàng nào trong nhà ga.' },
    ],
    questions: [
      { q: 'Which flight does the traveler choose?', options: ['The 2 p.m. with a stopover', 'The 6 p.m. direct flight', 'A flight tomorrow'], answer: 1 },
      { q: 'What does the traveler get?', options: ['A refund', 'A hotel room', 'A meal voucher'], answer: 2 },
    ],
    connectedSpeech: [
      { written: 'just got cancelled', spoken: '/ˈdʒʌs-gɑt-ˈkæn-səld/', note: '"just got" mất chữ t của "just": "jus-got".' },
      { written: "I'd rather", spoken: '/aɪd-ˈræ-ðər/', note: '"I\'d" rất ngắn, dễ nghe nhầm thành "I". Nhấn vào "ra".' },
    ],
    chunks: [
      { en: '… just got cancelled.', vi: '… vừa bị huỷ.', example: 'My train just got cancelled.', exampleVi: 'Chuyến tàu của mình vừa bị huỷ.' },
      { en: 'What are my options?', vi: 'Mình có những lựa chọn nào?', example: "I missed my connection. What are my options?", exampleVi: 'Mình lỡ chuyến nối. Mình có lựa chọn nào?' },
      { en: 'Is there anything earlier?', vi: 'Có cái nào sớm hơn không?', example: 'Ten a.m. is too late. Is there anything earlier?', exampleVi: '10 giờ trễ quá. Có chuyến nào sớm hơn không?' },
      { en: "I'd rather…", vi: 'Mình thà… / Mình muốn…', example: "I'd rather wait than pay extra.", exampleVi: 'Mình thà chờ còn hơn trả thêm tiền.' },
      { en: 'Am I entitled to…?', vi: 'Mình có được hưởng… không?', example: 'Am I entitled to compensation?', exampleVi: 'Mình có được bồi thường không?' },
      { en: 'My luggage hasn\'t arrived.', vi: 'Hành lý của mình chưa tới.', example: "Excuse me, my luggage hasn't arrived.", exampleVi: 'Xin lỗi, hành lý của tôi chưa tới.' },
      { en: 'a stopover in…', vi: 'quá cảnh ở…', example: 'The flight has a stopover in Dubai.', exampleVi: 'Chuyến bay quá cảnh ở Dubai.' },
      { en: 'I have a booking under…', vi: 'Mình có đặt chỗ tên…', example: 'Hi, I have a booking under Nguyen.', exampleVi: 'Chào, mình có đặt phòng tên Nguyễn.' },
    ],
    drills: [
      { vi: 'Chuyến bay của mình vừa bị huỷ.', en: 'My flight just got cancelled.' },
      { vi: 'Mình có những lựa chọn nào?', en: 'What are my options?' },
      { vi: 'Có chuyến nào sớm hơn không?', en: 'Is there anything earlier?' },
      { vi: 'Mình có được bồi thường không?', en: 'Am I entitled to compensation?' },
      { vi: 'Hành lý của mình chưa tới.', en: "My luggage hasn't arrived." },
      { vi: 'Chào, mình có đặt phòng tên Trần.', en: 'Hi, I have a booking under Tran.' },
    ],
    pattern: {
      frame: "I'd rather ___.", meaning: 'Mình thà / muốn ___ hơn.',
      slots: [
        { vi: 'Mình muốn ngồi cạnh cửa sổ hơn.', en: "I'd rather sit by the window.", accept: ["I'd rather have a window seat."] },
        { vi: 'Mình thà đi taxi còn hơn.', en: "I'd rather take a taxi." },
        { vi: 'Mình muốn ở lại thêm một đêm hơn.', en: "I'd rather stay one more night." },
        { vi: 'Mình muốn được hoàn tiền hơn.', en: "I'd rather get a refund." },
      ],
    },
    roleplay: {
      scenario: 'Đến khách sạn nhưng phòng chưa sẵn sàng.',
      lines: [
        { speaker: 'you', text: 'Hi, I have a booking under Pham.', vi: 'Chào, tôi có đặt phòng tên Phạm.' },
        { speaker: 'them', text: "Welcome. I'm afraid your room isn't ready yet.", vi: 'Chào mừng. E là phòng của bạn chưa sẵn sàng.' },
        { speaker: 'you', text: 'Oh. What are my options?', vi: 'Ồ. Tôi có những lựa chọn nào?' },
        { speaker: 'them', text: 'You can wait in the lobby, or we can upgrade you for a small fee.', vi: 'Bạn có thể chờ ở sảnh, hoặc nâng hạng với phí nhỏ.' },
        { speaker: 'you', text: "I'd rather wait. Can I leave my luggage here?", vi: 'Tôi chờ thì hơn. Tôi gửi hành lý ở đây được không?' },
      ],
    },
  },

  {
    id: 20, level: 'B1', track: 'work', emoji: '🌐',
    title: 'Networking & Introducing Yourself', titleVi: 'Giới thiệu bản thân khi giao lưu',
    situation: 'Bạn gặp người mới ở một sự kiện công nghệ.',
    dialogue: [
      { speaker: 'Chris', text: "Hi, I don't think we've met. I'm Chris.", vi: 'Chào, hình như mình chưa gặp nhau. Mình là Chris.' },
      { speaker: 'You', text: "Nice to meet you, Chris. I'm Linh. I work in product at a fintech startup.", vi: 'Rất vui được gặp, Chris. Mình là Linh. Mình làm product ở một startup fintech.' },
      { speaker: 'Chris', text: "Oh, interesting! What does your company do?", vi: 'Ồ, hay quá! Công ty bạn làm gì?' },
      { speaker: 'You', text: "We help small businesses manage their payments. What about you, what brings you here?", vi: 'Bọn mình giúp doanh nghiệp nhỏ quản lý thanh toán. Còn bạn, điều gì đưa bạn tới đây?' },
      { speaker: 'Chris', text: "I'm looking for partners for a new project, actually.", vi: 'Thật ra mình đang tìm đối tác cho một dự án mới.' },
      { speaker: 'You', text: "That sounds like something we could help with. Shall we connect on LinkedIn?", vi: 'Nghe có vẻ là việc bọn mình giúp được. Mình kết nối LinkedIn nhé?' },
      { speaker: 'Chris', text: "Definitely. It was great talking to you.", vi: 'Chắc chắn rồi. Nói chuyện với bạn vui lắm.' },
    ],
    questions: [
      { q: 'What does Linh\'s company do?', options: ['Builds games', 'Helps small businesses with payments', 'Sells phones'], answer: 1 },
      { q: 'Why is Chris at the event?', options: ['Looking for a job', 'Looking for partners', 'Giving a talk'], answer: 1 },
    ],
    connectedSpeech: [
      { written: "I don't think we've met", spoken: '/aɪ-ˈdoʊn-θɪŋk-wiv-ˈmet/', note: '"don\'t" mất chữ t: "don\' think".' },
      { written: 'What brings you here?', spoken: '/ˈwʌt-ˈbrɪŋ-zjə-ˈhɪr/', note: '"brings you" nối thành "bring-zya".' },
    ],
    chunks: [
      { en: "I don't think we've met.", vi: 'Hình như mình chưa gặp nhau.', example: "Hi, I don't think we've met. I'm Hoa.", exampleVi: 'Chào, hình như mình chưa gặp. Mình là Hoa.' },
      { en: 'I work in … at…', vi: 'Mình làm mảng … ở…', example: 'I work in marketing at a hotel group.', exampleVi: 'Mình làm marketing ở một tập đoàn khách sạn.' },
      { en: 'What does your company do?', vi: 'Công ty bạn làm gì?', example: 'Sounds cool. What does your company do?', exampleVi: 'Nghe hay đấy. Công ty bạn làm gì?' },
      { en: 'We help … (to) …', vi: 'Bọn mình giúp … …', example: 'We help schools manage their classes online.', exampleVi: 'Bọn mình giúp trường học quản lý lớp online.' },
      { en: 'What brings you here?', vi: 'Điều gì đưa bạn đến đây?', example: 'So, what brings you here today?', exampleVi: 'Vậy hôm nay điều gì đưa bạn tới đây?' },
      { en: "That sounds like something we could…", vi: 'Nghe như việc bọn mình có thể…', example: 'That sounds like something we could work on together.', exampleVi: 'Nghe như việc ta có thể làm cùng nhau.' },
      { en: 'Shall we connect on LinkedIn?', vi: 'Mình kết nối LinkedIn nhé?', example: 'Great chat. Shall we connect on LinkedIn?', exampleVi: 'Nói chuyện vui quá. Kết nối LinkedIn nhé?' },
      { en: 'It was great talking to you.', vi: 'Nói chuyện với bạn vui lắm.', example: "I have to go, but it was great talking to you.", exampleVi: 'Mình phải đi, nhưng nói chuyện với bạn vui lắm.' },
    ],
    drills: [
      { vi: 'Hình như mình chưa gặp nhau. Mình là Minh.', en: "I don't think we've met. I'm Minh." },
      { vi: 'Mình làm kỹ sư phần mềm ở một ngân hàng.', en: 'I work as a software engineer at a bank.', accept: ['I work in software engineering at a bank.'] },
      { vi: 'Công ty bạn làm gì?', en: 'What does your company do?' },
      { vi: 'Điều gì đưa bạn đến đây?', en: 'What brings you here?' },
      { vi: 'Mình kết nối LinkedIn nhé?', en: 'Shall we connect on LinkedIn?' },
      { vi: 'Nói chuyện với bạn vui lắm.', en: 'It was great talking to you.' },
    ],
    pattern: {
      frame: 'We help ___.', meaning: 'Bọn mình giúp ___.',
      slots: [
        { vi: 'Bọn mình giúp nhà hàng nhận đơn online.', en: 'We help restaurants take orders online.' },
        { vi: 'Bọn mình giúp sinh viên tìm việc.', en: 'We help students find jobs.' },
        { vi: 'Bọn mình giúp công ty tuyển dụng nhanh hơn.', en: 'We help companies hire faster.' },
        { vi: 'Bọn mình giúp mọi người học tiếng Anh.', en: 'We help people learn English.' },
      ],
    },
    roleplay: {
      scenario: 'Bạn bắt chuyện với một người ở sự kiện networking.',
      lines: [
        { speaker: 'you', text: "Hi, I don't think we've met. I'm Tuan.", vi: 'Chào, hình như mình chưa gặp. Mình là Tuấn.' },
        { speaker: 'them', text: 'Nice to meet you. I am Emma. What do you do?', vi: 'Rất vui được gặp. Mình là Emma. Bạn làm gì?' },
        { speaker: 'you', text: 'I work in sales at a software company. What brings you here?', vi: 'Mình làm sales ở công ty phần mềm. Điều gì đưa bạn tới đây?' },
        { speaker: 'them', text: "I'm hiring developers for my team.", vi: 'Mình đang tuyển lập trình viên cho team.' },
        { speaker: 'you', text: 'Interesting! Shall we connect on LinkedIn?', vi: 'Hay quá! Kết nối LinkedIn nhé?' },
        { speaker: 'them', text: 'Sure. It was great talking to you.', vi: 'Được chứ. Nói chuyện với bạn vui lắm.' },
      ],
    },
  },
];
