import type { FastTalkUnit } from './types';

export const unitsA2: FastTalkUnit[] = [
  {
    id: 1, level: 'A2+', track: 'life', emoji: '☕',
    title: 'Ordering at a Café', titleVi: 'Gọi đồ ở quán cà phê',
    situation: 'Bạn gọi đồ uống và đồ ăn ở một quán cà phê đông khách.',
    dialogue: [
      { speaker: 'Barista', text: "Hi there, what can I get for you?", vi: 'Chào bạn, bạn muốn gọi gì?' },
      { speaker: 'You', text: "Can I get a large iced latte, please?", vi: 'Cho mình một ly latte đá cỡ lớn nhé.' },
      { speaker: 'Barista', text: "Sure. Would you like oat milk or regular?", vi: 'Được. Bạn muốn sữa yến mạch hay sữa thường?' },
      { speaker: 'You', text: "Regular is fine. And I'll have one of those croissants too.", vi: 'Sữa thường được rồi. Và cho mình thêm một cái croissant kia.' },
      { speaker: 'Barista', text: "Is that for here or to go?", vi: 'Bạn dùng ở đây hay mang đi?' },
      { speaker: 'You', text: "To go, please. Can I pay by card?", vi: 'Mang đi nhé. Mình trả bằng thẻ được không?' },
      { speaker: 'Barista', text: "Of course. That'll be nine fifty.", vi: 'Tất nhiên. Tổng là 9 đô 50.' },
    ],
    questions: [
      { q: 'What kind of milk does the customer want?', options: ['Oat milk', 'Regular milk', 'No milk'], answer: 1 },
      { q: 'Where will the customer have the drink?', options: ['In the café', 'Outside, to go', 'At the office desk'], answer: 1 },
    ],
    connectedSpeech: [
      { written: 'Can I get a', spoken: '/kə-naɪ-ˈge-də/', note: '"Can I" nối thành "kə-naɪ", "get a" thành "ge-də" — nghe như một từ dài.' },
      { written: "That'll be", spoken: '/ˈðæ-dl-bi/', note: 'Chữ t giữa hai nguyên âm đọc nhẹ như "d" (giọng Mỹ).' },
    ],
    chunks: [
      { en: 'Can I get…, please?', vi: 'Cho mình… nhé?', example: 'Can I get a small black coffee, please?', exampleVi: 'Cho mình một ly cà phê đen nhỏ nhé.' },
      { en: "I'll have…", vi: 'Mình lấy…', example: "I'll have the chicken sandwich.", exampleVi: 'Mình lấy bánh mì kẹp gà.' },
      { en: 'for here or to go', vi: 'dùng ở đây hay mang đi', example: 'Is this for here or to go?', exampleVi: 'Cái này dùng ở đây hay mang đi?' },
      { en: '… is fine', vi: '… là được rồi', example: 'Regular sugar is fine.', exampleVi: 'Đường bình thường là được rồi.' },
      { en: 'Can I pay by card?', vi: 'Mình trả bằng thẻ được không?', example: "Can I pay by card? I don't have cash.", exampleVi: 'Mình trả thẻ được không? Mình không có tiền mặt.' },
      { en: 'Could I have it without…?', vi: 'Cho mình không có… được không?', example: 'Could I have it without ice?', exampleVi: 'Cho mình không đá được không?' },
      { en: "That's all, thanks.", vi: 'Vậy thôi, cảm ơn.', example: "Just the coffee. That's all, thanks.", exampleVi: 'Chỉ cà phê thôi. Vậy thôi, cảm ơn.' },
      { en: 'Could I get a receipt?', vi: 'Cho mình xin hoá đơn?', example: "Could I get a receipt? It's for work.", exampleVi: 'Cho mình xin hoá đơn được không? Để thanh toán công ty.' },
    ],
    drills: [
      { vi: 'Cho mình một ly trà sữa cỡ lớn nhé.', en: 'Can I get a large milk tea, please?', accept: ["I'll have a large milk tea, please."] },
      { vi: 'Mang đi nhé.', en: 'To go, please.' },
      { vi: 'Mình trả bằng thẻ được không?', en: 'Can I pay by card?' },
      { vi: 'Cho mình không đá được không?', en: 'Could I have it without ice?' },
      { vi: 'Vậy thôi, cảm ơn.', en: "That's all, thanks." },
      { vi: 'Mình lấy bánh mì kẹp gà.', en: "I'll have the chicken sandwich." },
    ],
    pattern: {
      frame: 'Could I have it without ___?', meaning: 'Cho mình không có ___ được không?',
      slots: [
        { vi: 'Cho mình không đường được không?', en: 'Could I have it without sugar?' },
        { vi: 'Cho mình không hành được không?', en: 'Could I have it without onions?' },
        { vi: 'Cho mình không cay được không?', en: 'Could I have it without chili?' },
        { vi: 'Cho mình không kem được không?', en: 'Could I have it without cream?' },
      ],
    },
    roleplay: {
      scenario: 'Bạn gọi một ly cà phê mang đi và trả bằng thẻ.',
      lines: [
        { speaker: 'them', text: 'Hi! What can I get for you today?', vi: 'Chào! Hôm nay bạn gọi gì?' },
        { speaker: 'you', text: 'Can I get a medium latte, please?', vi: 'Cho mình một ly latte cỡ vừa nhé.' },
        { speaker: 'them', text: 'Sure. For here or to go?', vi: 'Được. Dùng ở đây hay mang đi?' },
        { speaker: 'you', text: 'To go, please. Can I pay by card?', vi: 'Mang đi nhé. Mình trả thẻ được không?' },
        { speaker: 'them', text: 'Yes, of course. Anything else?', vi: 'Được chứ. Còn gì nữa không?' },
        { speaker: 'you', text: "No, that's all, thanks.", vi: 'Không, vậy thôi, cảm ơn.' },
      ],
    },
  },

  {
    id: 2, level: 'A2+', track: 'life', emoji: '🧭',
    title: 'Asking for Directions', titleVi: 'Hỏi đường',
    situation: 'Bạn bị lạc ở một thành phố mới và hỏi người đi đường.',
    dialogue: [
      { speaker: 'You', text: "Excuse me, sorry to bother you. Do you know where the train station is?", vi: 'Xin lỗi đã làm phiền. Bạn có biết ga tàu ở đâu không?' },
      { speaker: 'Local', text: "Sure. Go straight down this road and turn left at the lights.", vi: 'Có. Đi thẳng đường này rồi rẽ trái ở đèn giao thông.' },
      { speaker: 'You', text: "Turn left at the lights. Is it far from here?", vi: 'Rẽ trái ở đèn. Có xa đây không?' },
      { speaker: 'Local', text: "Not really, it's about a ten-minute walk.", vi: 'Không xa lắm, đi bộ khoảng mười phút.' },
      { speaker: 'You', text: "Great. Is there a bus I can take instead?", vi: 'Tốt quá. Có xe buýt nào mình đi thay được không?' },
      { speaker: 'Local', text: "The 12 goes there, but honestly walking is faster.", vi: 'Tuyến 12 đi tới đó, nhưng thật ra đi bộ nhanh hơn.' },
      { speaker: 'You', text: "Got it. Thanks so much for your help!", vi: 'Hiểu rồi. Cảm ơn bạn nhiều nhé!' },
    ],
    questions: [
      { q: 'Where should the person turn left?', options: ['At the bank', 'At the traffic lights', 'At the bus stop'], answer: 1 },
      { q: 'What does the local recommend?', options: ['Taking bus 12', 'Taking a taxi', 'Walking'], answer: 2 },
    ],
    connectedSpeech: [
      { written: 'Do you know', spoken: '/də-jə-ˈnoʊ/', note: '"Do you" rút gọn thành "də-jə", gần như "d\'ya know".' },
      { written: 'Is it far', spoken: '/ɪ-zɪt-ˈfɑr/', note: 'Phụ âm cuối "s" nối sang nguyên âm "it": "i-zit".' },
    ],
    chunks: [
      { en: 'Sorry to bother you, but…', vi: 'Xin lỗi đã làm phiền, nhưng…', example: 'Sorry to bother you, but is this the way to the museum?', exampleVi: 'Xin lỗi làm phiền, đây có phải đường tới bảo tàng không?' },
      { en: 'Do you know where … is?', vi: 'Bạn có biết … ở đâu không?', example: 'Do you know where the nearest ATM is?', exampleVi: 'Bạn có biết cây ATM gần nhất ở đâu không?' },
      { en: 'go straight', vi: 'đi thẳng', example: 'Go straight for two blocks.', exampleVi: 'Đi thẳng hai dãy nhà.' },
      { en: 'turn left / right at…', vi: 'rẽ trái / phải ở…', example: 'Turn right at the corner.', exampleVi: 'Rẽ phải ở góc đường.' },
      { en: 'Is it far from here?', vi: 'Có xa đây không?', example: 'Is the hotel far from here?', exampleVi: 'Khách sạn có xa đây không?' },
      { en: "a ten-minute walk", vi: 'đi bộ mười phút', example: "It's just a five-minute walk.", exampleVi: 'Chỉ đi bộ năm phút thôi.' },
      { en: 'Got it.', vi: 'Hiểu rồi.', example: 'Left at the lights, then straight. Got it.', exampleVi: 'Rẽ trái ở đèn, rồi đi thẳng. Hiểu rồi.' },
      { en: "I'm a bit lost.", vi: 'Mình hơi bị lạc.', example: "Sorry, I'm a bit lost. Where am I on this map?", exampleVi: 'Xin lỗi, mình hơi lạc. Mình đang ở đâu trên bản đồ này?' },
    ],
    drills: [
      { vi: 'Xin lỗi, mình hơi bị lạc.', en: "Sorry, I'm a bit lost." },
      { vi: 'Bạn có biết nhà vệ sinh ở đâu không?', en: 'Do you know where the restroom is?', accept: ['Do you know where the toilet is?', 'Do you know where the bathroom is?'] },
      { vi: 'Có xa đây không?', en: 'Is it far from here?' },
      { vi: 'Đi bộ khoảng năm phút.', en: "It's about a five-minute walk." },
      { vi: 'Rẽ trái ở đèn giao thông.', en: 'Turn left at the lights.', accept: ['Turn left at the traffic lights.'] },
      { vi: 'Hiểu rồi, cảm ơn nhiều nhé.', en: 'Got it, thanks so much.' },
    ],
    pattern: {
      frame: 'Do you know where ___ is?', meaning: 'Bạn có biết ___ ở đâu không?',
      slots: [
        { vi: 'Bạn có biết ga tàu điện ngầm ở đâu không?', en: 'Do you know where the subway station is?', accept: ['Do you know where the metro station is?', 'Do you know where the MRT station is?'] },
        { vi: 'Bạn có biết hiệu thuốc ở đâu không?', en: 'Do you know where the pharmacy is?' },
        { vi: 'Bạn có biết siêu thị ở đâu không?', en: 'Do you know where the supermarket is?' },
        { vi: 'Bạn có biết trạm xe buýt ở đâu không?', en: 'Do you know where the bus stop is?' },
      ],
    },
    roleplay: {
      scenario: 'Bạn hỏi một người lạ đường đến khách sạn.',
      lines: [
        { speaker: 'you', text: 'Excuse me, do you know where the Grand Hotel is?', vi: 'Xin lỗi, bạn có biết khách sạn Grand ở đâu không?' },
        { speaker: 'them', text: 'Yes, go straight and turn right at the bank.', vi: 'Có, đi thẳng rồi rẽ phải ở ngân hàng.' },
        { speaker: 'you', text: 'Is it far from here?', vi: 'Có xa đây không?' },
        { speaker: 'them', text: "No, it's only a five-minute walk.", vi: 'Không, chỉ đi bộ năm phút.' },
        { speaker: 'you', text: 'Got it. Thanks so much!', vi: 'Hiểu rồi. Cảm ơn nhiều!' },
      ],
    },
  },

  {
    id: 3, level: 'A2+', track: 'work', emoji: '👋',
    title: 'Small Talk with a Colleague', titleVi: 'Nói chuyện xã giao với đồng nghiệp',
    situation: 'Gặp đồng nghiệp ở pantry vào sáng thứ Hai.',
    dialogue: [
      { speaker: 'Mia', text: "Morning! How's it going?", vi: 'Chào buổi sáng! Dạo này sao rồi?' },
      { speaker: 'You', text: "Not bad, thanks. Still waking up, to be honest. How about you?", vi: 'Cũng ổn, cảm ơn. Thật ra vẫn đang tỉnh ngủ. Còn bạn?' },
      { speaker: 'Mia', text: "Same here. Did you get up to anything fun this weekend?", vi: 'Mình cũng vậy. Cuối tuần bạn có làm gì vui không?' },
      { speaker: 'You', text: "Nothing special. I just stayed in and caught up on sleep.", vi: 'Không có gì đặc biệt. Mình ở nhà ngủ bù.' },
      { speaker: 'Mia', text: "Sounds nice. I went hiking, and now my legs are killing me.", vi: 'Nghe hay đấy. Mình đi leo núi, giờ chân đau muốn chết.' },
      { speaker: 'You', text: "Oh no! Anyway, I'd better get going. Catch you later!", vi: 'Ôi! Thôi, mình phải đi đây. Gặp lại sau nhé!' },
    ],
    questions: [
      { q: 'What did the speaker do at the weekend?', options: ['Went hiking', 'Stayed home and slept', 'Worked overtime'], answer: 1 },
      { q: "Why are Mia's legs sore?", options: ['She went hiking', 'She went running', 'She stood all day'], answer: 0 },
    ],
    connectedSpeech: [
      { written: "How's it going?", spoken: '/ˌhaʊ-zɪt-ˈgoʊ-ɪn/', note: '"going" thường đọc thành "goin\'", bỏ âm "g" cuối.' },
      { written: "I'd better get going", spoken: '/aɪd-ˈbe-dər-ˈge-ˈgoʊ-ɪn/', note: '"get going" nuốt chữ "t": "ge-goin\'".' },
    ],
    chunks: [
      { en: "How's it going?", vi: 'Dạo này sao rồi?', example: "Hey Tom, how's it going?", exampleVi: 'Chào Tom, dạo này sao rồi?' },
      { en: 'Not bad, thanks.', vi: 'Cũng ổn, cảm ơn.', example: 'Not bad, thanks. A bit busy.', exampleVi: 'Cũng ổn, cảm ơn. Hơi bận chút.' },
      { en: 'How about you?', vi: 'Còn bạn thì sao?', example: 'I had a good weekend. How about you?', exampleVi: 'Cuối tuần mình vui. Còn bạn?' },
      { en: 'Same here.', vi: 'Mình cũng vậy.', example: "I'm so tired today. — Same here.", exampleVi: 'Hôm nay mệt quá. — Mình cũng vậy.' },
      { en: 'get up to anything fun', vi: 'làm gì vui', example: 'Did you get up to anything fun last night?', exampleVi: 'Tối qua bạn có làm gì vui không?' },
      { en: 'Nothing special.', vi: 'Không có gì đặc biệt.', example: 'Nothing special, I just watched Netflix.', exampleVi: 'Không có gì đặc biệt, mình chỉ xem Netflix.' },
      { en: "I'd better get going.", vi: 'Mình phải đi đây.', example: "I've got a meeting. I'd better get going.", exampleVi: 'Mình có họp. Mình phải đi đây.' },
      { en: 'Catch you later!', vi: 'Gặp lại sau nhé!', example: 'Okay, catch you later!', exampleVi: 'Ok, gặp lại sau nhé!' },
    ],
    drills: [
      { vi: 'Dạo này sao rồi?', en: "How's it going?" },
      { vi: 'Cũng ổn, cảm ơn. Còn bạn?', en: 'Not bad, thanks. How about you?' },
      { vi: 'Cuối tuần bạn có làm gì vui không?', en: 'Did you get up to anything fun this weekend?', accept: ['Did you do anything fun this weekend?'] },
      { vi: 'Không có gì đặc biệt.', en: 'Nothing special.' },
      { vi: 'Mình cũng vậy.', en: 'Same here.' },
      { vi: 'Mình phải đi đây. Gặp lại sau nhé!', en: "I'd better get going. Catch you later!" },
    ],
    pattern: {
      frame: 'Did you get up to anything fun ___?', meaning: 'Bạn có làm gì vui ___ không?',
      slots: [
        { vi: 'Tối qua bạn có làm gì vui không?', en: 'Did you get up to anything fun last night?' },
        { vi: 'Kỳ nghỉ bạn có làm gì vui không?', en: 'Did you get up to anything fun on your holiday?', accept: ['Did you get up to anything fun on your vacation?'] },
        { vi: 'Hôm Tết bạn có làm gì vui không?', en: 'Did you get up to anything fun over Tet?' },
        { vi: 'Hôm qua bạn có làm gì vui không?', en: 'Did you get up to anything fun yesterday?' },
      ],
    },
    roleplay: {
      scenario: 'Đồng nghiệp chào bạn ở thang máy.',
      lines: [
        { speaker: 'them', text: "Hey! How's it going?", vi: 'Này! Dạo này sao rồi?' },
        { speaker: 'you', text: 'Not bad, thanks. How about you?', vi: 'Cũng ổn, cảm ơn. Còn bạn?' },
        { speaker: 'them', text: 'Pretty good. Did you get up to anything fun this weekend?', vi: 'Khá ổn. Cuối tuần có làm gì vui không?' },
        { speaker: 'you', text: 'Nothing special. I just stayed in.', vi: 'Không có gì đặc biệt. Mình chỉ ở nhà.' },
        { speaker: 'them', text: "Fair enough. Well, this is my floor.", vi: 'Cũng được. À, tới tầng mình rồi.' },
        { speaker: 'you', text: 'Catch you later!', vi: 'Gặp lại sau nhé!' },
      ],
    },
  },

  {
    id: 4, level: 'A2+', track: 'life', emoji: '📅',
    title: 'Making Plans with Friends', titleVi: 'Rủ bạn bè đi chơi',
    situation: 'Bạn rủ một người bạn đi ăn tối cuối tuần.',
    dialogue: [
      { speaker: 'You', text: "Hey, are you free on Saturday night?", vi: 'Này, tối thứ Bảy bạn rảnh không?' },
      { speaker: 'Jake', text: "I think so. Why, what's up?", vi: 'Chắc là rảnh. Sao thế?' },
      { speaker: 'You', text: "Do you want to grab dinner? There's a new Thai place near me.", vi: 'Đi ăn tối không? Gần nhà mình có quán Thái mới mở.' },
      { speaker: 'Jake', text: "Sounds good! What time works for you?", vi: 'Được đó! Mấy giờ thì tiện cho bạn?' },
      { speaker: 'You', text: "How about seven? We could meet at the station.", vi: 'Bảy giờ được không? Mình gặp nhau ở ga nhé.' },
      { speaker: 'Jake', text: "Perfect. Let me know if anything changes.", vi: 'Hoàn hảo. Có gì thay đổi thì báo mình nhé.' },
      { speaker: 'You', text: "Will do. See you then!", vi: 'Ok nhé. Hẹn gặp lúc đó!' },
    ],
    questions: [
      { q: 'What are they going to do?', options: ['Watch a movie', 'Have dinner', 'Go shopping'], answer: 1 },
      { q: 'Where will they meet?', options: ['At the restaurant', 'At the station', "At Jake's house"], answer: 1 },
    ],
    connectedSpeech: [
      { written: 'Do you want to', spoken: '/də-jə-ˈwɑ-nə/', note: '"want to" thành "wanna" — rất phổ biến khi nói nhanh.' },
      { written: 'Let me know', spoken: '/ˈle-mi-ˈnoʊ/', note: '"Let me" thành "lemme".' },
    ],
    chunks: [
      { en: 'Are you free on…?', vi: 'Bạn rảnh vào… không?', example: 'Are you free on Sunday afternoon?', exampleVi: 'Chiều Chủ nhật bạn rảnh không?' },
      { en: "What's up?", vi: 'Có chuyện gì thế?', example: "You called me? What's up?", exampleVi: 'Bạn gọi mình à? Có chuyện gì thế?' },
      { en: 'Do you want to grab…?', vi: 'Đi ăn/uống… không?', example: 'Do you want to grab a coffee after work?', exampleVi: 'Tan làm đi uống cà phê không?' },
      { en: 'Sounds good!', vi: 'Được đó! / Nghe ổn đấy!', example: 'Pizza tonight? — Sounds good!', exampleVi: 'Tối nay ăn pizza nhé? — Được đó!' },
      { en: 'What time works for you?', vi: 'Mấy giờ thì tiện cho bạn?', example: 'I can meet tomorrow. What time works for you?', exampleVi: 'Mai mình gặp được. Mấy giờ tiện cho bạn?' },
      { en: 'How about…?', vi: '… thì sao?', example: 'How about Friday instead?', exampleVi: 'Thay vào đó thứ Sáu thì sao?' },
      { en: 'Let me know if…', vi: 'Báo mình nếu…', example: 'Let me know if you can make it.', exampleVi: 'Báo mình nếu bạn đến được nhé.' },
      { en: 'See you then!', vi: 'Hẹn gặp lúc đó!', example: 'Okay, seven at the station. See you then!', exampleVi: 'Ok, bảy giờ ở ga. Hẹn gặp lúc đó!' },
    ],
    drills: [
      { vi: 'Tối thứ Sáu bạn rảnh không?', en: 'Are you free on Friday night?' },
      { vi: 'Đi uống cà phê không?', en: 'Do you want to grab a coffee?' },
      { vi: 'Mấy giờ thì tiện cho bạn?', en: 'What time works for you?' },
      { vi: 'Tám giờ thì sao?', en: 'How about eight?', accept: ["How about eight o'clock?"] },
      { vi: 'Có gì thay đổi thì báo mình nhé.', en: 'Let me know if anything changes.' },
      { vi: 'Được đó! Hẹn gặp lúc đó!', en: 'Sounds good! See you then!' },
    ],
    pattern: {
      frame: 'Do you want to grab ___?', meaning: 'Đi ___ không?',
      slots: [
        { vi: 'Đi ăn trưa không?', en: 'Do you want to grab lunch?' },
        { vi: 'Đi uống chút gì không?', en: 'Do you want to grab a drink?' },
        { vi: 'Đi ăn chút gì không?', en: 'Do you want to grab a bite?', accept: ['Do you want to grab something to eat?'] },
        { vi: 'Đi ăn sáng không?', en: 'Do you want to grab breakfast?' },
      ],
    },
    roleplay: {
      scenario: 'Bạn rủ một người bạn đi xem phim Chủ nhật.',
      lines: [
        { speaker: 'you', text: 'Hey, are you free on Sunday?', vi: 'Này, Chủ nhật bạn rảnh không?' },
        { speaker: 'them', text: "I think so. What's up?", vi: 'Chắc là rảnh. Sao thế?' },
        { speaker: 'you', text: 'Do you want to see a movie?', vi: 'Đi xem phim không?' },
        { speaker: 'them', text: 'Sounds good! What time works for you?', vi: 'Được đó! Mấy giờ thì tiện cho bạn?' },
        { speaker: 'you', text: 'How about three? See you then!', vi: 'Ba giờ nhé? Hẹn gặp lúc đó!' },
      ],
    },
  },

  {
    id: 5, level: 'A2+', track: 'work', emoji: '🙋',
    title: 'Asking a Colleague for Help', titleVi: 'Nhờ đồng nghiệp giúp đỡ',
    situation: 'Bạn gặp khó với một việc và cần nhờ đồng nghiệp xem giúp.',
    dialogue: [
      { speaker: 'You', text: "Hey Ben, do you have a minute?", vi: 'Ben ơi, bạn có rảnh một phút không?' },
      { speaker: 'Ben', text: "Sure, what's going on?", vi: 'Có, chuyện gì vậy?' },
      { speaker: 'You', text: "I'm stuck on this report. Could you take a look at it?", vi: 'Mình bị kẹt với báo cáo này. Bạn xem giúp được không?' },
      { speaker: 'Ben', text: "Yeah, no problem. What's the issue?", vi: 'Ừ, không vấn đề gì. Vấn đề là gì?' },
      { speaker: 'You', text: "The numbers don't add up, and I'm not sure why.", vi: 'Các con số không khớp, và mình không rõ tại sao.' },
      { speaker: 'Ben', text: "Ah, you need to update the formula here. Let me show you.", vi: 'À, bạn cần cập nhật công thức chỗ này. Để mình chỉ.' },
      { speaker: 'You', text: "Oh, that makes sense. Thanks a lot, I owe you one!", vi: 'À, hiểu rồi. Cảm ơn nhiều, mình nợ bạn một lần!' },
    ],
    questions: [
      { q: 'What is the problem with the report?', options: ['It is too long', "The numbers don't match", 'It is late'], answer: 1 },
      { q: 'How does Ben fix it?', options: ['He rewrites it', 'He updates a formula', 'He asks the manager'], answer: 1 },
    ],
    connectedSpeech: [
      { written: 'Could you take a look at it?', spoken: '/ˈkʊ-dʒə-ˈteɪ-kə-ˈlʊ-kə-dɪt/', note: '"Could you" thành "could-ja"; "look at it" nối thành "loo-ka-dit".' },
      { written: 'Let me show you', spoken: '/ˈle-mi-ˈʃoʊ-jə/', note: '"Let me" thành "lemme", "you" đọc nhẹ thành "ya".' },
    ],
    chunks: [
      { en: 'Do you have a minute?', vi: 'Bạn có rảnh một phút không?', example: 'Sorry, do you have a minute? I have a quick question.', exampleVi: 'Xin lỗi, bạn rảnh một phút không? Mình có câu hỏi nhanh.' },
      { en: "I'm stuck on…", vi: 'Mình bị kẹt ở…', example: "I'm stuck on this bug.", exampleVi: 'Mình bị kẹt ở cái bug này.' },
      { en: 'Could you take a look at…?', vi: 'Bạn xem giúp… được không?', example: 'Could you take a look at my slides?', exampleVi: 'Bạn xem giúp slide của mình được không?' },
      { en: "What's the issue?", vi: 'Vấn đề là gì?', example: "Okay, so what's the issue exactly?", exampleVi: 'Ok, vậy chính xác vấn đề là gì?' },
      { en: "I'm not sure why.", vi: 'Mình không rõ tại sao.', example: "It stopped working, and I'm not sure why.", exampleVi: 'Nó ngừng chạy, mình không rõ tại sao.' },
      { en: 'Let me show you.', vi: 'Để mình chỉ cho.', example: "It's easy. Let me show you.", exampleVi: 'Dễ thôi. Để mình chỉ cho.' },
      { en: 'That makes sense.', vi: 'Hiểu rồi / Hợp lý.', example: 'Oh, that makes sense now.', exampleVi: 'À, giờ thì hiểu rồi.' },
      { en: 'I owe you one!', vi: 'Mình nợ bạn một lần!', example: 'Thanks for covering for me. I owe you one!', exampleVi: 'Cảm ơn đã làm thay mình. Mình nợ bạn một lần!' },
    ],
    drills: [
      { vi: 'Bạn có rảnh một phút không?', en: 'Do you have a minute?' },
      { vi: 'Mình bị kẹt ở cái bug này.', en: "I'm stuck on this bug." },
      { vi: 'Bạn xem giúp email này được không?', en: 'Could you take a look at this email?' },
      { vi: 'Nó không chạy, mình không rõ tại sao.', en: "It's not working, and I'm not sure why." },
      { vi: 'À, hiểu rồi.', en: 'Oh, that makes sense.' },
      { vi: 'Cảm ơn nhiều, mình nợ bạn một lần!', en: 'Thanks a lot, I owe you one!' },
    ],
    pattern: {
      frame: "I'm stuck on ___.", meaning: 'Mình bị kẹt ở ___.',
      slots: [
        { vi: 'Mình bị kẹt ở bài tập này.', en: "I'm stuck on this task." },
        { vi: 'Mình bị kẹt ở phần cuối.', en: "I'm stuck on the last part." },
        { vi: 'Mình bị kẹt ở bước hai.', en: "I'm stuck on step two." },
        { vi: 'Mình bị kẹt ở câu hỏi này.', en: "I'm stuck on this question." },
      ],
    },
    roleplay: {
      scenario: 'Bạn nhờ đồng nghiệp xem lại bài thuyết trình.',
      lines: [
        { speaker: 'you', text: 'Hi, do you have a minute?', vi: 'Chào, bạn có rảnh một phút không?' },
        { speaker: 'them', text: "Sure, what's going on?", vi: 'Có, chuyện gì vậy?' },
        { speaker: 'you', text: 'Could you take a look at my presentation?', vi: 'Bạn xem giúp bài thuyết trình của mình được không?' },
        { speaker: 'them', text: 'No problem. Send it over and I will check it after lunch.', vi: 'Không vấn đề. Gửi qua đi, mình xem sau bữa trưa.' },
        { speaker: 'you', text: 'Thanks a lot, I owe you one!', vi: 'Cảm ơn nhiều, mình nợ bạn một lần!' },
      ],
    },
  },

  {
    id: 6, level: 'A2+', track: 'life', emoji: '🛍️',
    title: 'Shopping & Returns', titleVi: 'Mua sắm và đổi trả',
    situation: 'Bạn mua áo bị sai cỡ và muốn đổi.',
    dialogue: [
      { speaker: 'Staff', text: "Hi, how can I help you?", vi: 'Chào bạn, mình giúp gì được?' },
      { speaker: 'You', text: "Hi, I bought this shirt yesterday, but it's too small.", vi: 'Chào, hôm qua mình mua cái áo này nhưng nó chật quá.' },
      { speaker: 'Staff', text: "No problem. Would you like to exchange it or get a refund?", vi: 'Không sao. Bạn muốn đổi hay hoàn tiền?' },
      { speaker: 'You', text: "I'd like to exchange it for a medium, if you have one.", vi: 'Mình muốn đổi sang cỡ M, nếu còn.' },
      { speaker: 'Staff', text: "Let me check. Do you have the receipt?", vi: 'Để mình kiểm tra. Bạn có hoá đơn không?' },
      { speaker: 'You', text: "Yes, here you go.", vi: 'Có, đây bạn.' },
      { speaker: 'Staff', text: "Great, here's a medium. Do you want to try it on?", vi: 'Tốt, đây là cỡ M. Bạn muốn thử không?' },
    ],
    questions: [
      { q: 'What is wrong with the shirt?', options: ['It is damaged', 'It is too small', 'Wrong color'], answer: 1 },
      { q: 'What does the customer want?', options: ['A refund', 'An exchange', 'A discount'], answer: 1 },
    ],
    connectedSpeech: [
      { written: 'try it on', spoken: '/ˈtraɪ-ɪ-dɑn/', note: '"it on" nối thành "i-don", chữ t đọc nhẹ như d.' },
      { written: "I'd like to", spoken: '/aɪd-ˈlaɪk-tə/', note: '"to" đọc nhẹ thành "tə", không nhấn.' },
    ],
    chunks: [
      { en: "It's too small / big.", vi: 'Nó chật / rộng quá.', example: 'These shoes are too big for me.', exampleVi: 'Đôi giày này rộng quá với mình.' },
      { en: "I'd like to exchange it.", vi: 'Mình muốn đổi nó.', example: "I'd like to exchange it for a different color.", exampleVi: 'Mình muốn đổi sang màu khác.' },
      { en: 'get a refund', vi: 'được hoàn tiền', example: 'Can I get a refund on this?', exampleVi: 'Mình được hoàn tiền món này không?' },
      { en: 'Do you have this in…?', vi: 'Cái này có cỡ/màu… không?', example: 'Do you have this in black?', exampleVi: 'Cái này có màu đen không?' },
      { en: 'Can I try it on?', vi: 'Mình thử được không?', example: 'This looks nice. Can I try it on?', exampleVi: 'Trông đẹp đấy. Mình thử được không?' },
      { en: 'Here you go.', vi: 'Đây bạn.', example: 'Your receipt? Here you go.', exampleVi: 'Hoá đơn hả? Đây bạn.' },
      { en: "I'm just looking.", vi: 'Mình chỉ xem thôi.', example: "Thanks, I'm just looking for now.", exampleVi: 'Cảm ơn, giờ mình chỉ xem thôi.' },
      { en: 'Is this on sale?', vi: 'Cái này có giảm giá không?', example: 'Excuse me, is this jacket on sale?', exampleVi: 'Xin lỗi, áo khoác này có giảm giá không?' },
    ],
    drills: [
      { vi: 'Cái áo này chật quá.', en: 'This shirt is too small.', accept: ["It's too small."] },
      { vi: 'Mình muốn đổi nó.', en: "I'd like to exchange it." },
      { vi: 'Cái này có màu trắng không?', en: 'Do you have this in white?' },
      { vi: 'Mình thử được không?', en: 'Can I try it on?' },
      { vi: 'Cảm ơn, mình chỉ xem thôi.', en: "Thanks, I'm just looking." },
      { vi: 'Mình được hoàn tiền không?', en: 'Can I get a refund?' },
    ],
    pattern: {
      frame: 'Do you have this in ___?', meaning: 'Cái này có ___ không?',
      slots: [
        { vi: 'Cái này có cỡ nhỏ không?', en: 'Do you have this in a small?', accept: ['Do you have this in small?'] },
        { vi: 'Cái này có màu xanh dương không?', en: 'Do you have this in blue?' },
        { vi: 'Cái này có cỡ lớn hơn không?', en: 'Do you have this in a bigger size?' },
        { vi: 'Cái này có màu khác không?', en: 'Do you have this in another color?', accept: ['Do you have this in a different color?'] },
      ],
    },
    roleplay: {
      scenario: 'Bạn mang giày đi đổi vì bị rộng.',
      lines: [
        { speaker: 'them', text: 'Hi there, can I help you?', vi: 'Chào bạn, mình giúp gì được?' },
        { speaker: 'you', text: "Hi, I bought these shoes, but they're too big.", vi: 'Chào, mình mua đôi giày này nhưng nó rộng quá.' },
        { speaker: 'them', text: 'Would you like a refund or an exchange?', vi: 'Bạn muốn hoàn tiền hay đổi?' },
        { speaker: 'you', text: "I'd like to exchange them for a smaller size.", vi: 'Mình muốn đổi sang cỡ nhỏ hơn.' },
        { speaker: 'them', text: 'Sure. Do you have the receipt?', vi: 'Được. Bạn có hoá đơn không?' },
        { speaker: 'you', text: 'Yes, here you go.', vi: 'Có, đây bạn.' },
      ],
    },
  },

  {
    id: 7, level: 'A2+', track: 'life', emoji: '🌤️',
    title: 'Talking About Your Weekend', titleVi: 'Kể về cuối tuần',
    situation: 'Bạn kể cho bạn bè nghe chuyến đi biển cuối tuần.',
    dialogue: [
      { speaker: 'Lily', text: "So, how was your weekend?", vi: 'Cuối tuần của bạn thế nào?' },
      { speaker: 'You', text: "It was great, actually. I went to the beach with some friends.", vi: 'Thật ra vui lắm. Mình đi biển với mấy người bạn.' },
      { speaker: 'Lily', text: "Oh nice! What was it like?", vi: 'Hay quá! Ở đó thế nào?' },
      { speaker: 'You', text: "The weather was perfect, and the seafood was amazing.", vi: 'Thời tiết tuyệt, hải sản thì ngon cực.' },
      { speaker: 'Lily', text: "Lucky you! Did you stay overnight?", vi: 'Sướng thế! Bạn có ở lại qua đêm không?' },
      { speaker: 'You', text: "Yeah, we stayed one night. I'm so tired now, though.", vi: 'Có, ở một đêm. Nhưng giờ mình mệt quá.' },
      { speaker: 'Lily', text: "I bet. It sounds like you had a good time.", vi: 'Chắc vậy rồi. Nghe có vẻ bạn đã chơi vui.' },
    ],
    questions: [
      { q: 'Where did the speaker go?', options: ['To the mountains', 'To the beach', 'To a concert'], answer: 1 },
      { q: 'How long did they stay?', options: ['A few hours', 'One night', 'A week'], answer: 1 },
    ],
    connectedSpeech: [
      { written: 'What was it like?', spoken: '/ˈwʌ-wə-zɪt-ˈlaɪk/', note: '"What was" nuốt chữ t: "wha-wuz", "was it" nối thành "wuh-zit".' },
      { written: 'had a good time', spoken: '/ˈhæ-də-ˈgʊd-taɪm/', note: '"had a" nối thành "ha-də"; "good time" mất chữ d.' },
    ],
    chunks: [
      { en: 'How was your weekend?', vi: 'Cuối tuần thế nào?', example: 'Hi! How was your weekend?', exampleVi: 'Chào! Cuối tuần thế nào?' },
      { en: 'It was great, actually.', vi: 'Thật ra rất vui.', example: 'It was great, actually. Really relaxing.', exampleVi: 'Thật ra rất vui. Rất thư giãn.' },
      { en: 'I went to … with…', vi: 'Mình đi … với…', example: 'I went to a concert with my sister.', exampleVi: 'Mình đi xem hoà nhạc với chị gái.' },
      { en: 'What was it like?', vi: 'Nó thế nào?', example: 'You went to Japan? What was it like?', exampleVi: 'Bạn đi Nhật à? Ở đó thế nào?' },
      { en: 'Lucky you!', vi: 'Sướng thế!', example: 'You have three days off? Lucky you!', exampleVi: 'Bạn được nghỉ ba ngày à? Sướng thế!' },
      { en: "I'm so tired now, though.", vi: 'Nhưng giờ mình mệt quá.', example: "It was fun. I'm so tired now, though.", exampleVi: 'Vui lắm. Nhưng giờ mệt quá.' },
      { en: 'I bet.', vi: 'Chắc vậy rồi.', example: 'I worked 12 hours. — I bet you are exhausted.', exampleVi: 'Mình làm 12 tiếng. — Chắc là mệt lắm.' },
      { en: 'had a good time', vi: 'đã chơi vui', example: 'We had a really good time.', exampleVi: 'Bọn mình đã chơi rất vui.' },
    ],
    drills: [
      { vi: 'Cuối tuần của bạn thế nào?', en: 'How was your weekend?' },
      { vi: 'Thật ra vui lắm.', en: 'It was great, actually.' },
      { vi: 'Mình đi Đà Lạt với gia đình.', en: 'I went to Da Lat with my family.' },
      { vi: 'Ở đó thế nào?', en: 'What was it like?' },
      { vi: 'Bọn mình đã chơi rất vui.', en: 'We had a really good time.', accept: ['We had a great time.'] },
      { vi: 'Sướng thế!', en: 'Lucky you!' },
    ],
    pattern: {
      frame: 'I went to ___ with ___.', meaning: 'Mình đi ___ với ___.',
      slots: [
        { vi: 'Mình đi xem phim với bạn gái.', en: 'I went to the movies with my girlfriend.', accept: ['I went to the cinema with my girlfriend.'] },
        { vi: 'Mình đi chợ với mẹ.', en: 'I went to the market with my mom.', accept: ['I went to the market with my mum.'] },
        { vi: 'Mình đi phòng gym với đồng nghiệp.', en: 'I went to the gym with a colleague.' },
        { vi: 'Mình đi một quán bar mới với bạn bè.', en: 'I went to a new bar with my friends.', accept: ['I went to a new bar with some friends.'] },
      ],
    },
    roleplay: {
      scenario: 'Đồng nghiệp hỏi về cuối tuần của bạn.',
      lines: [
        { speaker: 'them', text: 'Hey, how was your weekend?', vi: 'Này, cuối tuần thế nào?' },
        { speaker: 'you', text: 'It was great, actually. I went hiking with friends.', vi: 'Thật ra vui lắm. Mình đi leo núi với bạn.' },
        { speaker: 'them', text: 'Oh nice! What was it like?', vi: 'Hay quá! Thế nào?' },
        { speaker: 'you', text: "Beautiful, but I'm so tired now, though.", vi: 'Đẹp lắm, nhưng giờ mình mệt quá.' },
        { speaker: 'them', text: 'I bet! Sounds fun.', vi: 'Chắc vậy rồi! Nghe vui đấy.' },
      ],
    },
  },

  {
    id: 8, level: 'A2+', track: 'work', emoji: '⏰',
    title: 'Running Late & Rescheduling', titleVi: 'Báo trễ và dời lịch',
    situation: 'Bạn bị kẹt xe và phải báo trễ họp, rồi xin dời lịch.',
    dialogue: [
      { speaker: 'You', text: "Hi Anna, I'm so sorry, I'm running a bit late.", vi: 'Chào Anna, xin lỗi nhé, mình đến trễ một chút.' },
      { speaker: 'Anna', text: "No worries. Is everything okay?", vi: 'Không sao. Mọi chuyện ổn chứ?' },
      { speaker: 'You', text: "Yeah, I'm stuck in traffic. I'll be there in about fifteen minutes.", vi: 'Ổn, mình bị kẹt xe. Khoảng mười lăm phút nữa mình tới.' },
      { speaker: 'Anna', text: "Hmm, I have another meeting at ten. Can we push it to this afternoon?", vi: 'Hmm, mình có cuộc họp khác lúc mười giờ. Mình dời sang chiều nay được không?' },
      { speaker: 'You', text: "Sure, that works for me. How about two o'clock?", vi: 'Được, mình ổn. Hai giờ thì sao?' },
      { speaker: 'Anna', text: "Two is fine. I'll send you an updated invite.", vi: 'Hai giờ được. Mình sẽ gửi lại lịch mới.' },
      { speaker: 'You', text: "Thanks for understanding. See you then.", vi: 'Cảm ơn bạn đã thông cảm. Hẹn gặp lúc đó.' },
    ],
    questions: [
      { q: 'Why is the speaker late?', options: ['Overslept', 'Stuck in traffic', 'Missed the train'], answer: 1 },
      { q: 'When is the new meeting time?', options: ['10 a.m.', '2 p.m.', 'Tomorrow'], answer: 1 },
    ],
    connectedSpeech: [
      { written: "I'm running a bit late", spoken: '/aɪm-ˈrʌ-nɪn-ə-bɪ-ˈleɪt/', note: '"running" thành "runnin\'", "bit late" nuốt chữ t đầu.' },
      { written: 'push it to', spoken: '/ˈpʊ-ʃɪt-tə/', note: '"push it" nối liền thành "pu-shit"; "to" đọc nhẹ.' },
    ],
    chunks: [
      { en: "I'm running a bit late.", vi: 'Mình đến trễ một chút.', example: "Sorry, I'm running a bit late. Start without me.", exampleVi: 'Xin lỗi, mình trễ chút. Cứ bắt đầu trước nhé.' },
      { en: "I'm stuck in traffic.", vi: 'Mình bị kẹt xe.', example: "I'm stuck in traffic on the highway.", exampleVi: 'Mình bị kẹt xe trên cao tốc.' },
      { en: "I'll be there in…", vi: '… nữa mình tới.', example: "I'll be there in ten minutes.", exampleVi: 'Mười phút nữa mình tới.' },
      { en: 'Can we push it to…?', vi: 'Mình dời sang… được không?', example: 'Can we push it to Thursday?', exampleVi: 'Mình dời sang thứ Năm được không?' },
      { en: 'That works for me.', vi: 'Mình ổn với giờ đó.', example: 'Three p.m.? That works for me.', exampleVi: 'Ba giờ chiều à? Mình ổn.' },
      { en: 'No worries.', vi: 'Không sao đâu.', example: "Sorry I'm late! — No worries.", exampleVi: 'Xin lỗi mình trễ! — Không sao đâu.' },
      { en: "I'll send you an updated invite.", vi: 'Mình sẽ gửi lại lịch mới.', example: 'Okay, I\'ll send you an updated invite now.', exampleVi: 'Ok, mình gửi lại lịch mới ngay.' },
      { en: 'Thanks for understanding.', vi: 'Cảm ơn đã thông cảm.', example: "I can't make it today. Thanks for understanding.", exampleVi: 'Hôm nay mình không đến được. Cảm ơn đã thông cảm.' },
    ],
    drills: [
      { vi: 'Xin lỗi, mình đến trễ một chút.', en: "Sorry, I'm running a bit late." },
      { vi: 'Mình bị kẹt xe.', en: "I'm stuck in traffic." },
      { vi: 'Mười phút nữa mình tới.', en: "I'll be there in ten minutes." },
      { vi: 'Mình dời sang ngày mai được không?', en: 'Can we push it to tomorrow?' },
      { vi: 'Giờ đó mình ổn.', en: 'That works for me.' },
      { vi: 'Cảm ơn bạn đã thông cảm.', en: 'Thanks for understanding.' },
    ],
    pattern: {
      frame: 'Can we push it to ___?', meaning: 'Mình dời sang ___ được không?',
      slots: [
        { vi: 'Mình dời sang thứ Hai được không?', en: 'Can we push it to Monday?' },
        { vi: 'Mình dời sang tuần sau được không?', en: 'Can we push it to next week?' },
        { vi: 'Mình dời sang bốn giờ được không?', en: 'Can we push it to four?', accept: ["Can we push it to four o'clock?"] },
        { vi: 'Mình dời sang sau bữa trưa được không?', en: 'Can we push it to after lunch?' },
      ],
    },
    roleplay: {
      scenario: 'Bạn gọi cho đồng nghiệp vì trễ họp.',
      lines: [
        { speaker: 'you', text: "Hi, I'm so sorry, I'm running a bit late.", vi: 'Chào, xin lỗi nhé, mình trễ một chút.' },
        { speaker: 'them', text: 'No worries. When can you get here?', vi: 'Không sao. Khi nào bạn tới được?' },
        { speaker: 'you', text: "I'm stuck in traffic. I'll be there in twenty minutes.", vi: 'Mình kẹt xe. Hai mươi phút nữa mình tới.' },
        { speaker: 'them', text: "That's a bit tight for me. Can we do it tomorrow instead?", vi: 'Hơi gấp với mình. Mai được không?' },
        { speaker: 'you', text: 'Sure, that works for me. Thanks for understanding.', vi: 'Được, mình ổn. Cảm ơn bạn đã thông cảm.' },
      ],
    },
  },

  {
    id: 9, level: 'A2+', track: 'life', emoji: '💊',
    title: 'At the Pharmacy', titleVi: 'Ở hiệu thuốc',
    situation: 'Bạn bị cảm và hỏi mua thuốc ở hiệu thuốc.',
    dialogue: [
      { speaker: 'Pharmacist', text: "Hello, what can I do for you?", vi: 'Xin chào, tôi giúp gì được?' },
      { speaker: 'You', text: "Hi, I've got a sore throat and a bit of a fever.", vi: 'Chào, tôi bị đau họng và hơi sốt.' },
      { speaker: 'Pharmacist', text: "I see. How long have you had it?", vi: 'Tôi hiểu. Bạn bị bao lâu rồi?' },
      { speaker: 'You', text: "Since yesterday. I feel pretty awful.", vi: 'Từ hôm qua. Tôi thấy khá mệt.' },
      { speaker: 'Pharmacist', text: "Are you allergic to anything?", vi: 'Bạn có dị ứng với thứ gì không?' },
      { speaker: 'You', text: "Not that I know of.", vi: 'Theo tôi biết thì không.' },
      { speaker: 'Pharmacist', text: "Okay, take two of these every six hours, after meals.", vi: 'Được, uống hai viên này mỗi sáu tiếng, sau khi ăn.' },
      { speaker: 'You', text: "Every six hours, after meals. Got it, thank you.", vi: 'Mỗi sáu tiếng, sau khi ăn. Hiểu rồi, cảm ơn.' },
    ],
    questions: [
      { q: 'What are the symptoms?', options: ['Headache and cough', 'Sore throat and fever', 'Stomach ache'], answer: 1 },
      { q: 'How often should they take the medicine?', options: ['Every six hours', 'Once a day', 'Before bed'], answer: 0 },
    ],
    connectedSpeech: [
      { written: "I've got a", spoken: '/aɪv-ˈgɑ-də/', note: '"got a" thành "ga-də" — rất hay gặp: "I\'ve got a cold".' },
      { written: 'Not that I know of', spoken: '/ˈnɑ-ðə-daɪ-ˈnoʊ-əv/', note: '"that I" nối thành "tha-dai", "of" đọc nhẹ "əv".' },
    ],
    chunks: [
      { en: "I've got a sore throat.", vi: 'Mình bị đau họng.', example: "I've got a sore throat from talking all day.", exampleVi: 'Mình bị đau họng vì nói cả ngày.' },
      { en: 'a bit of a fever', vi: 'hơi sốt', example: 'I think I have a bit of a fever.', exampleVi: 'Mình nghĩ mình hơi sốt.' },
      { en: 'I feel pretty awful.', vi: 'Mình thấy khá mệt / tệ.', example: "I didn't sleep. I feel pretty awful.", exampleVi: 'Mình không ngủ được. Thấy khá tệ.' },
      { en: 'Since yesterday.', vi: 'Từ hôm qua.', example: "I've had this headache since yesterday.", exampleVi: 'Mình bị đau đầu từ hôm qua.' },
      { en: 'Are you allergic to…?', vi: 'Bạn có dị ứng… không?', example: "I'm allergic to penicillin.", exampleVi: 'Mình dị ứng penicillin.' },
      { en: 'Not that I know of.', vi: 'Theo mình biết thì không.', example: 'Any allergies? — Not that I know of.', exampleVi: 'Có dị ứng gì không? — Theo mình biết thì không.' },
      { en: 'Do I need a prescription?', vi: 'Có cần đơn thuốc không?', example: 'Do I need a prescription for this?', exampleVi: 'Thuốc này có cần đơn không?' },
      { en: 'something for…', vi: 'thuốc gì đó cho…', example: 'Do you have something for a headache?', exampleVi: 'Có thuốc gì cho đau đầu không?' },
    ],
    drills: [
      { vi: 'Mình bị đau họng.', en: "I've got a sore throat.", accept: ['I have a sore throat.'] },
      { vi: 'Mình hơi sốt.', en: 'I have a bit of a fever.', accept: ["I've got a bit of a fever."] },
      { vi: 'Bị từ hôm qua.', en: 'Since yesterday.' },
      { vi: 'Có thuốc gì cho đau đầu không?', en: 'Do you have something for a headache?' },
      { vi: 'Theo mình biết thì không.', en: 'Not that I know of.' },
      { vi: 'Có cần đơn thuốc không?', en: 'Do I need a prescription?' },
    ],
    pattern: {
      frame: 'Do you have something for ___?', meaning: 'Có thuốc gì cho ___ không?',
      slots: [
        { vi: 'Có thuốc gì cho ho không?', en: 'Do you have something for a cough?' },
        { vi: 'Có thuốc gì cho đau bụng không?', en: 'Do you have something for a stomach ache?' },
        { vi: 'Có thuốc gì cho muỗi đốt không?', en: 'Do you have something for mosquito bites?' },
        { vi: 'Có thuốc gì cho say xe không?', en: 'Do you have something for motion sickness?', accept: ['Do you have something for car sickness?'] },
      ],
    },
    roleplay: {
      scenario: 'Bạn bị đau đầu và hỏi dược sĩ.',
      lines: [
        { speaker: 'them', text: 'Hi, what can I do for you?', vi: 'Chào, tôi giúp gì được?' },
        { speaker: 'you', text: 'Do you have something for a headache?', vi: 'Có thuốc gì cho đau đầu không?' },
        { speaker: 'them', text: 'Sure. How long have you had it?', vi: 'Có. Bạn bị bao lâu rồi?' },
        { speaker: 'you', text: 'Since yesterday. I feel pretty awful.', vi: 'Từ hôm qua. Mình thấy khá tệ.' },
        { speaker: 'them', text: 'Are you allergic to anything?', vi: 'Bạn có dị ứng gì không?' },
        { speaker: 'you', text: 'Not that I know of.', vi: 'Theo mình biết thì không.' },
      ],
    },
  },

  {
    id: 10, level: 'A2+', track: 'work', emoji: '📞',
    title: 'Phone & Video Calls', titleVi: 'Gọi điện và họp online',
    situation: 'Cuộc gọi bị rớt tiếng, bạn cần xin nói lại và xác nhận thông tin.',
    dialogue: [
      { speaker: 'Raj', text: "Hi, this is Raj from the design team. Can you hear me okay?", vi: 'Chào, mình là Raj bên team thiết kế. Bạn nghe rõ không?' },
      { speaker: 'You', text: "Sorry, you're breaking up a bit. Could you say that again?", vi: 'Xin lỗi, tiếng bạn bị rè. Bạn nói lại được không?' },
      { speaker: 'Raj', text: "Sure. I'm calling about the new website.", vi: 'Được. Mình gọi về trang web mới.' },
      { speaker: 'You', text: "Ah, got it. Sorry, could you speak a little slower?", vi: 'À, hiểu rồi. Xin lỗi, bạn nói chậm lại một chút được không?' },
      { speaker: 'Raj', text: "Of course. We need your feedback by Friday.", vi: 'Tất nhiên. Bọn mình cần phản hồi của bạn trước thứ Sáu.' },
      { speaker: 'You', text: "Just to confirm, by this Friday?", vi: 'Để xác nhận lại, là thứ Sáu này đúng không?' },
      { speaker: 'Raj', text: "Exactly. I'll email you the details.", vi: 'Đúng vậy. Mình sẽ gửi email chi tiết.' },
    ],
    questions: [
      { q: 'What is the call about?', options: ['A new website', 'A new hire', 'A budget'], answer: 0 },
      { q: 'When is the feedback needed?', options: ['Today', 'By Friday', 'Next month'], answer: 1 },
    ],
    connectedSpeech: [
      { written: 'Can you hear me', spoken: '/kə-njə-ˈhɪr-mi/', note: '"Can you" thành "can-ya"; nhấn vào "hear".' },
      { written: 'Could you say that again?', spoken: '/ˈkʊ-dʒə-ˈseɪ-ðæ-də-ˈgen/', note: '"that again" nối thành "tha-də-gen".' },
    ],
    chunks: [
      { en: 'This is … from…', vi: 'Mình là … bên…', example: 'Hi, this is Linh from accounting.', exampleVi: 'Chào, mình là Linh bên kế toán.' },
      { en: 'Can you hear me okay?', vi: 'Bạn nghe rõ không?', example: 'Hello? Can you hear me okay?', exampleVi: 'Alo? Bạn nghe rõ không?' },
      { en: "You're breaking up.", vi: 'Tiếng bạn bị rè / mất.', example: "Sorry, you're breaking up. Can you call back?", exampleVi: 'Xin lỗi, tiếng bị rè. Bạn gọi lại được không?' },
      { en: 'Could you say that again?', vi: 'Bạn nói lại được không?', example: 'Sorry, could you say that again?', exampleVi: 'Xin lỗi, bạn nói lại được không?' },
      { en: 'Could you speak a little slower?', vi: 'Bạn nói chậm lại chút được không?', example: "Could you speak a little slower? I'm taking notes.", exampleVi: 'Bạn nói chậm lại chút được không? Mình đang ghi chép.' },
      { en: "I'm calling about…", vi: 'Mình gọi về việc…', example: "I'm calling about the invoice.", exampleVi: 'Mình gọi về hoá đơn.' },
      { en: 'Just to confirm, …?', vi: 'Để xác nhận lại, …?', example: 'Just to confirm, the meeting is at 3?', exampleVi: 'Xác nhận lại nhé, họp lúc 3 giờ đúng không?' },
      { en: "You're on mute.", vi: 'Bạn đang tắt mic.', example: "Sorry, I think you're on mute.", exampleVi: 'Xin lỗi, hình như bạn đang tắt mic.' },
    ],
    drills: [
      { vi: 'Chào, mình là Nam bên team IT.', en: 'Hi, this is Nam from the IT team.' },
      { vi: 'Bạn nghe rõ không?', en: 'Can you hear me okay?' },
      { vi: 'Xin lỗi, bạn nói lại được không?', en: 'Sorry, could you say that again?' },
      { vi: 'Hình như bạn đang tắt mic.', en: "I think you're on mute." },
      { vi: 'Bạn nói chậm lại chút được không?', en: 'Could you speak a little slower?' },
      { vi: 'Để xác nhận lại, hạn là thứ Sáu đúng không?', en: 'Just to confirm, the deadline is Friday?' },
    ],
    pattern: {
      frame: "I'm calling about ___.", meaning: 'Mình gọi về việc ___.',
      slots: [
        { vi: 'Mình gọi về đơn hàng của mình.', en: "I'm calling about my order." },
        { vi: 'Mình gọi về cuộc họp ngày mai.', en: "I'm calling about tomorrow's meeting.", accept: ["I'm calling about the meeting tomorrow."] },
        { vi: 'Mình gọi về vị trí tuyển dụng.', en: "I'm calling about the job opening.", accept: ["I'm calling about the job position."] },
        { vi: 'Mình gọi về lịch hẹn của mình.', en: "I'm calling about my appointment." },
      ],
    },
    roleplay: {
      scenario: 'Bạn nhận cuộc gọi từ khách hàng nhưng mạng yếu.',
      lines: [
        { speaker: 'them', text: "Hi, this is Sarah from ABC. I'm calling about the contract.", vi: 'Chào, mình là Sarah bên ABC. Mình gọi về hợp đồng.' },
        { speaker: 'you', text: "Sorry, you're breaking up. Could you say that again?", vi: 'Xin lỗi, tiếng bị rè. Bạn nói lại được không?' },
        { speaker: 'them', text: 'Sure. We need it signed by Monday.', vi: 'Được. Bọn mình cần ký trước thứ Hai.' },
        { speaker: 'you', text: 'Just to confirm, by next Monday?', vi: 'Xác nhận lại nhé, trước thứ Hai tới?' },
        { speaker: 'them', text: "Yes, that's right.", vi: 'Đúng rồi.' },
      ],
    },
  },
];
