export type ChallengeType = 'fill-blank' | 'listen-choose' | 'choose-slang';

export interface ChallengeOption {
  id: string;
  text: string;
}

export interface DailyChallenge {
  id: string;
  type: ChallengeType;
  instruction: string;
  audioText?: string;
  sentence?: string;
  question: string;
  options: ChallengeOption[];
  correctId: string;
  explanation: string;
  xpReward: number;
}

export const CHALLENGE_POOL: DailyChallenge[] = [
  // ─── Fill-blank ────────────────────────────────────────────────────
  {
    id: 'fb-1',
    type: 'fill-blank',
    instruction: 'Fill in the blank with the right word',
    sentence: "Sorry, I'm gonna have to ___ on our call — something urgent came up.",
    question: 'Choose the correct word:',
    options: [
      { id: 'a', text: 'bail' },
      { id: 'b', text: 'leave' },
      { id: 'c', text: 'exit' },
      { id: 'd', text: 'drop' },
    ],
    correctId: 'a',
    explanation: '"Bail on something" = cancel plans suddenly. Very common in workplace English. "I have to bail" = I need to drop out.',
    xpReward: 20,
  },
  {
    id: 'fb-2',
    type: 'fill-blank',
    instruction: 'Fill in the blank with the right word',
    sentence: "Can you ___ me up to speed? I missed the standup this morning.",
    question: 'Choose the correct word:',
    options: [
      { id: 'a', text: 'get' },
      { id: 'b', text: 'bring' },
      { id: 'c', text: 'put' },
      { id: 'd', text: 'make' },
    ],
    correctId: 'b',
    explanation: '"Bring someone up to speed" = fill them in on what they missed. "Fill someone in" means the same thing. Both are extremely common.',
    xpReward: 20,
  },
  {
    id: 'fb-3',
    type: 'fill-blank',
    instruction: 'Fill in the blank with the right word',
    sentence: "I'm completely ___ on this bug — no idea what's causing it.",
    question: 'Choose the correct word:',
    options: [
      { id: 'a', text: 'lost' },
      { id: 'b', text: 'stuck' },
      { id: 'c', text: 'stumped' },
      { id: 'd', text: 'confused' },
    ],
    correctId: 'c',
    explanation: '"Stumped" = completely out of ideas on how to proceed. Stronger than "confused" or "stuck" — it implies you\'ve tried everything and still can\'t figure it out.',
    xpReward: 20,
  },
  {
    id: 'fb-4',
    type: 'fill-blank',
    instruction: 'Fill in the blank with the right word',
    sentence: "Let's ___ this to next sprint — we're already overloaded this week.",
    question: 'Choose the correct word:',
    options: [
      { id: 'a', text: 'table' },
      { id: 'b', text: 'push' },
      { id: 'c', text: 'punt' },
      { id: 'd', text: 'move' },
    ],
    correctId: 'c',
    explanation: '"Punt" = kick the decision down the road, defer it for now. From American football. "Table it" (US usage) also means to postpone.',
    xpReward: 20,
  },
  {
    id: 'fb-5',
    type: 'fill-blank',
    instruction: 'Fill in the blank with the right word',
    sentence: "The meeting ___ into a two-hour debate about naming conventions.",
    question: 'Choose the correct word:',
    options: [
      { id: 'a', text: 'turned' },
      { id: 'b', text: 'devolved' },
      { id: 'c', text: 'went' },
      { id: 'd', text: 'spiraled' },
    ],
    correctId: 'd',
    explanation: '"Spiral into" = escalate out of control. "The situation spiraled" = things got progressively worse in ways nobody could contain.',
    xpReward: 20,
  },
  {
    id: 'fb-6',
    type: 'fill-blank',
    instruction: 'Fill in the blank with the right word',
    sentence: "She really ___ it this sprint — five features shipped, zero regressions.",
    question: 'Choose the correct word:',
    options: [
      { id: 'a', text: 'nailed' },
      { id: 'b', text: 'crushed' },
      { id: 'c', text: 'owned' },
      { id: 'd', text: 'killed' },
    ],
    correctId: 'b',
    explanation: '"Crush it" = perform exceptionally well. "Nail it", "kill it", "own it" are all similar — all four work here, but "crushed it" flows most naturally in context.',
    xpReward: 20,
  },
  {
    id: 'fb-7',
    type: 'fill-blank',
    instruction: 'Fill in the blank with the right word',
    sentence: "We went down a ___ debugging that memory leak and lost the whole afternoon.",
    question: 'Choose the correct word:',
    options: [
      { id: 'a', text: 'dead end' },
      { id: 'b', text: 'black hole' },
      { id: 'c', text: 'deep dive' },
      { id: 'd', text: 'rabbit hole' },
    ],
    correctId: 'd',
    explanation: '"Rabbit hole" = going deeper into an investigation than planned, often losing track of time. "Deep dive" = deliberately focused research — more intentional.',
    xpReward: 20,
  },
  {
    id: 'fb-8',
    type: 'fill-blank',
    instruction: 'Fill in the blank with the right word',
    sentence: "That module is a complete ___ — nobody on the team knows how it actually works.",
    question: 'Choose the correct word:',
    options: [
      { id: 'a', text: 'mess' },
      { id: 'b', text: 'nightmare' },
      { id: 'c', text: 'black box' },
      { id: 'd', text: 'mystery' },
    ],
    correctId: 'c',
    explanation: '"Black box" = a system nobody truly understands internally — you only know the inputs and outputs. Standard terminology in tech.',
    xpReward: 20,
  },

  // ─── Listen-choose ─────────────────────────────────────────────────
  {
    id: 'lc-1',
    type: 'listen-choose',
    instruction: 'Listen and answer the question',
    audioText: "Heads up — the deploy today might take the site down for a few minutes. We've got some breaking changes going in.",
    question: "What is the speaker warning about?",
    options: [
      { id: 'a', text: 'The server is completely down' },
      { id: 'b', text: "Today's deploy has breaking changes and may cause brief downtime" },
      { id: 'c', text: 'The deploy has been cancelled' },
      { id: 'd', text: 'The site is currently broken' },
    ],
    correctId: 'b',
    explanation: '"Heads up" = a friendly advance warning. "Breaking changes" = changes that aren\'t backward-compatible with older versions — always worth flagging before any update.',
    xpReward: 25,
  },
  {
    id: 'lc-2',
    type: 'listen-choose',
    instruction: 'Listen and answer the question',
    audioText: "The client keeps moving the goalposts — last week it was a simple dashboard, now they want real-time analytics too.",
    question: "Why is the speaker frustrated?",
    options: [
      { id: 'a', text: "The client doesn't know how to use the dashboard" },
      { id: 'b', text: 'The client keeps changing the requirements' },
      { id: 'c', text: 'The project is too complex' },
      { id: 'd', text: 'The client asked for too many features from the start' },
    ],
    correctId: 'b',
    explanation: '"Move the goalposts" = shift requirements or success criteria mid-project while others are trying to meet them. Frustrating by definition.',
    xpReward: 25,
  },
  {
    id: 'lc-3',
    type: 'listen-choose',
    instruction: 'Listen and answer the question',
    audioText: "I'm swamped right now. Can we push our sync to tomorrow morning instead?",
    question: 'What does "swamped" tell us about the speaker?',
    options: [
      { id: 'a', text: "They're literally in water" },
      { id: 'b', text: "They're completely overwhelmed with work" },
      { id: 'c', text: 'They forgot about the meeting' },
      { id: 'd', text: 'They want to cancel the meeting' },
    ],
    correctId: 'b',
    explanation: '"Swamped" = overwhelmed with work. A casual way to say extremely busy. "Sync" here = a quick meeting to align on updates.',
    xpReward: 25,
  },
  {
    id: 'lc-4',
    type: 'listen-choose',
    instruction: 'Listen and answer the question',
    audioText: "Nice work on the PR. Left a few nits — nothing blocking. LGTM overall.",
    question: "What does this code review feedback mean?",
    options: [
      { id: 'a', text: 'PR is rejected and needs a redo' },
      { id: 'b', text: "Reviewer hasn't finished reading" },
      { id: 'c', text: 'PR is approved with just a few minor style comments' },
      { id: 'd', text: 'PR has a serious bug' },
    ],
    correctId: 'c',
    explanation: '"Nits" (nitpicks) = minor style suggestions that don\'t affect functionality. "Nothing blocking" = nothing preventing the merge. "LGTM" = Looks Good To Me = approved.',
    xpReward: 25,
  },
  {
    id: 'lc-5',
    type: 'listen-choose',
    instruction: 'Listen and answer the question',
    audioText: "Let's not reinvent the wheel here — there are plenty of open-source libraries that already handle this perfectly.",
    question: "What is the speaker suggesting?",
    options: [
      { id: 'a', text: 'Build a custom solution from scratch to learn' },
      { id: 'b', text: 'Use an existing library instead of writing it ourselves' },
      { id: 'c', text: 'Contribute to open source' },
      { id: 'd', text: 'Avoid third-party libraries' },
    ],
    correctId: 'b',
    explanation: '"Reinvent the wheel" = rebuild something that\'s already solved well. "Don\'t reinvent the wheel" = don\'t waste effort building what already exists and works.',
    xpReward: 25,
  },
  {
    id: 'lc-6',
    type: 'listen-choose',
    instruction: 'Listen and answer the question',
    audioText: "This is a blocker for the whole team. We can't ship v2 without getting this sorted first.",
    question: 'What does "blocker" mean in this context?',
    options: [
      { id: 'a', text: 'A code design pattern' },
      { id: 'b', text: 'An issue preventing the entire team from moving forward' },
      { id: 'c', text: 'A difficult team member' },
      { id: 'd', text: 'A database error' },
    ],
    correctId: 'b',
    explanation: '"Blocker" = a serious issue that stops progress. Common in standups: "Any blockers today?" or "I have a blocker I need help with."',
    xpReward: 25,
  },
  {
    id: 'lc-7',
    type: 'listen-choose',
    instruction: 'Listen and answer the question',
    audioText: "Can you give me a ballpark figure for how long the auth refactor will take?",
    question: "What is the person asking for?",
    options: [
      { id: 'a', text: 'An exact hour-by-hour estimate' },
      { id: 'b', text: "A rough estimate — doesn't need to be precise" },
      { id: 'c', text: 'The cost of the refactor' },
      { id: 'd', text: 'A detailed written plan' },
    ],
    correctId: 'b',
    explanation: '"Ballpark figure" = a rough estimate, not an exact number. "In the ballpark of 2 weeks" = approximately 2 weeks, give or take.',
    xpReward: 25,
  },
  {
    id: 'lc-8',
    type: 'listen-choose',
    instruction: 'Listen and answer the question',
    audioText: "I've been heads-down all week on the auth module. Just came up for air this morning.",
    question: "What has the speaker been doing all week?",
    options: [
      { id: 'a', text: 'Working underwater' },
      { id: 'b', text: 'Avoiding meetings' },
      { id: 'c', text: 'Deeply focused on one task, barely doing anything else' },
      { id: 'd', text: 'Running multiple projects in parallel' },
    ],
    correctId: 'c',
    explanation: '"Heads-down" = deeply focused, not distracted. "Come up for air" = briefly surfacing after intense work — like a diver coming up to breathe.',
    xpReward: 25,
  },

  // ─── Choose-slang ──────────────────────────────────────────────────
  {
    id: 'cs-1',
    type: 'choose-slang',
    instruction: 'What does the highlighted idiom mean?',
    audioText: "I'm gonna take a stab at fixing this before the standup.",
    question: 'What does "take a stab at" mean?',
    options: [
      { id: 'a', text: 'Try to do something' },
      { id: 'b', text: 'Delete something' },
      { id: 'c', text: 'Attack someone' },
      { id: 'd', text: 'Test something' },
    ],
    correctId: 'a',
    explanation: '"Take a stab at" = attempt something, especially when you\'re not sure of the outcome. "Let me take a stab at this bug" = let me give it a try and see.',
    xpReward: 25,
  },
  {
    id: 'cs-2',
    type: 'choose-slang',
    instruction: 'What does the highlighted idiom mean?',
    audioText: "This sprint has been a complete dumpster fire — three devs out sick and prod went down twice.",
    question: 'What does "dumpster fire" describe?',
    options: [
      { id: 'a', text: 'An actual fire' },
      { id: 'b', text: 'A missed deadline' },
      { id: 'c', text: "A chaotic situation that's failing on multiple fronts" },
      { id: 'd', text: 'Having too much code to delete' },
    ],
    correctId: 'c',
    explanation: '"Dumpster fire" = a chaotic, disastrous situation where multiple things go wrong at once. Strong slang — best used with close teammates.',
    xpReward: 25,
  },
  {
    id: 'cs-3',
    type: 'choose-slang',
    instruction: 'What does the highlighted idiom mean?',
    audioText: "Let's circle back on the deployment strategy after the release — too much on our plate right now.",
    question: 'What does "circle back" mean?',
    options: [
      { id: 'a', text: 'Go in circles without deciding' },
      { id: 'b', text: 'Return to this topic later' },
      { id: 'c', text: 'Cancel the discussion' },
      { id: 'd', text: 'Start over from scratch' },
    ],
    correctId: 'b',
    explanation: '"Circle back" = revisit this topic when there\'s more time or information. Very common in professional English, especially during meetings.',
    xpReward: 25,
  },
  {
    id: 'cs-4',
    type: 'choose-slang',
    instruction: 'What does the highlighted idiom mean?',
    audioText: "We need to get our ducks in a row before the investor demo next week.",
    question: 'What does "get our ducks in a row" mean?',
    options: [
      { id: 'a', text: 'Organize a nature presentation' },
      { id: 'b', text: 'Onboard new team members' },
      { id: 'c', text: 'Get fully prepared, have everything organized' },
      { id: 'd', text: 'Schedule all meetings' },
    ],
    correctId: 'c',
    explanation: '"Get your ducks in a row" = be fully prepared and organized before something important. Common before demos, presentations, or major launches.',
    xpReward: 25,
  },
  {
    id: 'cs-5',
    type: 'choose-slang',
    instruction: 'What does the highlighted idiom mean?',
    audioText: "I'll ping you when the build finishes — should be about 10 minutes.",
    question: 'What does "ping" mean in this sentence?',
    options: [
      { id: 'a', text: 'Test a server connection' },
      { id: 'b', text: 'Make a phone call' },
      { id: 'c', text: 'Send a quick message or notification' },
      { id: 'd', text: 'Send a formal email' },
    ],
    correctId: 'c',
    explanation: '"Ping" = send a quick message or mention someone. "Ping me when you\'re done" = message me when you finish. Extremely common on Slack and Teams.',
    xpReward: 25,
  },
  {
    id: 'cs-6',
    type: 'choose-slang',
    instruction: 'What does the highlighted idiom mean?',
    audioText: "That refactor is totally out of scope for this sprint. Let's throw it in the backlog.",
    question: 'What does "out of scope" mean?',
    options: [
      { id: 'a', text: 'Too difficult to implement' },
      { id: 'b', text: 'Outside the agreed scope of work' },
      { id: 'c', text: "Not in the codebase" },
      { id: 'd', text: "Outside the team's expertise" },
    ],
    correctId: 'b',
    explanation: '"In scope / out of scope" = within or outside the agreed boundaries of the current sprint or project. Core vocabulary in any agile workflow.',
    xpReward: 25,
  },
  {
    id: 'cs-7',
    type: 'choose-slang',
    instruction: 'What does the highlighted idiom mean?',
    audioText: "Let's do a quick sanity check before we push this to prod.",
    question: 'What is a "sanity check"?',
    options: [
      { id: 'a', text: 'A mental health check for the team' },
      { id: 'b', text: 'A formal security audit' },
      { id: 'c', text: 'A quick check that everything works as expected' },
      { id: 'd', text: 'Running the full regression test suite' },
    ],
    correctId: 'c',
    explanation: '"Sanity check" = a quick verification that the logic or result seems right before continuing. Informal — basically "does this make sense?"',
    xpReward: 25,
  },
  {
    id: 'cs-8',
    type: 'choose-slang',
    instruction: 'What does the highlighted idiom mean?',
    audioText: "She's really in the zone today — knocked out half the backlog before noon.",
    question: 'What does "in the zone" mean?',
    options: [
      { id: 'a', text: 'Working in a specific area of the office' },
      { id: 'b', text: 'In a state of deep focus and high productivity' },
      { id: 'c', text: 'Working overtime' },
      { id: 'd', text: 'Working on the most important tasks' },
    ],
    correctId: 'b',
    explanation: '"In the zone" = a state of deep focus and flow where you\'re highly productive and lose track of time. Also called "flow state" in psychology.',
    xpReward: 25,
  },
];
