import type { DayLesson } from '@/types';

export const lessons: DayLesson[] = [
  {
    day: 1,
    title: 'Hello & Introductions',
    subtitle: 'Chào hỏi và tự giới thiệu',
    theme: 'office',
    emoji: '👋',
    gradient: ['#7C3AED', '#6366F1'],
    xpReward: 100,
    vocabulary: [
      { word: 'Hello', phonetic: '/hɛˈloʊ/', translation: 'Xin chào', example: 'Hello! My name is Anh.', exampleTranslation: 'Xin chào! Tên tôi là Anh.' },
      { word: 'Good morning', phonetic: '/ɡʊd ˈmɔːrnɪŋ/', translation: 'Chào buổi sáng', example: 'Good morning, everyone!', exampleTranslation: 'Chào buổi sáng mọi người!' },
      { word: 'Nice to meet you', phonetic: '/naɪs tə miːt juː/', translation: 'Rất vui được gặp bạn', example: 'Nice to meet you, I am the new manager.', exampleTranslation: 'Rất vui được gặp bạn, tôi là quản lý mới.' },
      { word: 'How are you?', phonetic: '/haʊ ɑːr juː/', translation: 'Bạn có khỏe không?', example: 'How are you today?', exampleTranslation: 'Hôm nay bạn có khỏe không?' },
      { word: "I'm fine, thank you", phonetic: '/aɪm faɪn θæŋk juː/', translation: 'Tôi khỏe, cảm ơn bạn', example: "I'm fine, thank you. And you?", exampleTranslation: 'Tôi khỏe, cảm ơn bạn. Còn bạn?' },
      { word: 'My name is', phonetic: '/maɪ neɪm ɪz/', translation: 'Tên tôi là', example: 'My name is Anh, I work in IT.', exampleTranslation: 'Tên tôi là Anh, tôi làm việc ở IT.' },
    ],
    exercises: [
      { id: 'd1e1', type: 'multiple-choice', question: '"Good morning" có nghĩa là gì?', options: ['Chào buổi tối', 'Chào buổi sáng', 'Chúc ngủ ngon', 'Hẹn gặp lại'], correct: 'Chào buổi sáng', hint: 'Morning = buổi sáng' },
      { id: 'd1e2', type: 'word-match', question: 'Nối từ tiếng Anh với nghĩa tiếng Việt', correct: 'matched', pairs: [['Hello', 'Xin chào'], ['Thank you', 'Cảm ơn'], ['Goodbye', 'Tạm biệt'], ['Please', 'Làm ơn'], ['Sorry', 'Xin lỗi']] },
      { id: 'd1e3', type: 'listen-choose', question: 'Nghe và chọn câu đúng', audioText: 'Nice to meet you', options: ['Nice to eat you', 'Nice to meet you', 'Nice to greet you', 'Nice to see you'], correct: 'Nice to meet you' },
      { id: 'd1e4', type: 'word-order', question: 'Sắp xếp thành câu đúng', words: ['name', 'is', 'My', 'Anh'], correct: 'My name is Anh', hint: 'Bắt đầu bằng "My"' },
      { id: 'd1e5', type: 'fill-blank', question: 'Good ___, how are you?', options: ['night', 'morning', 'bye', 'please'], correct: 'morning', hint: 'Dùng khi gặp nhau vào buổi sáng' },
      { id: 'd1e6', type: 'pronunciation', question: 'Phát âm câu chào hỏi', audioText: 'Nice to meet you', correct: 'nice to meet you', hint: '/naɪs tə miːt juː/' },
    ],
  },
  {
    day: 2,
    title: 'Office Objects',
    subtitle: 'Đồ vật trong văn phòng',
    theme: 'office',
    emoji: '💻',
    gradient: ['#0EA5E9', '#6366F1'],
    xpReward: 100,
    vocabulary: [
      { word: 'Computer', phonetic: '/kəmˈpjuːtər/', translation: 'Máy tính', example: 'My computer is broken today.', exampleTranslation: 'Máy tính của tôi bị hỏng hôm nay.' },
      { word: 'Desk', phonetic: '/dɛsk/', translation: 'Bàn làm việc', example: 'Please put the documents on my desk.', exampleTranslation: 'Hãy đặt tài liệu lên bàn của tôi.' },
      { word: 'Printer', phonetic: '/ˈprɪntər/', translation: 'Máy in', example: 'The printer is out of paper.', exampleTranslation: 'Máy in hết giấy rồi.' },
      { word: 'Meeting room', phonetic: '/ˈmiːtɪŋ ruːm/', translation: 'Phòng họp', example: 'The meeting room is on the 3rd floor.', exampleTranslation: 'Phòng họp ở tầng 3.' },
      { word: 'Colleague', phonetic: '/ˈkɒliːɡ/', translation: 'Đồng nghiệp', example: 'My colleague helped me finish the project.', exampleTranslation: 'Đồng nghiệp của tôi giúp tôi hoàn thành dự án.' },
      { word: 'Manager', phonetic: '/ˈmænɪdʒər/', translation: 'Quản lý', example: 'My manager is very supportive.', exampleTranslation: 'Quản lý của tôi rất hỗ trợ.' },
    ],
    exercises: [
      { id: 'd2e1', type: 'multiple-choice', question: '"Colleague" có nghĩa là gì?', options: ['Quản lý', 'Đồng nghiệp', 'Khách hàng', 'Giám đốc'], correct: 'Đồng nghiệp' },
      { id: 'd2e2', type: 'listen-choose', question: 'Nghe và chọn từ đúng', audioText: 'printer', options: ['Computer', 'Printer', 'Scanner', 'Monitor'], correct: 'Printer' },
      { id: 'd2e3', type: 'word-match', question: 'Nối từ với nghĩa tương ứng', correct: 'matched', pairs: [['Desk', 'Bàn làm việc'], ['Manager', 'Quản lý'], ['Computer', 'Máy tính'], ['Printer', 'Máy in'], ['Meeting room', 'Phòng họp']] },
      { id: 'd2e4', type: 'fill-blank', question: 'The ___ is on the 3rd floor.', options: ['desk', 'computer', 'meeting room', 'printer'], correct: 'meeting room', hint: 'Nơi mọi người họp lại' },
      { id: 'd2e5', type: 'word-order', question: 'Sắp xếp thành câu đúng', words: ['is', 'The', 'out', 'printer', 'of', 'paper'], correct: 'The printer is out of paper' },
      { id: 'd2e6', type: 'pronunciation', question: 'Phát âm từ văn phòng', audioText: 'colleague', correct: 'colleague', hint: '/ˈkɒliːɡ/' },
    ],
  },
  {
    day: 3,
    title: 'Time & Numbers',
    subtitle: 'Giờ giấc và con số',
    theme: 'office',
    emoji: '🕐',
    gradient: ['#F59E0B', '#EF4444'],
    xpReward: 110,
    vocabulary: [
      { word: 'What time is it?', phonetic: '/wɒt taɪm ɪz ɪt/', translation: 'Mấy giờ rồi?', example: 'Excuse me, what time is it?', exampleTranslation: 'Xin lỗi, mấy giờ rồi?' },
      { word: "It's 9 o'clock", phonetic: '/ɪts naɪn əˈklɒk/', translation: 'Bây giờ là 9 giờ', example: "The meeting starts at 9 o'clock.", exampleTranslation: 'Cuộc họp bắt đầu lúc 9 giờ.' },
      { word: 'Half past', phonetic: '/hɑːf pɑːst/', translation: 'Rưỡi (30 phút)', example: "It's half past three.", exampleTranslation: 'Bây giờ là 3 giờ 30.' },
      { word: 'Quarter to', phonetic: '/ˈkwɔːrtər tuː/', translation: 'Kém 15 phút', example: "It's quarter to five.", exampleTranslation: 'Bây giờ là 4 giờ 45.' },
      { word: 'In the morning', phonetic: '/ɪn ðə ˈmɔːrnɪŋ/', translation: 'Vào buổi sáng', example: 'I start work in the morning.', exampleTranslation: 'Tôi bắt đầu làm việc vào buổi sáng.' },
      { word: 'Deadline', phonetic: '/ˈdɛdlaɪn/', translation: 'Hạn chót', example: 'The deadline is Friday.', exampleTranslation: 'Hạn chót là thứ Sáu.' },
    ],
    exercises: [
      { id: 'd3e1', type: 'multiple-choice', question: '"Half past three" là mấy giờ?', options: ['3:15', '3:45', '3:30', '2:30'], correct: '3:30', hint: 'Half past = 30 phút' },
      { id: 'd3e2', type: 'listen-choose', question: 'Nghe và chọn câu đúng', audioText: 'The deadline is Friday', options: ['The deadline is Monday', 'The deadline is Friday', 'The deadline is Sunday', 'The deadline is Thursday'], correct: 'The deadline is Friday' },
      { id: 'd3e3', type: 'word-order', question: 'Sắp xếp câu hỏi đúng', words: ['time', 'it', 'What', 'is', '?'], correct: 'What time is it ?' },
      { id: 'd3e4', type: 'fill-blank', question: "The meeting starts ___ 9 o'clock.", options: ['in', 'on', 'at', 'by'], correct: 'at', hint: 'Dùng "at" trước giờ cụ thể' },
      { id: 'd3e5', type: 'word-match', question: 'Nối với nghĩa đúng', correct: 'matched', pairs: [['Deadline', 'Hạn chót'], ['Morning', 'Buổi sáng'], ['Afternoon', 'Buổi chiều'], ['Evening', 'Buổi tối'], ['Today', 'Hôm nay']] },
      { id: 'd3e6', type: 'pronunciation', question: 'Phát âm từ khó', audioText: 'deadline', correct: 'deadline', hint: '/ˈdɛdlaɪn/' },
    ],
  },
  {
    day: 4,
    title: 'Asking for Help',
    subtitle: 'Nhờ giúp đỡ & hỏi lại',
    theme: 'office',
    emoji: '🙋',
    gradient: ['#10B981', '#059669'],
    xpReward: 110,
    vocabulary: [
      { word: 'Could you help me?', phonetic: '/kʊd juː hɛlp miː/', translation: 'Bạn có thể giúp tôi không?', example: 'Could you help me with this report?', exampleTranslation: 'Bạn có thể giúp tôi với báo cáo này không?' },
      { word: "I don't understand", phonetic: '/aɪ doʊnt ˌʌndərˈstænd/', translation: 'Tôi không hiểu', example: "I'm sorry, I don't understand. Can you explain?", exampleTranslation: 'Xin lỗi, tôi không hiểu. Bạn có thể giải thích không?' },
      { word: 'Could you repeat that?', phonetic: '/kʊd juː rɪˈpiːt ðæt/', translation: 'Bạn có thể nói lại không?', example: "Could you repeat that, please? I missed it.", exampleTranslation: 'Bạn có thể nói lại không? Tôi không nghe kịp.' },
      { word: 'What does ... mean?', phonetic: '/wɒt dʌz ... miːn/', translation: '... có nghĩa là gì?', example: "What does 'budget' mean in Vietnamese?", exampleTranslation: '"Budget" có nghĩa là gì trong tiếng Việt?' },
      { word: 'Can you speak slowly?', phonetic: '/kæn juː spiːk ˈsloʊli/', translation: 'Bạn có thể nói chậm hơn không?', example: "Can you speak more slowly, please?", exampleTranslation: 'Bạn có thể nói chậm hơn không?' },
      { word: 'Of course', phonetic: '/ɒv kɔːrs/', translation: 'Tất nhiên rồi', example: "Of course! I'll help you right away.", exampleTranslation: 'Tất nhiên rồi! Tôi sẽ giúp bạn ngay.' },
    ],
    exercises: [
      { id: 'd4e1', type: 'multiple-choice', question: 'Khi không nghe rõ, bạn nói gì?', options: ["I don't know", 'Could you repeat that?', 'What does it mean?', 'Of course'], correct: 'Could you repeat that?' },
      { id: 'd4e2', type: 'word-order', question: 'Sắp xếp câu đúng', words: ['you', 'Could', 'me', 'help', '?'], correct: 'Could you help me ?' },
      { id: 'd4e3', type: 'listen-choose', question: 'Nghe và chọn câu đúng', audioText: "I don't understand, could you explain please", options: ["I don't understand, could you explain please", "I don't know, could you repeat please", "I don't understand, could you repeat please", "I can't understand, could you explain later"], correct: "I don't understand, could you explain please" },
      { id: 'd4e4', type: 'fill-blank', question: 'Could you speak more ___?', options: ['fast', 'slowly', 'loud', 'clear'], correct: 'slowly', hint: 'Chậm hơn = slowly' },
      { id: 'd4e5', type: 'word-match', question: 'Nối câu với tình huống phù hợp', correct: 'matched', pairs: [["Could you help me?", 'Nhờ giúp đỡ'], ["Of course!", 'Đồng ý giúp'], ["What does this mean?", 'Hỏi nghĩa từ'], ["Could you repeat that?", 'Xin nói lại'], ["I don't understand", 'Không hiểu']] },
      { id: 'd4e6', type: 'pronunciation', question: 'Phát âm câu quan trọng', audioText: "Could you repeat that please", correct: 'could you repeat that please', hint: '/kʊd juː rɪˈpiːt ðæt pliːz/' },
    ],
  },
  {
    day: 5,
    title: 'Meetings & Schedule',
    subtitle: 'Họp hành và lịch trình',
    theme: 'office',
    emoji: '📅',
    gradient: ['#8B5CF6', '#EC4899'],
    xpReward: 120,
    vocabulary: [
      { word: 'I have a meeting', phonetic: '/aɪ hæv ə ˈmiːtɪŋ/', translation: 'Tôi có cuộc họp', example: 'I have a meeting at 2 PM today.', exampleTranslation: 'Tôi có cuộc họp lúc 2 giờ chiều hôm nay.' },
      { word: 'Are you free?', phonetic: '/ɑːr juː friː/', translation: 'Bạn có rảnh không?', example: 'Are you free tomorrow morning?', exampleTranslation: 'Bạn có rảnh sáng mai không?' },
      { word: "I'll be there", phonetic: '/aɪl biː ðɛər/', translation: 'Tôi sẽ đến', example: "I'll be there at 3 o'clock.", exampleTranslation: 'Tôi sẽ đến lúc 3 giờ.' },
      { word: "Let's reschedule", phonetic: '/lɛts ˌriːˈskɛdʒuːl/', translation: 'Hãy đổi lịch', example: 'Can we reschedule to Thursday?', exampleTranslation: 'Chúng ta có thể đổi sang thứ Năm không?' },
      { word: 'Agenda', phonetic: '/əˈdʒɛndə/', translation: 'Chương trình họp', example: 'Please send me the meeting agenda.', exampleTranslation: 'Hãy gửi cho tôi chương trình họp.' },
      { word: 'Take notes', phonetic: '/teɪk noʊts/', translation: 'Ghi chú', example: 'Could you take notes for the meeting?', exampleTranslation: 'Bạn có thể ghi chú cho buổi họp không?' },
    ],
    exercises: [
      { id: 'd5e1', type: 'multiple-choice', question: '"Are you free tomorrow?" nghĩa là gì?', options: ['Bạn có miễn phí không?', 'Bạn có rảnh ngày mai không?', 'Bạn có ở nhà không?', 'Bạn có làm việc không?'], correct: 'Bạn có rảnh ngày mai không?' },
      { id: 'd5e2', type: 'word-order', question: 'Sắp xếp câu đúng', words: ['a', 'have', 'I', 'meeting', 'at', '2', 'PM'], correct: 'I have a meeting at 2 PM' },
      { id: 'd5e3', type: 'fill-blank', question: 'Please send me the meeting ___.', options: ['notes', 'agenda', 'schedule', 'time'], correct: 'agenda', hint: 'Danh sách nội dung sẽ thảo luận trong buổi họp' },
      { id: 'd5e4', type: 'listen-choose', question: 'Nghe và chọn câu đúng', audioText: 'Can we reschedule to Thursday', options: ['Can we reschedule to Tuesday', 'Can we reschedule to Thursday', 'Can we reschedule to Friday', 'Can we schedule for Thursday'], correct: 'Can we reschedule to Thursday' },
      { id: 'd5e5', type: 'word-match', question: 'Nối từ với nghĩa', correct: 'matched', pairs: [['Agenda', 'Chương trình họp'], ['Reschedule', 'Đổi lịch'], ['Take notes', 'Ghi chú'], ['Free', 'Rảnh rỗi'], ['Meeting', 'Cuộc họp']] },
      { id: 'd5e6', type: 'pronunciation', question: 'Phát âm từ khó', audioText: 'agenda', correct: 'agenda', hint: '/əˈdʒɛndə/ — nhấn âm "jen"' },
    ],
  },
  {
    day: 6,
    title: 'Making Requests',
    subtitle: 'Đưa ra yêu cầu lịch sự',
    theme: 'office',
    emoji: '🤝',
    gradient: ['#F97316', '#FBBF24'],
    xpReward: 120,
    vocabulary: [
      { word: 'Could you please...?', phonetic: '/kʊd juː pliːz/', translation: 'Bạn có thể... không?', example: 'Could you please send me the file?', exampleTranslation: 'Bạn có thể gửi cho tôi file đó không?' },
      { word: 'Would you mind...?', phonetic: '/wʊd juː maɪnd/', translation: 'Bạn có phiền... không?', example: 'Would you mind closing the door?', exampleTranslation: 'Bạn có phiền đóng cửa không?' },
      { word: 'I would like to...', phonetic: '/aɪ wʊd laɪk tuː/', translation: 'Tôi muốn...', example: 'I would like to speak with the manager.', exampleTranslation: 'Tôi muốn nói chuyện với quản lý.' },
      { word: 'Can I have...?', phonetic: '/kæn aɪ hæv/', translation: 'Tôi có thể có... không?', example: 'Can I have a copy of the report?', exampleTranslation: 'Tôi có thể có một bản sao báo cáo không?' },
      { word: 'No problem', phonetic: '/noʊ ˈprɒbləm/', translation: 'Không vấn đề gì', example: "No problem, I'll do it right away.", exampleTranslation: 'Không vấn đề gì, tôi sẽ làm ngay.' },
      { word: 'Sure thing', phonetic: '/ʃʊər θɪŋ/', translation: 'Chắc chắn rồi', example: "Sure thing! I'll send it to you.", exampleTranslation: 'Chắc chắn rồi! Tôi sẽ gửi cho bạn.' },
    ],
    exercises: [
      { id: 'd6e1', type: 'multiple-choice', question: 'Cách lịch sự nhất để nhờ ai đó làm gì?', options: ['Do this now!', 'Could you please help me?', 'Help me!', 'You must help me'], correct: 'Could you please help me?' },
      { id: 'd6e2', type: 'word-order', question: 'Sắp xếp câu đúng', words: ['mind', 'Would', 'you', 'door', 'closing', 'the', '?'], correct: 'Would you mind closing the door ?' },
      { id: 'd6e3', type: 'fill-blank', question: 'I ___ like to speak with the manager.', options: ['will', 'would', 'should', 'could'], correct: 'would', hint: '"Would like" = muốn (lịch sự)' },
      { id: 'd6e4', type: 'listen-choose', question: 'Nghe và chọn câu đúng', audioText: 'No problem, I will do it right away', options: ['No problem, I will do it right away', 'No problem, I will do it tomorrow', 'No problem, she will do it right away', 'Sure thing, I will do it right away'], correct: 'No problem, I will do it right away' },
      { id: 'd6e5', type: 'word-match', question: 'Nối câu với nghĩa', correct: 'matched', pairs: [['No problem', 'Không vấn đề gì'], ['Sure thing', 'Chắc chắn rồi'], ['Would you mind?', 'Bạn có phiền không?'], ['I would like', 'Tôi muốn'], ['Can I have?', 'Tôi có thể có không?']] },
      { id: 'd6e6', type: 'pronunciation', question: 'Phát âm câu yêu cầu lịch sự', audioText: 'Could you please help me', correct: 'could you please help me', hint: '/kʊd juː pliːz hɛlp miː/' },
    ],
  },
  {
    day: 7,
    title: 'Office Review',
    subtitle: 'Ôn tập tuần 1',
    theme: 'review',
    emoji: '⭐',
    gradient: ['#6366F1', '#8B5CF6'],
    xpReward: 150,
    vocabulary: [
      { word: 'Presentation', phonetic: '/ˌprezənˈteɪʃən/', translation: 'Bài thuyết trình', example: 'I have a presentation tomorrow.', exampleTranslation: 'Tôi có bài thuyết trình ngày mai.' },
      { word: 'Report', phonetic: '/rɪˈpɔːrt/', translation: 'Báo cáo', example: 'The monthly report is due on Friday.', exampleTranslation: 'Báo cáo tháng phải nộp vào thứ Sáu.' },
      { word: 'Client', phonetic: '/ˈklaɪənt/', translation: 'Khách hàng', example: 'Our client is very happy with the results.', exampleTranslation: 'Khách hàng của chúng tôi rất hài lòng với kết quả.' },
      { word: 'Project', phonetic: '/ˈprɒdʒɛkt/', translation: 'Dự án', example: 'The project deadline is next week.', exampleTranslation: 'Hạn chót của dự án là tuần sau.' },
      { word: 'Budget', phonetic: '/ˈbʌdʒɪt/', translation: 'Ngân sách', example: "We don't have enough budget.", exampleTranslation: 'Chúng tôi không có đủ ngân sách.' },
      { word: 'Feedback', phonetic: '/ˈfiːdbæk/', translation: 'Phản hồi', example: 'Please give me your feedback.', exampleTranslation: 'Hãy cho tôi biết phản hồi của bạn.' },
    ],
    exercises: [
      { id: 'd7e1', type: 'multiple-choice', question: 'Chọn câu đúng để nhờ ai đó gửi file', options: ['Send the file!', 'Could you please send me the file?', 'I want the file now.', 'Give me the file.'], correct: 'Could you please send me the file?' },
      { id: 'd7e2', type: 'word-match', question: 'Ôn lại từ vựng tuần 1', correct: 'matched', pairs: [['Deadline', 'Hạn chót'], ['Budget', 'Ngân sách'], ['Client', 'Khách hàng'], ['Feedback', 'Phản hồi'], ['Colleague', 'Đồng nghiệp']] },
      { id: 'd7e3', type: 'word-order', question: 'Sắp xếp câu đúng', words: ['project', 'The', 'is', 'deadline', 'next', 'week'], correct: 'The project deadline is next week' },
      { id: 'd7e4', type: 'fill-blank', question: 'Could you take ___ for the meeting?', options: ['agenda', 'notes', 'files', 'report'], correct: 'notes' },
      { id: 'd7e5', type: 'listen-choose', question: 'Nghe và chọn đúng', audioText: 'Please give me your feedback on the presentation', options: ['Please give me your feedback on the project', 'Please give me your feedback on the presentation', 'Please send me your feedback on the presentation', 'Please give me your notes on the presentation'], correct: 'Please give me your feedback on the presentation' },
      { id: 'd7e6', type: 'pronunciation', question: 'Phát âm từ khó nhất tuần này', audioText: 'presentation', correct: 'presentation', hint: '/ˌprezənˈteɪʃən/ — nhấn vào "TAY"' },
    ],
  },
  {
    day: 8,
    title: 'At the Airport',
    subtitle: 'Tại sân bay',
    theme: 'travel',
    emoji: '✈️',
    gradient: ['#06B6D4', '#3B82F6'],
    xpReward: 120,
    vocabulary: [
      { word: 'Passport', phonetic: '/ˈpɑːspɔːrt/', translation: 'Hộ chiếu', example: 'Please show me your passport.', exampleTranslation: 'Hãy cho tôi xem hộ chiếu của bạn.' },
      { word: 'Boarding pass', phonetic: '/ˈbɔːrdɪŋ pɑːs/', translation: 'Thẻ lên máy bay', example: 'I need to print my boarding pass.', exampleTranslation: 'Tôi cần in thẻ lên máy bay.' },
      { word: 'Check-in', phonetic: '/ˈtʃɛkɪn/', translation: 'Làm thủ tục', example: 'Where is the check-in counter?', exampleTranslation: 'Quầy làm thủ tục ở đâu?' },
      { word: 'Gate', phonetic: '/ɡeɪt/', translation: 'Cổng khởi hành', example: 'Your flight departs from gate B12.', exampleTranslation: 'Chuyến bay của bạn khởi hành từ cổng B12.' },
      { word: 'Luggage', phonetic: '/ˈlʌɡɪdʒ/', translation: 'Hành lý', example: 'How many pieces of luggage do you have?', exampleTranslation: 'Bạn có bao nhiêu kiện hành lý?' },
      { word: 'Delayed', phonetic: '/dɪˈleɪd/', translation: 'Bị trễ', example: 'My flight is delayed by 2 hours.', exampleTranslation: 'Chuyến bay của tôi bị trễ 2 tiếng.' },
    ],
    exercises: [
      { id: 'd8e1', type: 'multiple-choice', question: '"Boarding pass" là gì?', options: ['Hộ chiếu', 'Thẻ lên máy bay', 'Vé xe', 'Thẻ khách sạn'], correct: 'Thẻ lên máy bay' },
      { id: 'd8e2', type: 'word-order', question: 'Sắp xếp câu hỏi đúng', words: ['is', 'the', 'Where', 'check-in', 'counter', '?'], correct: 'Where is the check-in counter ?' },
      { id: 'd8e3', type: 'listen-choose', question: 'Nghe và chọn câu đúng', audioText: 'Your flight departs from gate B twelve', options: ['Your flight departs from gate A twelve', 'Your flight departs from gate B twelve', 'Your flight arrives at gate B twelve', 'Your flight departs from gate B two'], correct: 'Your flight departs from gate B twelve' },
      { id: 'd8e4', type: 'fill-blank', question: 'My flight is ___ by 2 hours.', options: ['late', 'delayed', 'slow', 'cancelled'], correct: 'delayed', hint: 'Bị trễ = delayed' },
      { id: 'd8e5', type: 'word-match', question: 'Nối từ với nghĩa', correct: 'matched', pairs: [['Passport', 'Hộ chiếu'], ['Gate', 'Cổng khởi hành'], ['Luggage', 'Hành lý'], ['Delayed', 'Bị trễ'], ['Check-in', 'Làm thủ tục']] },
      { id: 'd8e6', type: 'pronunciation', question: 'Phát âm câu tại sân bay', audioText: 'Where is the check-in counter', correct: 'where is the check-in counter', hint: '/wɛər ɪz ðə ˈtʃɛkɪn ˈkaʊntər/' },
    ],
  },
  {
    day: 9,
    title: 'Hotel Check-in',
    subtitle: 'Nhận phòng khách sạn',
    theme: 'travel',
    emoji: '🏨',
    gradient: ['#EC4899', '#8B5CF6'],
    xpReward: 120,
    vocabulary: [
      { word: 'Reservation', phonetic: '/ˌrɛzərˈveɪʃən/', translation: 'Đặt phòng', example: 'I have a reservation under the name Anh.', exampleTranslation: 'Tôi có đặt phòng dưới tên Anh.' },
      { word: 'Room service', phonetic: '/ruːm ˈsɜːrvɪs/', translation: 'Dịch vụ phòng', example: 'I would like to order room service.', exampleTranslation: 'Tôi muốn gọi dịch vụ phòng.' },
      { word: 'Check out', phonetic: '/tʃɛk aʊt/', translation: 'Trả phòng', example: 'What time is check-out?', exampleTranslation: 'Mấy giờ là giờ trả phòng?' },
      { word: 'King-size bed', phonetic: '/kɪŋ saɪz bɛd/', translation: 'Giường đôi lớn', example: 'I prefer a room with a king-size bed.', exampleTranslation: 'Tôi thích phòng có giường đôi lớn.' },
      { word: 'Wi-Fi password', phonetic: '/ˈwaɪfaɪ ˈpæswɜːrd/', translation: 'Mật khẩu Wi-Fi', example: 'What is the Wi-Fi password?', exampleTranslation: 'Mật khẩu Wi-Fi là gì?' },
      { word: 'Non-smoking', phonetic: '/nɒn ˈsmoʊkɪŋ/', translation: 'Không hút thuốc', example: 'I need a non-smoking room, please.', exampleTranslation: 'Tôi cần phòng không hút thuốc.' },
    ],
    exercises: [
      { id: 'd9e1', type: 'multiple-choice', question: '"Check out" có nghĩa là gì?', options: ['Nhận phòng', 'Trả phòng', 'Đặt phòng', 'Dọn phòng'], correct: 'Trả phòng' },
      { id: 'd9e2', type: 'word-order', question: 'Sắp xếp câu đúng', words: ['have', 'I', 'reservation', 'a', 'Anh', 'name', 'under', 'the'], correct: 'I have a reservation under the name Anh' },
      { id: 'd9e3', type: 'fill-blank', question: 'What is the ___ password?', options: ['internet', 'Wi-Fi', 'computer', 'phone'], correct: 'Wi-Fi' },
      { id: 'd9e4', type: 'listen-choose', question: 'Nghe và chọn câu đúng', audioText: 'I need a non-smoking room please', options: ['I need a smoking room please', 'I need a non-smoking room please', 'I want a non-smoking room please', 'I need a non-smoking suite please'], correct: 'I need a non-smoking room please' },
      { id: 'd9e5', type: 'word-match', question: 'Nối từ với nghĩa', correct: 'matched', pairs: [['Reservation', 'Đặt phòng'], ['Check out', 'Trả phòng'], ['Room service', 'Dịch vụ phòng'], ['Non-smoking', 'Không hút thuốc'], ['Key card', 'Thẻ chìa khóa']] },
      { id: 'd9e6', type: 'pronunciation', question: 'Phát âm từ khó', audioText: 'reservation', correct: 'reservation', hint: '/ˌrɛzərˈveɪʃən/ — nhấn "VAY"' },
    ],
  },
  {
    day: 10,
    title: 'Asking for Directions',
    subtitle: 'Hỏi đường',
    theme: 'travel',
    emoji: '🗺️',
    gradient: ['#14B8A6', '#06B6D4'],
    xpReward: 130,
    vocabulary: [
      { word: 'Turn left', phonetic: '/tɜːrn lɛft/', translation: 'Rẽ trái', example: 'Turn left at the traffic light.', exampleTranslation: 'Rẽ trái ở đèn giao thông.' },
      { word: 'Turn right', phonetic: '/tɜːrn raɪt/', translation: 'Rẽ phải', example: 'Turn right at the next corner.', exampleTranslation: 'Rẽ phải ở góc phố tiếp theo.' },
      { word: 'Go straight', phonetic: '/ɡoʊ streɪt/', translation: 'Đi thẳng', example: 'Go straight for 200 meters.', exampleTranslation: 'Đi thẳng 200 mét.' },
      { word: "It's on the left", phonetic: '/ɪts ɒn ðə lɛft/', translation: 'Nó ở bên trái', example: 'The hospital is on the left.', exampleTranslation: 'Bệnh viện ở bên trái.' },
      { word: 'How far is it?', phonetic: '/haʊ fɑːr ɪz ɪt/', translation: 'Cách bao xa?', example: 'How far is it to the train station?', exampleTranslation: 'Đến nhà ga tàu cách bao xa?' },
      { word: "About 5 minutes' walk", phonetic: '/əˈbaʊt faɪv ˈmɪnɪts wɔːk/', translation: 'Khoảng 5 phút đi bộ', example: "It's about 5 minutes' walk from here.", exampleTranslation: 'Từ đây khoảng 5 phút đi bộ.' },
    ],
    exercises: [
      { id: 'd10e1', type: 'multiple-choice', question: '"Turn left at the corner" nghĩa là gì?', options: ['Đi thẳng ở góc phố', 'Rẽ phải ở góc phố', 'Rẽ trái ở góc phố', 'Dừng lại ở góc phố'], correct: 'Rẽ trái ở góc phố' },
      { id: 'd10e2', type: 'word-order', question: 'Sắp xếp câu hỏi đúng', words: ['far', 'the', 'is', 'How', 'station', 'train', '?'], correct: 'How far is the train station ?' },
      { id: 'd10e3', type: 'fill-blank', question: 'Go ___ for 200 meters, then turn right.', options: ['left', 'right', 'straight', 'back'], correct: 'straight' },
      { id: 'd10e4', type: 'listen-choose', question: 'Nghe và chọn câu đúng', audioText: "It's about five minutes walk from here", options: ["It's about ten minutes walk from here", "It's about five minutes walk from here", "It's about five minutes drive from here", "It's about fifty minutes walk from here"], correct: "It's about five minutes walk from here" },
      { id: 'd10e5', type: 'word-match', question: 'Nối từ chỉ hướng', correct: 'matched', pairs: [['Turn left', 'Rẽ trái'], ['Turn right', 'Rẽ phải'], ['Go straight', 'Đi thẳng'], ['On the left', 'Bên trái'], ['On the right', 'Bên phải']] },
      { id: 'd10e6', type: 'pronunciation', question: 'Hỏi đường bằng tiếng Anh', audioText: 'Excuse me, how do I get to the train station', correct: 'excuse me how do i get to the train station', hint: '/ɪkˈskjuːz miː haʊ duː aɪ ɡɛt tuː ðə treɪn ˈsteɪʃən/' },
    ],
  },
  {
    day: 11,
    title: 'Restaurant & Food',
    subtitle: 'Nhà hàng và đặt món',
    theme: 'travel',
    emoji: '🍽️',
    gradient: ['#EF4444', '#F97316'],
    xpReward: 130,
    vocabulary: [
      { word: "I'd like to order", phonetic: '/aɪd laɪk tuː ˈɔːrdər/', translation: 'Tôi muốn gọi món', example: "I'd like to order the grilled chicken, please.", exampleTranslation: 'Tôi muốn gọi gà nướng, làm ơn.' },
      { word: 'What do you recommend?', phonetic: '/wɒt duː juː ˌrɛkəˈmɛnd/', translation: 'Bạn gợi ý món gì?', example: 'What do you recommend from the menu?', exampleTranslation: 'Bạn gợi ý món nào từ thực đơn?' },
      { word: 'The bill, please', phonetic: '/ðə bɪl pliːz/', translation: 'Cho tôi hóa đơn', example: 'Excuse me, the bill, please.', exampleTranslation: 'Xin lỗi, cho tôi hóa đơn.' },
      { word: 'A table for two', phonetic: '/ə ˈteɪbəl fɔːr tuː/', translation: 'Bàn cho hai người', example: 'I would like a table for two, please.', exampleTranslation: 'Tôi muốn một bàn cho hai người.' },
      { word: 'Vegetarian', phonetic: '/ˌvɛdʒɪˈtɛəriən/', translation: 'Ăn chay', example: 'Do you have any vegetarian options?', exampleTranslation: 'Bạn có món nào ăn chay không?' },
      { word: 'Delicious', phonetic: '/dɪˈlɪʃəs/', translation: 'Ngon', example: 'This food is absolutely delicious!', exampleTranslation: 'Món ăn này thực sự rất ngon!' },
    ],
    exercises: [
      { id: 'd11e1', type: 'multiple-choice', question: 'Khi muốn trả tiền, bạn nói gì?', options: ["I'd like to order", 'The bill, please', 'What do you recommend?', 'A table for two'], correct: 'The bill, please' },
      { id: 'd11e2', type: 'word-order', question: 'Sắp xếp câu đúng', words: ['like', "I'd", 'table', 'for', 'a', 'two'], correct: "I'd like a table for two" },
      { id: 'd11e3', type: 'fill-blank', question: 'Do you have any ___ options?', options: ['meat', 'vegetarian', 'expensive', 'local'], correct: 'vegetarian', hint: 'Ăn chay = vegetarian' },
      { id: 'd11e4', type: 'listen-choose', question: 'Nghe và chọn đúng', audioText: 'What do you recommend from the menu', options: ['What do you recommend from the chef', 'What do you recommend from the menu', 'What would you recommend from the menu', 'What do you order from the menu'], correct: 'What do you recommend from the menu' },
      { id: 'd11e5', type: 'word-match', question: 'Nối với nghĩa đúng', correct: 'matched', pairs: [['Delicious', 'Ngon'], ['Vegetarian', 'Ăn chay'], ['Menu', 'Thực đơn'], ['Bill', 'Hóa đơn'], ['Order', 'Gọi món']] },
      { id: 'd11e6', type: 'pronunciation', question: 'Phát âm từ khó', audioText: 'vegetarian', correct: 'vegetarian', hint: '/ˌvɛdʒɪˈtɛəriən/ — nhấn "TER"' },
    ],
  },
  {
    day: 12,
    title: 'Shopping',
    subtitle: 'Mua sắm',
    theme: 'travel',
    emoji: '🛍️',
    gradient: ['#F59E0B', '#10B981'],
    xpReward: 130,
    vocabulary: [
      { word: 'How much does it cost?', phonetic: '/haʊ mʌtʃ dʌz ɪt kɒst/', translation: 'Cái này giá bao nhiêu?', example: 'Excuse me, how much does this cost?', exampleTranslation: 'Xin lỗi, cái này giá bao nhiêu?' },
      { word: 'Do you have this in...?', phonetic: '/duː juː hæv ðɪs ɪn/', translation: 'Bạn có cái này màu/size...?', example: 'Do you have this in blue?', exampleTranslation: 'Bạn có cái này màu xanh không?' },
      { word: 'Too expensive', phonetic: '/tuː ɪkˈspɛnsɪv/', translation: 'Quá đắt', example: "That's too expensive. Do you have anything cheaper?", exampleTranslation: 'Cái đó quá đắt. Bạn có cái nào rẻ hơn không?' },
      { word: 'Receipt', phonetic: '/rɪˈsiːt/', translation: 'Hóa đơn mua hàng', example: 'Can I have the receipt, please?', exampleTranslation: 'Bạn cho tôi hóa đơn được không?' },
      { word: 'Discount', phonetic: '/ˈdɪskaʊnt/', translation: 'Giảm giá', example: 'Is there a discount for this item?', exampleTranslation: 'Mặt hàng này có giảm giá không?' },
      { word: 'Exchange', phonetic: '/ɪksˈtʃeɪndʒ/', translation: 'Đổi hàng', example: 'I would like to exchange this for a larger size.', exampleTranslation: 'Tôi muốn đổi cái này lấy size lớn hơn.' },
    ],
    exercises: [
      { id: 'd12e1', type: 'multiple-choice', question: '"How much does it cost?" nghĩa là gì?', options: ['Cái này ở đâu?', 'Cái này giá bao nhiêu?', 'Cái này màu gì?', 'Bạn có cái này không?'], correct: 'Cái này giá bao nhiêu?' },
      { id: 'd12e2', type: 'word-order', question: 'Sắp xếp câu đúng', words: ['have', 'Do', 'you', 'blue', 'in', 'this', '?'], correct: 'Do you have this in blue ?' },
      { id: 'd12e3', type: 'fill-blank', question: "That's too ___. Do you have anything cheaper?", options: ['good', 'cheap', 'expensive', 'small'], correct: 'expensive' },
      { id: 'd12e4', type: 'listen-choose', question: 'Nghe và chọn câu đúng', audioText: 'Is there a discount for this item', options: ['Is there a discount for these items', 'Is there a discount for this item', 'Is there a sale for this item', 'Is there any discount for this item'], correct: 'Is there a discount for this item' },
      { id: 'd12e5', type: 'word-match', question: 'Nối từ với nghĩa', correct: 'matched', pairs: [['Discount', 'Giảm giá'], ['Receipt', 'Hóa đơn'], ['Exchange', 'Đổi hàng'], ['Expensive', 'Đắt'], ['Cheaper', 'Rẻ hơn']] },
      { id: 'd12e6', type: 'pronunciation', question: 'Phát âm từ dễ nhầm', audioText: 'receipt', correct: 'receipt', hint: '/rɪˈsiːt/ — chữ "p" không đọc!' },
    ],
  },
  {
    day: 13,
    title: 'Transportation',
    subtitle: 'Phương tiện di chuyển',
    theme: 'travel',
    emoji: '🚕',
    gradient: ['#3B82F6', '#06B6D4'],
    xpReward: 130,
    vocabulary: [
      { word: 'Take me to...', phonetic: '/teɪk miː tuː/', translation: 'Đưa tôi đến...', example: 'Take me to the city center, please.', exampleTranslation: 'Đưa tôi đến trung tâm thành phố.' },
      { word: 'How long does it take?', phonetic: '/haʊ lɒŋ dʌz ɪt teɪk/', translation: 'Mất bao lâu?', example: 'How long does it take to get there?', exampleTranslation: 'Mất bao lâu để đến đó?' },
      { word: 'Where do I buy tickets?', phonetic: '/wɛər duː aɪ baɪ ˈtɪkɪts/', translation: 'Tôi mua vé ở đâu?', example: 'Where do I buy tickets for the bus?', exampleTranslation: 'Tôi mua vé xe buýt ở đâu?' },
      { word: 'Bus stop', phonetic: '/bʌs stɒp/', translation: 'Trạm xe buýt', example: 'Is there a bus stop near here?', exampleTranslation: 'Gần đây có trạm xe buýt không?' },
      { word: 'Taxi', phonetic: '/ˈtæksi/', translation: 'Xe taxi', example: 'Can you call a taxi for me?', exampleTranslation: 'Bạn có thể gọi taxi cho tôi không?' },
      { word: 'Train station', phonetic: '/treɪn ˈsteɪʃən/', translation: 'Ga tàu', example: 'The train station is 10 minutes away.', exampleTranslation: 'Ga tàu cách đây 10 phút.' },
    ],
    exercises: [
      { id: 'd13e1', type: 'multiple-choice', question: 'Khi đi taxi, bạn nói gì để đến một địa điểm?', options: ['Where is...?', 'Take me to...', 'How far is...?', 'I want to go'], correct: 'Take me to...' },
      { id: 'd13e2', type: 'word-order', question: 'Sắp xếp câu hỏi đúng', words: ['long', 'does', 'How', 'it', 'take', '?'], correct: 'How long does it take ?' },
      { id: 'd13e3', type: 'fill-blank', question: 'Where do I buy ___ for the bus?', options: ['cards', 'money', 'tickets', 'passes'], correct: 'tickets' },
      { id: 'd13e4', type: 'listen-choose', question: 'Nghe và chọn đúng', audioText: 'Can you call a taxi for me please', options: ['Can you book a taxi for me please', 'Can you call a taxi for me please', 'Can you call a bus for me please', 'Could you call a taxi for me please'], correct: 'Can you call a taxi for me please' },
      { id: 'd13e5', type: 'word-match', question: 'Nối phương tiện với nghĩa', correct: 'matched', pairs: [['Taxi', 'Xe taxi'], ['Bus stop', 'Trạm xe buýt'], ['Train station', 'Ga tàu'], ['Subway', 'Tàu điện ngầm'], ['Airport', 'Sân bay']] },
      { id: 'd13e6', type: 'pronunciation', question: 'Nói với tài xế taxi', audioText: 'Take me to the train station please', correct: 'take me to the train station please', hint: '/teɪk miː tuː ðə treɪn ˈsteɪʃən pliːz/' },
    ],
  },
  {
    day: 14,
    title: 'Small Talk',
    subtitle: 'Chuyện phiếm xã giao',
    theme: 'travel',
    emoji: '💬',
    gradient: ['#A855F7', '#EC4899'],
    xpReward: 140,
    vocabulary: [
      { word: 'How was your weekend?', phonetic: '/haʊ wɒz jɔːr ˈwiːkɛnd/', translation: 'Cuối tuần của bạn thế nào?', example: 'Hey! How was your weekend?', exampleTranslation: 'Này! Cuối tuần của bạn thế nào?' },
      { word: 'The weather is great', phonetic: '/ðə ˈwɛðər ɪz ɡreɪt/', translation: 'Thời tiết thật tuyệt', example: "The weather is great today, isn't it?", exampleTranslation: 'Thời tiết hôm nay thật tuyệt, phải không?' },
      { word: 'What do you do for fun?', phonetic: '/wɒt duː juː duː fɔːr fʌn/', translation: 'Bạn thích làm gì cho vui?', example: 'After work, what do you do for fun?', exampleTranslation: 'Sau giờ làm, bạn thích làm gì cho vui?' },
      { word: 'I enjoy...', phonetic: '/aɪ ɪnˈdʒɔɪ/', translation: 'Tôi thích...', example: 'I enjoy reading books and traveling.', exampleTranslation: 'Tôi thích đọc sách và đi du lịch.' },
      { word: 'Have a great day!', phonetic: '/hæv ə ɡreɪt deɪ/', translation: 'Chúc bạn một ngày tốt lành!', example: "It was nice talking to you! Have a great day!", exampleTranslation: 'Rất vui được nói chuyện với bạn! Chúc bạn một ngày tốt lành!' },
      { word: "That's interesting!", phonetic: '/ðæts ˈɪntrɪstɪŋ/', translation: 'Thật thú vị!', example: "Oh, you traveled to Japan? That's interesting!", exampleTranslation: 'Ồ, bạn đã đến Nhật? Thật thú vị!' },
    ],
    exercises: [
      { id: 'd14e1', type: 'multiple-choice', question: 'Khi chia tay ai đó, bạn nói gì?', options: ["That's interesting!", 'Have a great day!', 'How was your weekend?', 'I enjoy traveling'], correct: 'Have a great day!' },
      { id: 'd14e2', type: 'word-order', question: 'Sắp xếp câu hỏi đúng', words: ['do', 'What', 'you', 'for', 'do', 'fun', '?'], correct: 'What do you do for fun ?' },
      { id: 'd14e3', type: 'fill-blank', question: 'I ___ reading books and traveling.', options: ['want', 'enjoy', 'need', 'do'], correct: 'enjoy' },
      { id: 'd14e4', type: 'listen-choose', question: 'Nghe và chọn câu đúng', audioText: "The weather is great today isn't it", options: ["The weather is nice today isn't it", "The weather is great today isn't it", "The weather is great today is it", "The weather was great today wasn't it"], correct: "The weather is great today isn't it" },
      { id: 'd14e5', type: 'word-match', question: 'Nối với nghĩa phù hợp', correct: 'matched', pairs: [['How was your weekend?', 'Cuối tuần thế nào?'], ['I enjoy...', 'Tôi thích...'], ["That's interesting!", 'Thật thú vị!'], ['Have a great day!', 'Chúc ngày tốt lành!'], ['What about you?', 'Còn bạn thì sao?']] },
      { id: 'd14e6', type: 'pronunciation', question: 'Phát âm câu xã giao', audioText: "That's interesting, have a great day", correct: "that's interesting have a great day", hint: '/ðæts ˈɪntrɪstɪŋ hæv ə ɡreɪt deɪ/' },
    ],
  },
  {
    day: 15,
    title: 'Week 2 Review',
    subtitle: 'Ôn tập tuần 2 — Travel',
    theme: 'review',
    emoji: '⭐',
    gradient: ['#06B6D4', '#3B82F6'],
    xpReward: 150,
    vocabulary: [
      { word: 'Itinerary', phonetic: '/aɪˈtɪnəreri/', translation: 'Lịch trình chuyến đi', example: "I'll send you the travel itinerary tonight.", exampleTranslation: 'Tôi sẽ gửi cho bạn lịch trình chuyến đi tối nay.' },
      { word: 'Customs', phonetic: '/ˈkʌstəmz/', translation: 'Hải quan', example: 'You must declare cash over $10,000 at customs.', exampleTranslation: 'Bạn phải khai báo tiền mặt trên $10,000 tại hải quan.' },
      { word: 'Complimentary', phonetic: '/ˌkɒmplɪˈmentri/', translation: 'Miễn phí (quà tặng)', example: 'Breakfast is complimentary for all guests.', exampleTranslation: 'Bữa sáng miễn phí cho tất cả khách.' },
      { word: 'Connecting flight', phonetic: '/kəˈnɛktɪŋ flaɪt/', translation: 'Chuyến bay nối chuyến', example: 'I have a 2-hour layover for my connecting flight.', exampleTranslation: 'Tôi có 2 giờ chờ cho chuyến bay nối chuyến.' },
      { word: 'Fare', phonetic: '/fɛər/', translation: 'Giá vé', example: 'The taxi fare to the hotel is about $20.', exampleTranslation: 'Giá taxi đến khách sạn khoảng $20.' },
      { word: 'Jet lag', phonetic: '/ˈdʒɛt læɡ/', translation: 'Mệt vì lệch múi giờ', example: 'I always get jet lag on long flights.', exampleTranslation: 'Tôi luôn bị lệch múi giờ trên các chuyến bay dài.' },
    ],
    exercises: [
      { id: 'd15e1', type: 'multiple-choice', question: 'A "connecting flight" means:', options: ['A direct flight', 'A flight with a stop in another city', 'A cancelled flight', 'A cheap flight'], correct: 'A flight with a stop in another city' },
      { id: 'd15e2', type: 'word-order', question: 'Arrange the sentence correctly', words: ['have', 'I', 'a', 'reservation', 'name', 'under', 'Anh', 'the'], correct: 'I have a reservation under the name Anh' },
      { id: 'd15e3', type: 'word-match', question: 'Match travel vocabulary', correct: 'matched', pairs: [['Boarding pass', 'Thẻ lên máy bay'], ['Fare', 'Giá vé'], ['Jet lag', 'Mệt lệch múi giờ'], ['Customs', 'Hải quan'], ['Itinerary', 'Lịch trình']] },
      { id: 'd15e4', type: 'fill-blank', question: 'Breakfast is ___ for all guests.', options: ['free', 'complimentary', 'included', 'cheap'], correct: 'complimentary', hint: '"Complimentary" = free as a gift from the hotel' },
      { id: 'd15e5', type: 'listen-choose', question: 'Listen and choose', audioText: 'My flight is delayed by two hours, could you check the gate', options: ['My flight is delayed by two hours, could you check the gate', 'My flight is delayed by an hour, could you check the gate', 'My flight is cancelled, could you check the gate', 'My flight is delayed by two hours, could you check the time'], correct: 'My flight is delayed by two hours, could you check the gate' },
      { id: 'd15e6', type: 'pronunciation', question: 'Tricky travel word', audioText: 'itinerary', correct: 'itinerary', hint: '/aɪˈtɪnəreri/ — stress on "TIN", silent second "a"' },
    ],
  },

  // ── WEEK 3: Tech Communication ────────────────────────────────────────────
  {
    day: 16,
    title: 'Code Review Talk',
    subtitle: 'Ngôn ngữ trong code review',
    theme: 'tech',
    emoji: '🔍',
    gradient: ['#6366F1', '#8B5CF6'],
    xpReward: 140,
    vocabulary: [
      { word: 'Nit', phonetic: '/nɪt/', translation: 'Góp ý nhỏ, không bắt buộc', example: 'Nit: you could rename this variable to be clearer.', exampleTranslation: 'Nit: bạn có thể đặt tên biến này rõ hơn.' },
      { word: 'LGTM', phonetic: '/ˌɛl dʒiː tiː ˈɛm/', translation: 'Looks good to me — trông ổn', example: 'LGTM! Merging now.', exampleTranslation: 'Trông ổn! Merge luôn nhé.' },
      { word: 'Can you walk me through this?', phonetic: '/kæn juː wɔːk miː θruː ðɪs/', translation: 'Bạn có thể giải thích cái này không?', example: 'Can you walk me through this logic?', exampleTranslation: 'Bạn có thể giải thích logic này không?' },
      { word: 'What was the thinking here?', phonetic: '/wɒt wɒz ðə ˈθɪŋkɪŋ hɪər/', translation: 'Suy nghĩ của bạn ở đây là gì?', example: 'What was the thinking here — why not use a map?', exampleTranslation: 'Suy nghĩ của bạn ở đây là gì — sao không dùng map?' },
      { word: 'This could be cleaner', phonetic: '/ðɪs kʊd biː ˈkliːnər/', translation: 'Cái này có thể gọn hơn', example: 'This could be cleaner — consider extracting a helper function.', exampleTranslation: 'Cái này có thể gọn hơn — hãy xem xét tách hàm helper.' },
      { word: 'Blocking issue', phonetic: '/ˈblɒkɪŋ ˈɪʃuː/', translation: 'Vấn đề chặn merge', example: "There's a blocking issue here — this will break in production.", exampleTranslation: 'Có vấn đề chặn merge ở đây — cái này sẽ bị lỗi ở production.' },
    ],
    exercises: [
      { id: 'd16e1', type: 'multiple-choice', question: 'What does "LGTM" mean in a PR comment?', options: ['Please fix this', 'Looks good to me', 'Let me test more', 'Large task milestone'], correct: 'Looks good to me' },
      { id: 'd16e2', type: 'word-order', question: 'Arrange the review comment', words: ['walk', 'Can', 'you', 'me', 'through', 'this', 'logic', '?'], correct: 'Can you walk me through this logic ?' },
      { id: 'd16e3', type: 'fill-blank', question: '___ issue — this will break the API in production.', options: ['Minor', 'Blocking', 'Small', 'Optional'], correct: 'Blocking', hint: 'Something that must be fixed before merging' },
      { id: 'd16e4', type: 'listen-choose', question: 'Listen and choose', audioText: 'This could be cleaner, consider extracting a helper function', options: ['This could be cleaner, consider extracting a helper function', 'This could be better, consider extracting a helper function', 'This could be cleaner, consider adding a helper function', 'This should be cleaner, consider extracting a helper function'], correct: 'This could be cleaner, consider extracting a helper function' },
      { id: 'd16e5', type: 'word-match', question: 'Match code review terms', correct: 'matched', pairs: [['Nit', 'Nhỏ, không bắt buộc'], ['LGTM', 'Trông ổn'], ['Blocking', 'Phải sửa trước khi merge'], ['Walk me through', 'Giải thích cho tôi'], ['Approve', 'Chấp thuận']] },
      { id: 'd16e6', type: 'pronunciation', question: 'Common PR phrase', audioText: 'What was the thinking here', correct: 'what was the thinking here', hint: '/wɒt wɒz ðə ˈθɪŋkɪŋ hɪər/' },
    ],
  },
  {
    day: 17,
    title: 'Stand-up & Syncs',
    subtitle: 'Daily stand-up và cuộc họp ngắn',
    theme: 'tech',
    emoji: '📢',
    gradient: ['#10B981', '#06B6D4'],
    xpReward: 140,
    vocabulary: [
      { word: "Yesterday I worked on...", phonetic: '/ˈjɛstərdeɪ aɪ ˈwɜːrkt ɒn/', translation: 'Hôm qua tôi đã làm...', example: 'Yesterday I worked on the login bug fix.', exampleTranslation: 'Hôm qua tôi đã làm sửa bug login.' },
      { word: "Today I'm going to...", phonetic: '/təˈdeɪ aɪm ˈɡoʊɪŋ tuː/', translation: 'Hôm nay tôi sẽ...', example: "Today I'm going to finish the user dashboard.", exampleTranslation: 'Hôm nay tôi sẽ hoàn thành dashboard người dùng.' },
      { word: 'Blocked', phonetic: '/blɒkt/', translation: 'Đang bị chặn / cần giúp đỡ', example: "I'm blocked on the payment integration — waiting for API keys.", exampleTranslation: 'Tôi đang bị chặn ở phần tích hợp thanh toán — chờ API keys.' },
      { word: 'Ship it', phonetic: '/ʃɪp ɪt/', translation: 'Triển khai / release nó', example: "The feature is ready — let's ship it.", exampleTranslation: 'Tính năng đã sẵn sàng — triển khai thôi.' },
      { word: 'In progress', phonetic: '/ɪn ˈprɒɡrɛs/', translation: 'Đang làm', example: 'The refactoring is still in progress.', exampleTranslation: 'Việc refactoring vẫn đang làm.' },
      { word: 'Heads up', phonetic: '/hɛdz ʌp/', translation: 'Thông báo trước / cảnh báo', example: 'Heads up — I will be OOO tomorrow.', exampleTranslation: 'Thông báo trước — tôi sẽ vắng mặt ngày mai.' },
    ],
    exercises: [
      { id: 'd17e1', type: 'multiple-choice', question: 'In a stand-up, "I am blocked" means:', options: ['I finished my task', "I can't proceed without help", 'I have no tasks', 'I am in a meeting'], correct: "I can't proceed without help" },
      { id: 'd17e2', type: 'word-order', question: 'Arrange the stand-up update', words: ['going', "I'm", 'Today', 'finish', 'to', 'the', 'API', 'integration'], correct: "Today I'm going to finish the API integration" },
      { id: 'd17e3', type: 'fill-blank', question: "___ — the staging server will be down for 30 minutes at 3 PM.", options: ['Blocked', 'Heads up', 'Ship it', 'In progress'], correct: 'Heads up', hint: 'Warning others about something upcoming' },
      { id: 'd17e4', type: 'listen-choose', question: 'Listen and choose', audioText: "I'm blocked on the payment integration, waiting for API keys from the backend team", options: ["I'm blocked on the payment integration, waiting for API keys from the backend team", "I'm stuck on the payment integration, waiting for API keys from the backend team", "I'm blocked on the auth integration, waiting for API keys from the backend team", "I'm blocked on the payment integration, waiting for credentials from the backend team"], correct: "I'm blocked on the payment integration, waiting for API keys from the backend team" },
      { id: 'd17e5', type: 'word-match', question: 'Match stand-up terms', correct: 'matched', pairs: [['Blocked', 'Cần giúp để tiếp tục'], ['Ship it', 'Triển khai/release'], ['In progress', 'Đang làm'], ['Heads up', 'Thông báo trước'], ['OOO', 'Out of office']] },
      { id: 'd17e6', type: 'pronunciation', question: 'Stand-up phrase', audioText: "Today I'm going to ship the new feature", correct: "today i'm going to ship the new feature", hint: 'Speak naturally, not word by word' },
    ],
  },
  {
    day: 18,
    title: 'Debugging & Problem Solving',
    subtitle: 'Nói về bugs và lỗi kỹ thuật',
    theme: 'tech',
    emoji: '🐛',
    gradient: ['#EF4444', '#F97316'],
    xpReward: 150,
    vocabulary: [
      { word: 'Reproduce the issue', phonetic: '/ˌriːprəˈdjuːs ðə ˈɪʃuː/', translation: 'Tái hiện lỗi', example: "I can't reproduce the issue on my machine.", exampleTranslation: 'Tôi không thể tái hiện lỗi này trên máy của tôi.' },
      { word: 'Root cause', phonetic: '/ruːt kɔːz/', translation: 'Nguyên nhân gốc rễ', example: 'The root cause was a race condition in the async handler.', exampleTranslation: 'Nguyên nhân gốc rễ là race condition trong async handler.' },
      { word: 'Workaround', phonetic: '/ˈwɜːrkəraʊnd/', translation: 'Giải pháp tạm thời', example: "It's not a fix — just a workaround until we patch it properly.", exampleTranslation: 'Đây không phải sửa thật — chỉ là giải pháp tạm thời cho đến khi vá đúng cách.' },
      { word: 'Edge case', phonetic: '/ɛdʒ keɪs/', translation: 'Trường hợp ngoại lệ', example: "This edge case wasn't covered in the tests.", exampleTranslation: 'Trường hợp ngoại lệ này chưa được bao gồm trong test.' },
      { word: 'Regression', phonetic: '/rɪˈɡrɛʃən/', translation: 'Lỗi hồi quy (bug mới từ fix cũ)', example: 'The last deploy introduced a regression in the checkout flow.', exampleTranslation: 'Deploy lần trước đã tạo ra lỗi hồi quy trong checkout flow.' },
      { word: 'Stack trace', phonetic: '/stæk treɪs/', translation: 'Dấu vết lỗi / log lỗi', example: 'Can you share the full stack trace from the error?', exampleTranslation: 'Bạn có thể chia sẻ stack trace đầy đủ từ lỗi không?' },
    ],
    exercises: [
      { id: 'd18e1', type: 'multiple-choice', question: 'A "regression" in software means:', options: ['A performance improvement', 'A new bug caused by a recent change', 'A planned feature', 'A database error'], correct: 'A new bug caused by a recent change' },
      { id: 'd18e2', type: 'word-order', question: 'Arrange the sentence', words: ['cause', 'The', 'was', 'root', 'a', 'condition', 'race'], correct: 'The root cause was a race condition' },
      { id: 'd18e3', type: 'fill-blank', question: "This ___ wasn't covered in our tests — it only happens with empty arrays.", options: ['bug', 'edge case', 'regression', 'error'], correct: 'edge case' },
      { id: 'd18e4', type: 'listen-choose', question: 'Listen and choose', audioText: "I can't reproduce the issue on my machine, can you share the stack trace", options: ["I can't reproduce the issue on my machine, can you share the stack trace", "I can't replicate the issue on my machine, can you share the stack trace", "I can't reproduce the error on my machine, can you share the stack trace", "I can't reproduce the issue on your machine, can you share the stack trace"], correct: "I can't reproduce the issue on my machine, can you share the stack trace" },
      { id: 'd18e5', type: 'word-match', question: 'Match debugging terms', correct: 'matched', pairs: [['Root cause', 'Nguyên nhân gốc'], ['Workaround', 'Giải pháp tạm'], ['Edge case', 'Trường hợp ngoại lệ'], ['Regression', 'Bug do fix cũ gây ra'], ['Stack trace', 'Log lỗi']] },
      { id: 'd18e6', type: 'pronunciation', question: 'Debugging vocabulary', audioText: 'regression', correct: 'regression', hint: '/rɪˈɡrɛʃən/ — stress on "GRESH"' },
    ],
  },
  {
    day: 19,
    title: 'Tech Slang & Acronyms',
    subtitle: 'Tiếng lóng và viết tắt thông dụng',
    theme: 'tech',
    emoji: '💬',
    gradient: ['#8B5CF6', '#EC4899'],
    xpReward: 140,
    vocabulary: [
      { word: 'TL;DR', phonetic: '/tiː ɛl diː ɑːr/', translation: 'Too long; didn\'t read — tóm lại', example: 'TL;DR — the new API is faster but has breaking changes.', exampleTranslation: 'Tóm lại — API mới nhanh hơn nhưng có breaking changes.' },
      { word: 'EOD / EOM', phonetic: '/iː oʊ diː/', translation: 'End of day / end of month', example: 'I need this report by EOD Friday.', exampleTranslation: 'Tôi cần báo cáo này trước cuối ngày thứ Sáu.' },
      { word: 'FYI', phonetic: '/ɛf waɪ aɪ/', translation: 'For your information — để bạn biết', example: 'FYI — the staging server will be down tonight.', exampleTranslation: 'Để bạn biết — staging server sẽ bị tắt tối nay.' },
      { word: 'Ping me', phonetic: '/pɪŋ miː/', translation: 'Nhắn tin / liên hệ cho tôi', example: 'Ping me when the PR is ready for review.', exampleTranslation: 'Nhắn tin cho tôi khi PR sẵn sàng để review.' },
      { word: 'Loop in', phonetic: '/luːp ɪn/', translation: 'Thêm ai vào (CC / tag)', example: 'Can you loop in Sarah on this email?', exampleTranslation: 'Bạn có thể thêm Sarah vào email này không?' },
      { word: 'Bandwidth', phonetic: '/ˈbændwɪdθ/', translation: 'Khả năng / thời gian rảnh (nghĩa bóng)', example: "I don't have the bandwidth to take on another project right now.", exampleTranslation: 'Tôi không có thời gian để nhận thêm dự án khác ngay bây giờ.' },
    ],
    exercises: [
      { id: 'd19e1', type: 'multiple-choice', question: 'A colleague says "I don\'t have the bandwidth for this." What do they mean?', options: ["Their internet is slow", "They are too busy / don't have capacity", "They need more information", "They disagree with the plan"], correct: "They are too busy / don't have capacity" },
      { id: 'd19e2', type: 'fill-blank', question: '___ — the new deploy broke the login page on mobile.', options: ['LGTM', 'TL;DR', 'FYI', 'EOD'], correct: 'FYI', hint: 'Sharing useful info, not requesting action' },
      { id: 'd19e3', type: 'word-order', question: 'Arrange the Slack message', words: ['in', 'Can', 'you', 'loop', 'David', 'on', 'this', '?'], correct: 'Can you loop in David on this ?' },
      { id: 'd19e4', type: 'listen-choose', question: 'Listen and choose', audioText: 'Ping me when the build is green and I will approve the PR', options: ['Ping me when the build is green and I will approve the PR', 'Message me when the build is green and I will approve the PR', 'Ping me when the build is done and I will approve the PR', 'Ping me when the build is green and I will review the PR'], correct: 'Ping me when the build is green and I will approve the PR' },
      { id: 'd19e5', type: 'word-match', question: 'Match tech slang', correct: 'matched', pairs: [['TL;DR', 'Tóm lại'], ['EOD', 'Cuối ngày'], ['Loop in', 'Thêm vào cuộc trò chuyện'], ['Bandwidth', 'Khả năng/thời gian'], ['Ping me', 'Liên hệ cho tôi']] },
      { id: 'd19e6', type: 'pronunciation', question: 'Slack phrase', audioText: "I don't have the bandwidth for this right now", correct: "i don't have the bandwidth for this right now", hint: 'Natural connected speech' },
    ],
  },
  {
    day: 20,
    title: 'Presentations & Demos',
    subtitle: 'Thuyết trình và demo sản phẩm',
    theme: 'tech',
    emoji: '🎯',
    gradient: ['#F59E0B', '#EF4444'],
    xpReward: 150,
    vocabulary: [
      { word: "Let me show you...", phonetic: '/lɛt miː ʃoʊ juː/', translation: 'Để tôi chỉ cho bạn xem...', example: "Let me show you how the new feature works.", exampleTranslation: 'Để tôi chỉ cho bạn xem tính năng mới hoạt động thế nào.' },
      { word: "Bear with me", phonetic: '/bɛər wɪð miː/', translation: 'Chờ tôi một chút', example: "Bear with me while I pull up the dashboard.", exampleTranslation: 'Chờ tôi một chút trong khi tôi mở dashboard lên.' },
      { word: 'As you can see', phonetic: '/æz juː kæn siː/', translation: 'Như bạn có thể thấy', example: 'As you can see, the response time dropped by 40%.', exampleTranslation: 'Như bạn có thể thấy, thời gian phản hồi đã giảm 40%.' },
      { word: 'To summarize', phonetic: '/tuː ˈsʌməraɪz/', translation: 'Để tóm tắt lại', example: 'To summarize, we shipped three new features this sprint.', exampleTranslation: 'Để tóm tắt lại, chúng tôi đã release ba tính năng mới trong sprint này.' },
      { word: 'Does anyone have questions?', phonetic: '/dʌz ˈɛniwʌn hæv ˈkwɛstʃənz/', translation: 'Ai có câu hỏi không?', example: 'That covers the demo. Does anyone have questions?', exampleTranslation: 'Đó là phần demo. Ai có câu hỏi không?' },
      { word: 'The key takeaway is', phonetic: '/ðə kiː ˈteɪkəweɪ ɪz/', translation: 'Điều quan trọng cần nhớ là', example: 'The key takeaway is: we cut load time in half.', exampleTranslation: 'Điều quan trọng cần nhớ là: chúng tôi đã cắt giảm thời gian tải xuống một nửa.' },
    ],
    exercises: [
      { id: 'd20e1', type: 'multiple-choice', question: '"Bear with me" in a presentation means:', options: ['I disagree', 'Please be patient', 'I have a bear', 'Start without me'], correct: 'Please be patient' },
      { id: 'd20e2', type: 'word-order', question: 'Arrange the presentation phrase', words: ['can', 'As', 'see', 'you', 'the', 'time', 'load', 'dropped'], correct: 'As you can see the load time dropped' },
      { id: 'd20e3', type: 'fill-blank', question: '___ — we reduced the number of API calls by 60%.', options: ['As you can see', 'Bear with me', 'The key takeaway is', 'Let me show you'], correct: 'The key takeaway is' },
      { id: 'd20e4', type: 'listen-choose', question: 'Listen and choose', audioText: 'Bear with me while I pull up the live demo on the staging server', options: ['Bear with me while I pull up the live demo on the staging server', 'Bear with me while I set up the live demo on the staging server', 'Wait for me while I pull up the live demo on the staging server', 'Bear with me while I pull up the demo on the production server'], correct: 'Bear with me while I pull up the live demo on the staging server' },
      { id: 'd20e5', type: 'word-match', question: 'Match presentation phrases', correct: 'matched', pairs: [['Bear with me', 'Chờ tôi một chút'], ['As you can see', 'Như bạn thấy'], ['To summarize', 'Tóm tắt lại'], ['Key takeaway', 'Điểm quan trọng'], ['Does anyone have questions?', 'Có câu hỏi không?']] },
      { id: 'd20e6', type: 'pronunciation', question: 'Closing a demo', audioText: 'That covers the demo, does anyone have questions', correct: 'that covers the demo does anyone have questions', hint: 'Slightly falling intonation at the end' },
    ],
  },
  {
    day: 21,
    title: 'Week 3 Review',
    subtitle: 'Ôn tập tuần 3 — Tech Communication',
    theme: 'review',
    emoji: '⭐',
    gradient: ['#6366F1', '#8B5CF6'],
    xpReward: 160,
    vocabulary: [
      { word: 'Trade-off', phonetic: '/ˈtreɪd ɒf/', translation: 'Sự đánh đổi', example: "There's always a trade-off between speed and code quality.", exampleTranslation: 'Luôn có sự đánh đổi giữa tốc độ và chất lượng code.' },
      { word: 'Scalable', phonetic: '/ˈskeɪləbl/', translation: 'Có thể mở rộng quy mô', example: 'Is this architecture scalable for 10 million users?', exampleTranslation: 'Kiến trúc này có thể mở rộng cho 10 triệu người dùng không?' },
      { word: 'Bottleneck', phonetic: '/ˈbɒtlnɛk/', translation: 'Điểm nghẽn cổ chai', example: 'The database query is the bottleneck in our system.', exampleTranslation: 'Truy vấn database là điểm nghẽn trong hệ thống của chúng tôi.' },
      { word: 'Refactor', phonetic: '/ˌriːˈfæktər/', translation: 'Tái cấu trúc code', example: "We need to refactor this before it becomes a bigger problem.", exampleTranslation: 'Chúng ta cần tái cấu trúc cái này trước khi nó trở thành vấn đề lớn hơn.' },
      { word: 'Deploy', phonetic: '/dɪˈplɔɪ/', translation: 'Triển khai (lên server)', example: 'We deploy to production every Friday at 5 PM.', exampleTranslation: 'Chúng tôi deploy lên production mỗi thứ Sáu lúc 5 giờ chiều.' },
      { word: 'Tech debt', phonetic: '/tɛk dɛt/', translation: 'Nợ kỹ thuật', example: "We've been ignoring tech debt for too long.", exampleTranslation: 'Chúng ta đã bỏ qua nợ kỹ thuật quá lâu rồi.' },
    ],
    exercises: [
      { id: 'd21e1', type: 'multiple-choice', question: '"Tech debt" refers to:', options: ['Money owed to technology vendors', 'Shortcuts taken now that create more work later', 'Slow internet connection', 'Outdated hardware'], correct: 'Shortcuts taken now that create more work later' },
      { id: 'd21e2', type: 'word-order', question: 'Arrange the sentence', words: ['always', "There's", 'a', 'trade-off', 'speed', 'between', 'and', 'quality'], correct: "There's always a trade-off between speed and quality" },
      { id: 'd21e3', type: 'word-match', question: 'Review: tech vocabulary', correct: 'matched', pairs: [['Bottleneck', 'Điểm nghẽn'], ['Scalable', 'Mở rộng được'], ['Refactor', 'Tái cấu trúc code'], ['Tech debt', 'Nợ kỹ thuật'], ['Deploy', 'Triển khai']] },
      { id: 'd21e4', type: 'fill-blank', question: 'The database is the ___ — all requests slow down there.', options: ['edge case', 'bottleneck', 'regression', 'trade-off'], correct: 'bottleneck' },
      { id: 'd21e5', type: 'listen-choose', question: 'Listen and choose', audioText: "We need to refactor this service before we scale, otherwise it will become a bottleneck", options: ["We need to refactor this service before we scale, otherwise it will become a bottleneck", "We need to refactor this service before we launch, otherwise it will become a bottleneck", "We should refactor this service before we scale, otherwise it will become a bottleneck", "We need to rewrite this service before we scale, otherwise it will become a bottleneck"], correct: "We need to refactor this service before we scale, otherwise it will become a bottleneck" },
      { id: 'd21e6', type: 'pronunciation', question: 'Key tech word', audioText: 'scalable', correct: 'scalable', hint: '/ˈskeɪləbl/ — stress on "SCALE"' },
    ],
  },

  // ── WEEK 4: Career English ────────────────────────────────────────────────
  {
    day: 22,
    title: 'Job Interviews',
    subtitle: 'Phỏng vấn xin việc',
    theme: 'career',
    emoji: '👔',
    gradient: ['#0EA5E9', '#6366F1'],
    xpReward: 160,
    vocabulary: [
      { word: 'Tell me about yourself', phonetic: '/tɛl miː əˈbaʊt jɔːrsɛlf/', translation: 'Hãy giới thiệu về bản thân', example: "Tell me about yourself and your experience with React.", exampleTranslation: 'Hãy giới thiệu về bản thân và kinh nghiệm React của bạn.' },
      { word: "I have X years of experience in", phonetic: '/aɪ hæv ɪkˈspɪəriəns ɪn/', translation: 'Tôi có X năm kinh nghiệm trong', example: 'I have 4 years of experience in backend development.', exampleTranslation: 'Tôi có 4 năm kinh nghiệm trong phát triển backend.' },
      { word: 'My greatest strength is', phonetic: '/maɪ ˈɡreɪtɪst strɛŋθ ɪz/', translation: 'Điểm mạnh lớn nhất của tôi là', example: 'My greatest strength is breaking down complex problems.', exampleTranslation: 'Điểm mạnh lớn nhất của tôi là phân tích vấn đề phức tạp.' },
      { word: 'I am passionate about', phonetic: '/aɪ æm ˈpæʃənɪt əˈbaʊt/', translation: 'Tôi rất đam mê', example: 'I am passionate about building products that people actually use.', exampleTranslation: 'Tôi rất đam mê xây dựng sản phẩm mà mọi người thực sự dùng.' },
      { word: 'Could you tell me more about the team?', phonetic: '/kʊd juː tɛl miː mɔːr/', translation: 'Bạn có thể cho tôi biết thêm về team không?', example: 'Could you tell me more about the engineering team structure?', exampleTranslation: 'Bạn có thể cho tôi biết thêm về cơ cấu team kỹ thuật không?' },
      { word: "I'd like to follow up", phonetic: '/aɪd laɪk tuː ˈfɒloʊ ʌp/', translation: 'Tôi muốn hỏi thêm / tiếp tục theo dõi', example: "I'd like to follow up on my application from last week.", exampleTranslation: 'Tôi muốn hỏi thêm về đơn ứng tuyển của tôi tuần trước.' },
    ],
    exercises: [
      { id: 'd22e1', type: 'multiple-choice', question: 'The best way to answer "Tell me about yourself" is:', options: ['Talk about your childhood', 'Summarize your relevant experience and why you fit the role', 'List all your hobbies', 'Ask what they want to know'], correct: 'Summarize your relevant experience and why you fit the role' },
      { id: 'd22e2', type: 'word-order', question: 'Arrange the interview answer', words: ['have', 'I', 'years', 'of', 'experience', 'three', 'in', 'full-stack', 'development'], correct: 'I have three years of experience in full-stack development' },
      { id: 'd22e3', type: 'fill-blank', question: "My greatest ___ is staying calm under pressure and delivering on time.", options: ['weakness', 'strength', 'experience', 'skill'], correct: 'strength' },
      { id: 'd22e4', type: 'listen-choose', question: 'Listen and choose', audioText: "I am passionate about building scalable systems and I would love to learn more about how your team approaches architecture", options: ["I am passionate about building scalable systems and I would love to learn more about how your team approaches architecture", "I am passionate about building scalable systems and I would like to learn more about how your team approaches architecture", "I am excited about building scalable systems and I would love to learn more about how your team approaches architecture", "I am passionate about building reliable systems and I would love to learn more about how your team approaches architecture"], correct: "I am passionate about building scalable systems and I would love to learn more about how your team approaches architecture" },
      { id: 'd22e5', type: 'word-match', question: 'Match interview phrases', correct: 'matched', pairs: [['Tell me about yourself', 'Giới thiệu bản thân'], ['Greatest strength', 'Điểm mạnh nhất'], ['Passionate about', 'Đam mê về'], ['Follow up', 'Hỏi thêm/theo dõi'], ['Years of experience', 'Năm kinh nghiệm']] },
      { id: 'd22e6', type: 'pronunciation', question: 'Interview opener', audioText: "I have four years of experience in backend development", correct: "i have four years of experience in backend development", hint: 'Confident, steady pace — not too fast' },
    ],
  },
  {
    day: 23,
    title: 'Salary Negotiation',
    subtitle: 'Thương lượng lương và đãi ngộ',
    theme: 'career',
    emoji: '💰',
    gradient: ['#10B981', '#F59E0B'],
    xpReward: 170,
    vocabulary: [
      { word: 'What is the salary range?', phonetic: '/wɒt ɪz ðə ˈsæləri reɪndʒ/', translation: 'Mức lương dự kiến là bao nhiêu?', example: 'Could you share the salary range for this position?', exampleTranslation: 'Bạn có thể chia sẻ mức lương dự kiến cho vị trí này không?' },
      { word: 'Based on my experience', phonetic: '/beɪst ɒn maɪ ɪkˈspɪəriəns/', translation: 'Dựa trên kinh nghiệm của tôi', example: 'Based on my experience and market rates, I was expecting around $X.', exampleTranslation: 'Dựa trên kinh nghiệm của tôi và mức thị trường, tôi kỳ vọng khoảng $X.' },
      { word: 'Is there room to negotiate?', phonetic: '/ɪz ðɛər ruːm tuː nɪˈɡoʊʃieɪt/', translation: 'Có thể thương lượng không?', example: "That's a bit below my expectation. Is there room to negotiate?", exampleTranslation: 'Mức đó hơi thấp hơn kỳ vọng của tôi. Có thể thương lượng không?' },
      { word: 'Benefits package', phonetic: '/ˈbɛnɪfɪts ˈpækɪdʒ/', translation: 'Gói phúc lợi', example: "Can you walk me through the benefits package?", exampleTranslation: 'Bạn có thể giải thích gói phúc lợi cho tôi không?' },
      { word: 'Counter offer', phonetic: '/ˈkaʊntər ˈɒfər/', translation: 'Đề nghị ngược lại', example: 'I have a counter offer from another company.', exampleTranslation: 'Tôi có đề nghị ngược lại từ một công ty khác.' },
      { word: "I'd like time to consider", phonetic: '/aɪd laɪk taɪm tuː kənˈsɪdər/', translation: 'Tôi muốn có thời gian suy nghĩ', example: "This is exciting — I'd like a day or two to consider the full offer.", exampleTranslation: 'Đây là điều thú vị — Tôi muốn một hai ngày để suy nghĩ về toàn bộ đề nghị.' },
    ],
    exercises: [
      { id: 'd23e1', type: 'multiple-choice', question: 'You receive a job offer. The salary is lower than expected. What is the most professional response?', options: ['Reject immediately', 'Accept without question', 'Say "Is there room to negotiate?"', 'Ask for double the amount'], correct: 'Say "Is there room to negotiate?"' },
      { id: 'd23e2', type: 'word-order', question: 'Arrange the negotiation sentence', words: ['my', 'on', 'Based', 'experience', 'expecting', 'was', 'I', 'more'], correct: 'Based on my experience I was expecting more' },
      { id: 'd23e3', type: 'fill-blank', question: "Could you walk me through the ___ package — health insurance, equity, vacation days?", options: ['salary', 'benefits', 'bonus', 'contract'], correct: 'benefits' },
      { id: 'd23e4', type: 'listen-choose', question: 'Listen and choose', audioText: "This is a great opportunity and I'm very interested, but I'd like a day to review the full offer", options: ["This is a great opportunity and I'm very interested, but I'd like a day to review the full offer", "This is a great opportunity and I'm very interested, but I'd like a week to review the full offer", "This is a good opportunity and I'm very interested, but I'd like a day to review the full offer", "This is a great opportunity and I'm very interested, but I need a day to review the full offer"], correct: "This is a great opportunity and I'm very interested, but I'd like a day to review the full offer" },
      { id: 'd23e5', type: 'word-match', question: 'Match negotiation terms', correct: 'matched', pairs: [['Salary range', 'Khoảng lương'], ['Benefits package', 'Gói phúc lợi'], ['Counter offer', 'Đề nghị ngược lại'], ['Room to negotiate', 'Khả năng thương lượng'], ['Consider', 'Suy nghĩ, cân nhắc']] },
      { id: 'd23e6', type: 'pronunciation', question: 'Negotiation opener', audioText: 'Is there room to negotiate on the base salary', correct: 'is there room to negotiate on the base salary', hint: 'Calm, confident tone — not aggressive' },
    ],
  },
  {
    day: 24,
    title: 'Networking',
    subtitle: 'Kết nối chuyên nghiệp',
    theme: 'career',
    emoji: '🤝',
    gradient: ['#EC4899', '#8B5CF6'],
    xpReward: 160,
    vocabulary: [
      { word: "What do you do?", phonetic: '/wɒt duː juː duː/', translation: 'Bạn làm nghề gì?', example: "Hi, I'm Anh. What do you do?", exampleTranslation: 'Xin chào, tôi là Anh. Bạn làm nghề gì?' },
      { word: "I work at / I work in", phonetic: '/aɪ wɜːrk æt/', translation: 'Tôi làm ở / tôi làm trong lĩnh vực', example: 'I work at a fintech startup in Ho Chi Minh City.', exampleTranslation: 'Tôi làm ở một startup fintech ở TP. Hồ Chí Minh.' },
      { word: "Let's keep in touch", phonetic: '/lɛts kiːp ɪn tʌtʃ/', translation: 'Hãy giữ liên lạc', example: "It was great meeting you — let's keep in touch on LinkedIn.", exampleTranslation: 'Rất vui được gặp bạn — hãy giữ liên lạc trên LinkedIn.' },
      { word: 'I came across your work', phonetic: '/aɪ keɪm əˈkrɒs jɔːr wɜːrk/', translation: 'Tôi tình cờ thấy công việc của bạn', example: 'I came across your GitHub and your open source work is impressive.', exampleTranslation: 'Tôi tình cờ thấy GitHub của bạn và công việc open source của bạn rất ấn tượng.' },
      { word: 'Coffee chat', phonetic: '/ˈkɒfi tʃæt/', translation: 'Gặp gỡ không chính thức để nói chuyện', example: 'Would you be open to a quick coffee chat this week?', exampleTranslation: 'Bạn có sẵn lòng gặp gỡ nói chuyện ngắn tuần này không?' },
      { word: 'Mutual connection', phonetic: '/ˈmjuːtʃuəl kəˈnɛkʃən/', translation: 'Mối quan hệ chung', example: "We have a mutual connection — I know Sarah from the last conference.", exampleTranslation: 'Chúng ta có mối quan hệ chung — tôi quen Sarah từ hội thảo lần trước.' },
    ],
    exercises: [
      { id: 'd24e1', type: 'multiple-choice', question: 'The best LinkedIn message to connect with someone you admire is:', options: ["Please give me a job", "Hi, I came across your work on X and really admire it — would love to connect", "Add me please", "I need your advice"], correct: "Hi, I came across your work on X and really admire it — would love to connect" },
      { id: 'd24e2', type: 'word-order', question: 'Arrange the networking phrase', words: ['open', 'you', 'be', 'Would', 'to', 'a', 'coffee', 'chat', '?'], correct: 'Would you be open to a coffee chat ?' },
      { id: 'd24e3', type: 'fill-blank', question: "It was great meeting you — let's ___ on LinkedIn.", options: ['connect', 'keep in touch', 'follow', 'message'], correct: 'keep in touch' },
      { id: 'd24e4', type: 'listen-choose', question: 'Listen and choose', audioText: "Hi, I came across your talk at the conference and I'd love to grab a coffee chat if you have time", options: ["Hi, I came across your talk at the conference and I'd love to grab a coffee chat if you have time", "Hi, I saw your talk at the conference and I'd love to grab a coffee chat if you have time", "Hi, I came across your talk at the conference and I'd like to grab a coffee chat if you have time", "Hi, I came across your talk at the meetup and I'd love to grab a coffee chat if you have time"], correct: "Hi, I came across your talk at the conference and I'd love to grab a coffee chat if you have time" },
      { id: 'd24e5', type: 'word-match', question: 'Match networking vocab', correct: 'matched', pairs: [['Coffee chat', 'Gặp nói chuyện ngắn'], ['Keep in touch', 'Giữ liên lạc'], ['Mutual connection', 'Quen biết chung'], ['Came across', 'Tình cờ tìm thấy'], ['What do you do?', 'Bạn làm nghề gì?']] },
      { id: 'd24e6', type: 'pronunciation', question: 'Networking intro', audioText: "I work at a startup focused on developer tools", correct: "i work at a startup focused on developer tools", hint: 'Confident, friendly tone' },
    ],
  },
  {
    day: 25,
    title: 'Giving Feedback',
    subtitle: 'Đưa ra và nhận phản hồi xây dựng',
    theme: 'career',
    emoji: '📝',
    gradient: ['#F97316', '#EF4444'],
    xpReward: 160,
    vocabulary: [
      { word: 'I appreciate that, and...', phonetic: '/aɪ əˈpriːʃieɪt ðæt ænd/', translation: 'Tôi đánh giá cao điều đó, và...', example: "I appreciate that, and I think we can push it further.", exampleTranslation: 'Tôi đánh giá cao điều đó, và tôi nghĩ chúng ta có thể đẩy xa hơn.' },
      { word: 'One thing I noticed is', phonetic: '/wʌn θɪŋ aɪ ˈnoʊtɪst ɪz/', translation: 'Một điều tôi để ý là', example: 'One thing I noticed is that the deadlines keep slipping.', exampleTranslation: 'Một điều tôi để ý là deadline cứ bị trễ dần.' },
      { word: "I'm open to feedback", phonetic: '/aɪm ˈoʊpən tuː ˈfiːdbæk/', translation: 'Tôi sẵn sàng lắng nghe phản hồi', example: "I'm open to feedback — what would you have done differently?", exampleTranslation: 'Tôi sẵn sàng lắng nghe phản hồi — bạn sẽ làm khác đi thế nào?' },
      { word: 'Moving forward', phonetic: '/ˈmuːvɪŋ ˈfɔːrwərd/', translation: 'Trong tương lai / từ đây về sau', example: 'Moving forward, please communicate blockers earlier.', exampleTranslation: 'Từ đây về sau, hãy thông báo sớm hơn khi bị chặn.' },
      { word: 'That said', phonetic: '/ðæt sɛd/', translation: 'Tuy nhiên / dù vậy', example: "Great work overall. That said, the documentation needs improvement.", exampleTranslation: 'Nhìn chung là tốt. Tuy nhiên, phần tài liệu cần cải thiện.' },
      { word: 'Constructive criticism', phonetic: '/kənˈstrʌktɪv ˈkrɪtɪsɪzəm/', translation: 'Phê bình xây dựng', example: 'I value constructive criticism — it helps me grow.', exampleTranslation: 'Tôi trân trọng phê bình xây dựng — nó giúp tôi phát triển.' },
    ],
    exercises: [
      { id: 'd25e1', type: 'multiple-choice', question: '"That said" is used to:', options: ['Agree completely', 'End the conversation', 'Introduce a contrasting point politely', 'Ask a question'], correct: 'Introduce a contrasting point politely' },
      { id: 'd25e2', type: 'word-order', question: 'Arrange the feedback phrase', words: ['forward', 'Moving', 'communicate', 'please', 'blockers', 'earlier'], correct: 'Moving forward please communicate blockers earlier' },
      { id: 'd25e3', type: 'fill-blank', question: "Great presentation! ___, I'd recommend adding more data to support the main claim.", options: ['Therefore', 'That said', "Moving forward", "I appreciate that"], correct: 'That said' },
      { id: 'd25e4', type: 'listen-choose', question: 'Listen and choose', audioText: "One thing I noticed is that the estimates are consistently off, moving forward let's add buffer time", options: ["One thing I noticed is that the estimates are consistently off, moving forward let's add buffer time", "One thing I noticed is that the deadlines are consistently off, moving forward let's add buffer time", "One thing I noticed is that the estimates are always off, moving forward let's add buffer time", "One thing I noticed is that the estimates are consistently off, in future let's add buffer time"], correct: "One thing I noticed is that the estimates are consistently off, moving forward let's add buffer time" },
      { id: 'd25e5', type: 'word-match', question: 'Match feedback phrases', correct: 'matched', pairs: [['That said', 'Tuy nhiên'], ['Moving forward', 'Từ đây về sau'], ['One thing I noticed', 'Một điều tôi để ý'], ["I'm open to feedback", 'Sẵn sàng nghe góp ý'], ['Constructive criticism', 'Phê bình xây dựng']] },
      { id: 'd25e6', type: 'pronunciation', question: 'Feedback phrase', audioText: "I appreciate the effort, that said there's room to improve the documentation", correct: "i appreciate the effort that said there's room to improve the documentation", hint: 'Warm tone — critical but supportive' },
    ],
  },
  {
    day: 26,
    title: 'Remote Work & Video Calls',
    subtitle: 'Làm việc từ xa và họp online',
    theme: 'career',
    emoji: '💻',
    gradient: ['#06B6D4', '#10B981'],
    xpReward: 150,
    vocabulary: [
      { word: "You're on mute", phonetic: '/jɔːr ɒn mjuːt/', translation: 'Bạn đang tắt mic', example: "Sorry, I think you're on mute — can't hear you.", exampleTranslation: 'Xin lỗi, tôi nghĩ bạn đang tắt mic — tôi không nghe thấy bạn.' },
      { word: 'Can you share your screen?', phonetic: '/kæn juː ʃɛər jɔːr skriːn/', translation: 'Bạn có thể chia sẻ màn hình không?', example: 'Can you share your screen so we can follow along?', exampleTranslation: 'Bạn có thể chia sẻ màn hình để chúng tôi theo dõi không?' },
      { word: 'Bad connection', phonetic: '/bæd kəˈnɛkʃən/', translation: 'Kết nối kém', example: "Sorry, I have a bad connection — can you repeat that?", exampleTranslation: 'Xin lỗi, tôi có kết nối kém — bạn có thể nhắc lại không?' },
      { word: 'Async', phonetic: '/ˈeɪsɪŋk/', translation: 'Không đồng bộ / không cần trả lời ngay', example: "Let's handle this async — I'll document it and share in Slack.", exampleTranslation: 'Hãy xử lý cái này async — tôi sẽ ghi lại và chia sẻ trên Slack.' },
      { word: 'Take this offline', phonetic: '/teɪk ðɪs ˈɒflaɪn/', translation: 'Thảo luận riêng sau', example: "That's a long topic — let's take it offline and schedule a separate call.", exampleTranslation: 'Đó là chủ đề dài — hãy thảo luận riêng và đặt cuộc gọi riêng.' },
      { word: 'End-of-day update', phonetic: '/ɛnd ɒv deɪ ˈʌpdeɪt/', translation: 'Cập nhật cuối ngày', example: "I'll send an end-of-day update on where things stand.", exampleTranslation: 'Tôi sẽ gửi cập nhật cuối ngày về tiến độ mọi việc.' },
    ],
    exercises: [
      { id: 'd26e1', type: 'multiple-choice', question: '"Let\'s take this offline" in a meeting means:', options: ['Shut down the laptop', 'Discuss this in a separate conversation later', 'Cancel the meeting', 'Work without internet'], correct: 'Discuss this in a separate conversation later' },
      { id: 'd26e2', type: 'word-order', question: 'Arrange the video call phrase', words: ['share', 'Can', 'you', 'screen', 'your', 'so', 'we', 'can', 'follow', '?'], correct: 'Can you share your screen so we can follow ?' },
      { id: 'd26e3', type: 'fill-blank', question: "Sorry, I have a bad ___ — could you say that again?", options: ['wifi', 'sound', 'connection', 'signal'], correct: 'connection' },
      { id: 'd26e4', type: 'listen-choose', question: 'Listen and choose', audioText: "Hey, I think you're on mute, we can see you but can't hear anything", options: ["Hey, I think you're on mute, we can see you but can't hear anything", "Hey, I think you're on mute, we can hear you but can't see anything", "Hey, I think you're on mute, we can see you but can't hear you", "Sorry, I think you're on mute, we can see you but can't hear anything"], correct: "Hey, I think you're on mute, we can see you but can't hear anything" },
      { id: 'd26e5', type: 'word-match', question: 'Match remote work terms', correct: 'matched', pairs: [["You're on mute", 'Đang tắt mic'], ['Take it offline', 'Thảo luận riêng sau'], ['Async', 'Không cần trả lời ngay'], ['EOD update', 'Cập nhật cuối ngày'], ['Bad connection', 'Kết nối kém']] },
      { id: 'd26e6', type: 'pronunciation', question: 'Video call phrase', audioText: "Can you share your screen, I want to walk everyone through the design", correct: "can you share your screen i want to walk everyone through the design", hint: 'Clear and direct' },
    ],
  },
  {
    day: 27,
    title: 'Workplace Idioms',
    subtitle: 'Thành ngữ thông dụng tại nơi làm việc',
    theme: 'career',
    emoji: '🗣️',
    gradient: ['#A855F7', '#EC4899'],
    xpReward: 170,
    vocabulary: [
      { word: 'Touch base', phonetic: '/tʌtʃ beɪs/', translation: 'Liên lạc / check in', example: "Let's touch base tomorrow morning to align on priorities.", exampleTranslation: 'Hãy liên lạc sáng mai để thống nhất các ưu tiên.' },
      { word: 'Ballpark figure', phonetic: '/ˈbɔːlpɑːrk ˈfɪɡər/', translation: 'Con số ước tính', example: "I don't need an exact number — just a ballpark figure.", exampleTranslation: 'Tôi không cần số chính xác — chỉ cần con số ước tính.' },
      { word: 'On the same page', phonetic: '/ɒn ðə seɪm peɪdʒ/', translation: 'Hiểu cùng một ý', example: "Before we proceed, let's make sure we're on the same page.", exampleTranslation: 'Trước khi tiến hành, hãy đảm bảo chúng ta hiểu cùng một ý.' },
      { word: 'Think outside the box', phonetic: '/θɪŋk ˌaʊtˈsaɪd ðə bɒks/', translation: 'Suy nghĩ sáng tạo / đột phá', example: "We need to think outside the box on this problem.", exampleTranslation: 'Chúng ta cần suy nghĩ sáng tạo về vấn đề này.' },
      { word: 'Get the ball rolling', phonetic: '/ɡɛt ðə bɔːl ˈroʊlɪŋ/', translation: 'Bắt đầu / khởi động', example: "Let's get the ball rolling — who's starting the first sprint?", exampleTranslation: 'Hãy bắt đầu thôi — ai sẽ khởi động sprint đầu tiên?' },
      { word: 'Take it with a grain of salt', phonetic: '/teɪk ɪt wɪð ə ɡreɪn əv sɔːlt/', translation: 'Đừng tin hoàn toàn / nên nghi ngờ', example: "Take the deadline estimate with a grain of salt — it usually slips.", exampleTranslation: 'Đừng tin hoàn toàn vào ước tính deadline — thường hay bị trễ.' },
    ],
    exercises: [
      { id: 'd27e1', type: 'multiple-choice', question: '"Let\'s touch base tomorrow" means:', options: ['Meet for a long strategy session', "Have a quick check-in", 'Cancel tomorrow\'s plan', 'Play baseball'], correct: "Have a quick check-in" },
      { id: 'd27e2', type: 'fill-blank', question: "Before we start building, let's make sure we're all on the ___ ___.", options: ['same page', 'same team', 'right track', 'same level'], correct: 'same page' },
      { id: 'd27e3', type: 'word-order', question: 'Arrange the idiom sentence', words: ['need', 'We', 'box', 'the', 'outside', 'think', 'to'], correct: 'We need to think outside the box' },
      { id: 'd27e4', type: 'listen-choose', question: 'Listen and choose', audioText: "Take the roadmap with a grain of salt, priorities change every quarter", options: ["Take the roadmap with a grain of salt, priorities change every quarter", "Take the roadmap with a grain of salt, priorities change every month", "Take the plan with a grain of salt, priorities change every quarter", "Take the roadmap with a pinch of salt, priorities change every quarter"], correct: "Take the roadmap with a grain of salt, priorities change every quarter" },
      { id: 'd27e5', type: 'word-match', question: 'Match workplace idioms', correct: 'matched', pairs: [['Touch base', 'Liên lạc kiểm tra'], ['Ballpark figure', 'Số ước tính'], ['On the same page', 'Hiểu cùng ý'], ['Get the ball rolling', 'Bắt đầu khởi động'], ['Grain of salt', 'Đừng tin hoàn toàn']] },
      { id: 'd27e6', type: 'pronunciation', question: 'Common workplace phrase', audioText: "Let's touch base after the standup to make sure we're on the same page", correct: "let's touch base after the standup to make sure we're on the same page", hint: 'Natural, conversational pace' },
    ],
  },
  {
    day: 28,
    title: 'Week 4 Review',
    subtitle: 'Ôn tập tuần 4 — Career English',
    theme: 'review',
    emoji: '⭐',
    gradient: ['#EC4899', '#8B5CF6'],
    xpReward: 180,
    vocabulary: [
      { word: 'Value proposition', phonetic: '/ˈvæljuː ˌprɒpəˈzɪʃən/', translation: 'Giá trị cốt lõi bạn mang lại', example: "Your value proposition as a developer is clear: fast, clean, reliable code.", exampleTranslation: 'Giá trị cốt lõi của bạn với tư cách developer rất rõ: code nhanh, sạch, đáng tin cậy.' },
      { word: 'Proactive', phonetic: '/proʊˈæktɪv/', translation: 'Chủ động', example: 'I try to be proactive about flagging risks early.', exampleTranslation: 'Tôi cố gắng chủ động báo cáo rủi ro sớm.' },
      { word: 'Visibility', phonetic: '/ˌvɪzɪˈbɪlɪti/', translation: 'Độ hiện diện / tầm nhìn rõ ràng', example: "I'd like more visibility into the product roadmap.", exampleTranslation: 'Tôi muốn có tầm nhìn rõ hơn về lộ trình sản phẩm.' },
      { word: 'Alignment', phonetic: '/əˈlaɪnmənt/', translation: 'Sự đồng thuận / thống nhất', example: "We need alignment on the technical approach before starting.", exampleTranslation: 'Chúng ta cần thống nhất về cách tiếp cận kỹ thuật trước khi bắt đầu.' },
      { word: 'Ownership', phonetic: '/ˈoʊnərʃɪp/', translation: 'Tinh thần làm chủ / chịu trách nhiệm', example: 'Take ownership of the problem — see it through to resolution.', exampleTranslation: 'Hãy làm chủ vấn đề — theo dõi đến khi giải quyết xong.' },
      { word: 'Impact', phonetic: '/ˈɪmpækt/', translation: 'Tác động / kết quả có ý nghĩa', example: 'Show your impact with numbers: "I reduced build time by 40%."', exampleTranslation: 'Chứng minh tác động bằng số liệu: "Tôi đã giảm thời gian build 40%."' },
    ],
    exercises: [
      { id: 'd28e1', type: 'multiple-choice', question: '"Take ownership" in a work context means:', options: ['Buy company shares', 'Be responsible and follow through on a task', 'Blame others for problems', 'Take a break'], correct: 'Be responsible and follow through on a task' },
      { id: 'd28e2', type: 'word-order', question: 'Arrange the sentence', words: ['alignment', 'need', 'We', 'on', 'approach', 'technical', 'the'], correct: 'We need alignment on the technical approach' },
      { id: 'd28e3', type: 'word-match', question: 'Review: career vocabulary', correct: 'matched', pairs: [['Proactive', 'Chủ động'], ['Visibility', 'Tầm nhìn rõ ràng'], ['Alignment', 'Sự thống nhất'], ['Ownership', 'Tinh thần làm chủ'], ['Impact', 'Tác động có ý nghĩa']] },
      { id: 'd28e4', type: 'fill-blank', question: 'I try to be ___ about flagging blockers — I don\'t wait until the last minute.', options: ['reactive', 'proactive', 'passive', 'creative'], correct: 'proactive' },
      { id: 'd28e5', type: 'listen-choose', question: 'Listen and choose', audioText: "My goal is to have more visibility and ownership over the features I ship", options: ["My goal is to have more visibility and ownership over the features I ship", "My goal is to have more impact and ownership over the features I ship", "My goal is to have more visibility and responsibility over the features I ship", "My goal is to have more visibility and ownership over the products I ship"], correct: "My goal is to have more visibility and ownership over the features I ship" },
      { id: 'd28e6', type: 'pronunciation', question: 'Career phrase', audioText: "I take ownership of my work and I proactively flag risks", correct: "i take ownership of my work and i proactively flag risks", hint: '/ˈoʊnərʃɪp/ — stress on OWN' },
    ],
  },

  // ── FINAL 2 DAYS ──────────────────────────────────────────────────────────
  {
    day: 29,
    title: 'Advanced Conversations',
    subtitle: 'Hội thoại nâng cao — tổng hợp',
    theme: 'review',
    emoji: '🔥',
    gradient: ['#F59E0B', '#EF4444'],
    xpReward: 190,
    vocabulary: [
      { word: 'In retrospect', phonetic: '/ɪn ˈrɛtrəspɛkt/', translation: 'Nhìn lại / nhìn lại quá khứ', example: 'In retrospect, we should have written more tests.', exampleTranslation: 'Nhìn lại, chúng ta nên đã viết nhiều test hơn.' },
      { word: 'At the end of the day', phonetic: '/æt ðə ɛnd əv ðə deɪ/', translation: 'Xét cho cùng / cuối cùng mà nói', example: 'At the end of the day, the user experience is what matters most.', exampleTranslation: 'Xét cho cùng, trải nghiệm người dùng là điều quan trọng nhất.' },
      { word: "To be honest", phonetic: '/tuː biː ˈɒnɪst/', translation: 'Thành thật mà nói', example: 'To be honest, I think the timeline is too aggressive.', exampleTranslation: 'Thành thật mà nói, tôi nghĩ timeline quá gấp.' },
      { word: 'From a technical standpoint', phonetic: '/frɒm ə ˈtɛknɪkəl ˈstændpɔɪnt/', translation: 'Từ góc độ kỹ thuật', example: 'From a technical standpoint, this approach will not scale.', exampleTranslation: 'Từ góc độ kỹ thuật, cách tiếp cận này sẽ không scale được.' },
      { word: 'Long story short', phonetic: '/lɒŋ ˈstɔːri ʃɔːrt/', translation: 'Nói ngắn gọn lại', example: 'Long story short — the deploy broke production and we rolled back.', exampleTranslation: 'Nói ngắn gọn lại — deploy bị vỡ production và chúng tôi đã rollback.' },
      { word: 'Worth considering', phonetic: '/wɜːrθ kənˈsɪdərɪŋ/', translation: 'Đáng cân nhắc', example: "It's worth considering a microservices approach here.", exampleTranslation: 'Đáng cân nhắc cách tiếp cận microservices ở đây.' },
    ],
    exercises: [
      { id: 'd29e1', type: 'multiple-choice', question: '"From a technical standpoint" is used to:', options: ['Explain personal feelings', 'Give a technical perspective on something', 'Change the subject', 'Ask for clarification'], correct: 'Give a technical perspective on something' },
      { id: 'd29e2', type: 'word-order', question: 'Arrange the advanced phrase', words: ['short', 'Long', 'story', 'the', 'build', 'failed', 'and', 'we', 'reverted'], correct: 'Long story short the build failed and we reverted' },
      { id: 'd29e3', type: 'fill-blank', question: "___, this architecture will not scale beyond a million users.", options: ['To be honest', 'From a technical standpoint', 'Long story short', 'At the end of the day'], correct: 'From a technical standpoint' },
      { id: 'd29e4', type: 'listen-choose', question: 'Listen and choose', audioText: "To be honest I think we're moving too fast, it's worth slowing down and getting the architecture right", options: ["To be honest I think we're moving too fast, it's worth slowing down and getting the architecture right", "To be honest I think we're moving too fast, it's worth slowing down and getting the design right", "Honestly I think we're moving too fast, it's worth slowing down and getting the architecture right", "To be honest I think we're going too fast, it's worth slowing down and getting the architecture right"], correct: "To be honest I think we're moving too fast, it's worth slowing down and getting the architecture right" },
      { id: 'd29e5', type: 'word-match', question: 'Match advanced phrases', correct: 'matched', pairs: [['In retrospect', 'Nhìn lại quá khứ'], ['At the end of the day', 'Xét cho cùng'], ['To be honest', 'Thành thật mà nói'], ['Long story short', 'Nói ngắn gọn'], ['Worth considering', 'Đáng cân nhắc']] },
      { id: 'd29e6', type: 'pronunciation', question: 'Advanced connectors', audioText: "At the end of the day the product needs to work for the user, not just pass the tests", correct: "at the end of the day the product needs to work for the user not just pass the tests", hint: 'Natural flow, not robotic' },
    ],
  },
  {
    day: 30,
    title: 'Final Mastery',
    subtitle: 'Tổng ôn tập 30 ngày — Mastery challenge',
    theme: 'review',
    emoji: '🏆',
    gradient: ['#7C3AED', '#EC4899'],
    xpReward: 250,
    vocabulary: [
      { word: 'Congratulations!', phonetic: '/kənˌɡrætʃʊˈleɪʃənz/', translation: 'Chúc mừng!', example: 'Congratulations — you completed 30 days of English practice!', exampleTranslation: 'Chúc mừng — bạn đã hoàn thành 30 ngày luyện tiếng Anh!' },
      { word: 'Consistent', phonetic: '/kənˈsɪstənt/', translation: 'Kiên định / đều đặn', example: 'Being consistent is the key to language learning.', exampleTranslation: 'Kiên định là chìa khóa để học ngôn ngữ.' },
      { word: 'Growth mindset', phonetic: '/ɡroʊθ ˈmaɪndsɛt/', translation: 'Tư duy phát triển', example: 'A growth mindset means you believe skills can improve with effort.', exampleTranslation: 'Tư duy phát triển có nghĩa là bạn tin rằng kỹ năng có thể cải thiện nhờ nỗ lực.' },
      { word: 'Level up', phonetic: '/ˈlɛvəl ʌp/', translation: 'Nâng cấp bản thân', example: "Keep practicing — you're leveling up every day.", exampleTranslation: 'Tiếp tục luyện tập — bạn đang nâng cấp bản thân mỗi ngày.' },
      { word: "Don't stop here", phonetic: '/doʊnt stɒp hɪər/', translation: 'Đừng dừng lại ở đây', example: "30 days is a great start — don't stop here.", exampleTranslation: '30 ngày là một khởi đầu tốt — đừng dừng lại ở đây.' },
      { word: 'Real-world fluency', phonetic: '/rɪəl wɜːrld ˈfluːənsi/', translation: 'Sự trôi chảy trong thực tế', example: 'Real-world fluency comes from speaking with real people.', exampleTranslation: 'Sự trôi chảy trong thực tế đến từ việc nói chuyện với người thật.' },
    ],
    exercises: [
      { id: 'd30e1', type: 'multiple-choice', question: 'Which phrase is best for starting a job interview answer?', options: ["I work at...", "Based on my experience, I...", "My name is...", "I don't know..."], correct: "Based on my experience, I..." },
      { id: 'd30e2', type: 'word-match', question: 'Final vocabulary review — all 4 weeks', correct: 'matched', pairs: [['LGTM', 'Looks good to me'], ['Ballpark figure', 'Con số ước tính'], ['Touch base', 'Liên lạc kiểm tra'], ['Bottleneck', 'Điểm nghẽn'], ['Constructive criticism', 'Phê bình xây dựng']] },
      { id: 'd30e3', type: 'word-order', question: 'Arrange the final sentence', words: ['consistent', 'Being', 'the', 'key', 'is', 'to', 'fluency'], correct: 'Being consistent is the key to fluency' },
      { id: 'd30e4', type: 'fill-blank', question: "___, this approach will not scale — we need to rethink the data layer.", options: ['To be honest', 'From a technical standpoint', 'Long story short', 'In retrospect'], correct: 'From a technical standpoint' },
      { id: 'd30e5', type: 'listen-choose', question: 'Final listening challenge', audioText: "Based on my experience I was expecting a higher salary, is there room to negotiate", options: ["Based on my experience I was expecting a higher salary, is there room to negotiate", "Based on my skills I was expecting a higher salary, is there room to negotiate", "Based on my experience I was expecting more salary, is there room to negotiate", "Based on my experience I was expecting a higher salary, can we negotiate"], correct: "Based on my experience I was expecting a higher salary, is there room to negotiate" },
      { id: 'd30e6', type: 'pronunciation', question: 'Your 30-day achievement', audioText: "I completed thirty days of English practice and I am ready to use it in the real world", correct: "i completed thirty days of english practice and i am ready to use it in the real world", hint: 'Say it with confidence — you earned it' },
    ],
  },
];

export function getLessonByDay(day: number): DayLesson | undefined {
  return lessons.find((l) => l.day === day);
}
