export type ShadowLevel = 'A2' | 'B1' | 'B2' | 'C1';
export type ShadowCategory = 'office' | 'travel' | 'daily' | 'business';

export interface ShadowingItem {
  id: string;
  level: ShadowLevel;
  category: ShadowCategory;
  title: string;
  text: string;
  translation: string;
  tip?: string;
}

export const shadowingItems: ShadowingItem[] = [
  // ─── A2 ────────────────────────────────────────────────────────
  {
    id: 'a2-o1',
    level: 'A2',
    category: 'office',
    title: 'Reschedule a meeting',
    text: "I need to reschedule our meeting because something urgent came up. Would Thursday afternoon work for you?",
    translation: "Tôi cần dời lịch họp vì có việc gấp. Chiều thứ Năm có phù hợp với bạn không?",
    tip: 'Stress "URgent" and "WORK for you" — both carry key information in this sentence',
  },
  {
    id: 'a2-o2',
    level: 'A2',
    category: 'office',
    title: 'Request a deadline extension',
    text: "I am afraid I cannot finish the report by Friday. Could you give me until Monday to complete it properly?",
    translation: "Tôi e là không thể hoàn thành báo cáo trước thứ Sáu. Bạn có thể cho tôi đến thứ Hai để hoàn thiện không?",
    tip: '"I\'m aFRAID" — a polite softener when saying no. Stress falls on "afraid", not "I\'m"',
  },
  {
    id: 'a2-o3',
    level: 'A2',
    category: 'office',
    title: 'Ask for clarification',
    text: "Sorry, could you clarify what you mean by that? I want to make sure I understand your expectations correctly.",
    translation: "Xin lỗi, bạn có thể làm rõ ý bạn không? Tôi muốn chắc chắn rằng tôi hiểu đúng kỳ vọng của bạn.",
    tip: 'Stress "corRECTly" at the end — it signals you\'re being careful and thorough',
  },
  {
    id: 'a2-t1',
    level: 'A2',
    category: 'travel',
    title: 'At the hotel reception',
    text: "Excuse me, I have a reservation for two nights. My name is on the booking. Could I also request a wake-up call for seven tomorrow morning?",
    translation: "Xin lỗi, tôi đặt phòng hai đêm. Tên tôi có trong đơn đặt phòng. Tôi cũng có thể nhờ gọi báo thức lúc 7 giờ sáng mai không?",
    tip: '"wake-up CALL" — in compound nouns, stress the last word, not the first',
  },
  {
    id: 'a2-t2',
    level: 'A2',
    category: 'travel',
    title: 'Asking about transport',
    text: "How long does it take to get to the city center from here? Is it better to take the subway or a taxi?",
    translation: "Từ đây đến trung tâm thành phố mất bao lâu? Đi tàu điện ngầm hay taxi thì tốt hơn?",
    tip: 'In "X or Y?" questions, stress both options equally. Voice rises slightly on the first, falls on the second',
  },
  {
    id: 'a2-d1',
    level: 'A2',
    category: 'daily',
    title: 'Morning routine',
    text: "I usually start my day by checking my emails and reviewing my schedule before attending any meetings.",
    translation: "Tôi thường bắt đầu ngày làm việc bằng cách kiểm tra email và xem lại lịch trình trước khi dự họp.",
    tip: '"by checking" — the /g/ in "checking" links smoothly into the next word. Keep the flow',
  },
  {
    id: 'a2-d2',
    level: 'A2',
    category: 'daily',
    title: 'Declining an invitation',
    text: "Thank you so much for the invitation, but I already have prior commitments that evening. I hope we can catch up another time.",
    translation: "Cảm ơn bạn rất nhiều vì lời mời, nhưng tôi đã có việc trước vào buổi tối hôm đó. Tôi hy vọng chúng ta có thể gặp nhau vào lần khác.",
    tip: '"priOR comMITments" — stress the second syllable in each. "Prior commitments" is the polite excuse phrase',
  },
  {
    id: 'a2-b1',
    level: 'A2',
    category: 'business',
    title: 'Introduce yourself professionally',
    text: "I am the project coordinator for the marketing team. I have been with this company for about two years, focusing mainly on digital campaigns.",
    translation: "Tôi là điều phối viên dự án của nhóm marketing. Tôi đã làm ở công ty này khoảng hai năm, chủ yếu tập trung vào các chiến dịch kỹ thuật số.",
    tip: '"FOcusing MAINly" — both words carry equal emphasis. Don\'t rush through the detail',
  },

  // ─── B1 ────────────────────────────────────────────────────────
  {
    id: 'b1-o1',
    level: 'B1',
    category: 'office',
    title: 'Postpone a project',
    text: "I'm afraid we'll have to postpone the launch due to some unforeseen technical issues. The development team is working around the clock to resolve them.",
    translation: "Tôi e rằng chúng ta sẽ phải hoãn buổi ra mắt vì một số vấn đề kỹ thuật không lường trước được. Đội phát triển đang làm việc suốt ngày đêm để giải quyết.",
    tip: '"around the CLOCK" — idiom for 24/7. Stress "clock". The metaphor lands best when you hit that word',
  },
  {
    id: 'b1-o2',
    level: 'B1',
    category: 'office',
    title: 'Give constructive feedback',
    text: "Overall your presentation was compelling, however I think the data section could benefit from more concrete examples to support your conclusions.",
    translation: "Nhìn chung bài thuyết trình của bạn rất thuyết phục, tuy nhiên tôi nghĩ phần dữ liệu có thể tốt hơn nếu có thêm ví dụ cụ thể để hỗ trợ kết luận.",
    tip: '"howEVer" — stress second syllable. A slight pause before it signals the contrast is coming',
  },
  {
    id: 'b1-o3',
    level: 'B1',
    category: 'office',
    title: 'Negotiate a deadline',
    text: "Given the complexity of this task, I would suggest allocating at least two additional weeks. Otherwise we risk delivering something that doesn't meet the required standards.",
    translation: "Xét đến độ phức tạp của nhiệm vụ này, tôi đề nghị phân bổ thêm ít nhất hai tuần. Nếu không, chúng ta có nguy cơ giao sản phẩm không đáp ứng tiêu chuẩn yêu cầu.",
    tip: '"otherWISE we RISK" — slow down slightly here. The consequence needs to land with weight',
  },
  {
    id: 'b1-t1',
    level: 'B1',
    category: 'travel',
    title: 'Complain at a restaurant',
    text: "I'm sorry to bother you, but I ordered the salmon nearly thirty minutes ago and it still hasn't arrived. Could you check on that for me please?",
    translation: "Xin lỗi vì làm phiền, nhưng tôi gọi cá hồi gần ba mươi phút trước và vẫn chưa thấy. Bạn có thể kiểm tra giúp tôi không?",
    tip: 'Keep the tone warm even when complaining. Stress "SOrry" and "thirty MINUTES" — the facts make your case',
  },
  {
    id: 'b1-t2',
    level: 'B1',
    category: 'travel',
    title: 'Handle a flight delay',
    text: "Could you tell me what options are available? My connecting flight leaves in two hours and I'm concerned I won't make it in time.",
    translation: "Bạn có thể cho tôi biết có những lựa chọn nào không? Chuyến bay nối chuyến của tôi khởi hành sau hai tiếng và tôi lo rằng mình sẽ không kịp.",
    tip: '"conCERNED" — softer than "worried". In formal travel situations, staying calm signals you know your rights',
  },
  {
    id: 'b1-d1',
    level: 'B1',
    category: 'daily',
    title: 'Discuss a news article',
    text: "I read an interesting article this morning about how remote work is reshaping urban planning. Apparently, fewer people commuting has had a significant impact on city infrastructure.",
    translation: "Tôi đọc một bài báo thú vị sáng nay về cách làm việc từ xa đang định hình lại quy hoạch đô thị. Dường như việc ít người đi làm hơn đã có tác động đáng kể đến cơ sở hạ tầng thành phố.",
    tip: '"reSHAPing" — the re- prefix is unstressed. Stress "shaping". The -ing ending also stays light',
  },
  {
    id: 'b1-b1',
    level: 'B1',
    category: 'business',
    title: 'Propose a solution',
    text: "One possible approach would be to outsource the design work temporarily while we build our in-house capability. This would allow us to meet the deadline without compromising quality.",
    translation: "Một hướng tiếp cận có thể là thuê ngoài công việc thiết kế tạm thời trong khi chúng ta xây dựng năng lực nội bộ. Điều này sẽ cho phép chúng ta đáp ứng thời hạn mà không ảnh hưởng đến chất lượng.",
    tip: '"comPROMising QUAlity" — stress both nouns. They are the two trade-offs being discussed',
  },
  {
    id: 'b1-b2',
    level: 'B1',
    category: 'business',
    title: 'Quarterly review',
    text: "The quarterly results exceeded our projections by fifteen percent, which puts us in a strong position to proceed with the expansion we discussed in January.",
    translation: "Kết quả quý vượt dự báo của chúng ta 15%, điều này đặt chúng ta vào vị thế thuận lợi để tiến hành mở rộng mà chúng ta đã thảo luận vào tháng Một.",
    tip: '"exCEEDed our proJECtions" — both words stressed. Numbers like "fifteen percent" get equal weight on each word',
  },

  // ─── B2 ────────────────────────────────────────────────────────
  {
    id: 'b2-o1',
    level: 'B2',
    category: 'office',
    title: 'Raise a concern professionally',
    text: "I'd appreciate it if you could elaborate on the rationale behind this decision, particularly regarding how it aligns with our long-term strategic objectives.",
    translation: "Tôi sẽ rất biết ơn nếu bạn có thể giải thích chi tiết hơn về lý do đằng sau quyết định này, đặc biệt là về cách nó phù hợp với các mục tiêu chiến lược dài hạn của chúng ta.",
    tip: '"eLAborate on the raTIONale" — academic words with tricky stress. Get these right and you sound very polished',
  },
  {
    id: 'b2-o2',
    level: 'B2',
    category: 'office',
    title: 'Respond to criticism',
    text: "I take your point, and while I understand the concerns you've raised, I believe the evidence suggests that the benefits of this approach significantly outweigh the potential drawbacks.",
    translation: "Tôi hiểu quan điểm của bạn, và mặc dù tôi hiểu những lo ngại bạn nêu ra, tôi tin rằng bằng chứng cho thấy lợi ích của cách tiếp cận này vượt trội đáng kể so với những hạn chế tiềm ẩn.",
    tip: '"OUTweigh the DRAWbacks" — the contrast between both sides. Stress both to land the argument',
  },
  {
    id: 'b2-o3',
    level: 'B2',
    category: 'office',
    title: 'Motivate the team',
    text: "I acknowledge that the past few months have been incredibly demanding, but your resilience and dedication have not gone unnoticed. I'm confident that we're on the verge of a significant breakthrough.",
    translation: "Tôi nhận thấy rằng vài tháng qua đã vô cùng căng thẳng, nhưng sự kiên cường và tận tâm của các bạn đã không bị bỏ qua. Tôi tin chắc rằng chúng ta đang trên đà đạt được một bước đột phá đáng kể.",
    tip: '"on the VERGE of" — idiom meaning "about to". Pause briefly before "breakthrough" for maximum effect',
  },
  {
    id: 'b2-t1',
    level: 'B2',
    category: 'travel',
    title: 'Negotiate a refund',
    text: "Given that the accommodation failed to meet the standards outlined in the booking description, I believe I'm entitled to either a partial refund or a complimentary upgrade for the remaining nights.",
    translation: "Xét rằng chỗ ở không đáp ứng các tiêu chuẩn được nêu trong mô tả đặt phòng, tôi cho rằng tôi có quyền được hoàn tiền một phần hoặc nâng cấp miễn phí cho những đêm còn lại.",
    tip: '"I\'m enTITled to" — stress the second syllable. Saying this calmly and clearly is far more effective than being angry',
  },
  {
    id: 'b2-t2',
    level: 'B2',
    category: 'travel',
    title: 'Cultural observation',
    text: "What strikes me most about this city is how seamlessly it blends ancient architecture with ultra-modern infrastructure, creating an atmosphere that feels simultaneously familiar and completely foreign.",
    translation: "Điều gây ấn tượng nhất với tôi về thành phố này là cách nó hòa trộn kiến trúc cổ đại với cơ sở hạ tầng siêu hiện đại một cách liền mạch, tạo ra bầu không khí vừa quen thuộc vừa hoàn toàn xa lạ.",
    tip: '"SEAMlessly" /ˈsiːmləsli/ — stress first syllable: SEAM. Means "without any visible joins or gaps"',
  },
  {
    id: 'b2-d1',
    level: 'B2',
    category: 'daily',
    title: 'Work-life balance',
    text: "Maintaining a healthy work-life balance has become increasingly elusive in an era where technology effectively erases the boundaries between professional obligations and personal time.",
    translation: "Duy trì sự cân bằng lành mạnh giữa công việc và cuộc sống ngày càng khó đạt được trong một kỷ nguyên mà công nghệ xóa nhòa ranh giới giữa nghĩa vụ nghề nghiệp và thời gian cá nhân.",
    tip: '"eLUsive" /ɪˈluːsɪv/ — stress second syllable, long /uː/ vowel. Means "hard to find or achieve"',
  },
  {
    id: 'b2-b1',
    level: 'B2',
    category: 'business',
    title: 'Announce a restructuring',
    text: "The merger will inevitably necessitate some restructuring across departments, and it's paramount that we communicate these changes transparently to mitigate uncertainty among the workforce.",
    translation: "Việc sáp nhập chắc chắn sẽ đòi hỏi cơ cấu lại một số phòng ban, và điều tối quan trọng là chúng ta phải truyền đạt những thay đổi này một cách minh bạch để giảm thiểu sự không chắc chắn trong lực lượng lao động.",
    tip: '"PARAmount" /ˈpærəmaʊnt/ — stress first syllable, wide /æ/ vowel. Means "more important than anything else"',
  },
  {
    id: 'b2-b2',
    level: 'B2',
    category: 'business',
    title: 'Pitch an idea',
    text: "What we're proposing is a paradigm shift in how we approach customer acquisition, one that leverages data-driven insights to deliver highly personalised experiences at scale.",
    translation: "Những gì chúng tôi đề xuất là sự thay đổi mô hình trong cách chúng ta tiếp cận việc thu hút khách hàng, một cách tận dụng thông tin dữ liệu để cung cấp trải nghiệm được cá nhân hóa cao ở quy mô lớn.",
    tip: '"PARadigm" — the G is SILENT: /ˈpærədaɪm/, rhymes with "para-dime". This trips up even advanced speakers',
  },

  // ─── C1 ────────────────────────────────────────────────────────
  {
    id: 'c1-o1',
    level: 'C1',
    category: 'office',
    title: 'System design: distributed systems trade-offs',
    text: "The thing with distributed systems is that you're essentially trading simplicity for resilience. Every network call is a potential failure point, so the question isn't whether we'll have partial failures — it's how gracefully we handle them when they inevitably occur.",
    translation: "Vấn đề với hệ thống phân tán là bạn đang đánh đổi sự đơn giản để lấy tính bền vững. Mỗi cuộc gọi mạng là một điểm lỗi tiềm ẩn, vì vậy câu hỏi không phải là liệu chúng ta có gặp lỗi hay không — mà là chúng ta xử lý chúng uyển chuyển như thế nào.",
    tip: '"grACEfully" and "ineviTABly" — both adverbs are doing heavy lifting. Don\'t swallow the endings',
  },
  {
    id: 'c1-o2',
    level: 'C1',
    category: 'office',
    title: 'System design: proposing a migration',
    text: "We're at a crossroads with the current architecture. The monolith has served us well up to this point, but given our projected growth, we need to start thinking about decomposing it into services that can scale independently.",
    translation: "Chúng ta đang đứng trước ngã rẽ với kiến trúc hiện tại. Hệ thống monolith đã phục vụ chúng ta tốt đến điểm này, nhưng với mức tăng trưởng dự kiến, chúng ta cần bắt đầu nghĩ đến việc phân rã nó thành các dịch vụ có thể mở rộng độc lập.",
    tip: '"at a CROSSroads" — idiom for a critical decision point. Pause briefly before it so the metaphor registers',
  },
  {
    id: 'c1-b1',
    level: 'C1',
    category: 'business',
    title: 'Salary negotiation: opening move',
    text: "I'm genuinely excited about the opportunity, and I appreciate the offer. That said, based on my research into market rates and the value I'd be bringing to the team, I was expecting something in the region of ten to fifteen percent higher. Is there any flexibility there?",
    translation: "Tôi thực sự hào hứng với cơ hội này và trân trọng đề xuất. Tuy nhiên, dựa trên nghiên cứu của tôi về mức thị trường và giá trị tôi mang lại, tôi kỳ vọng mức cao hơn khoảng mười đến mười lăm phần trăm. Liệu có chỗ nào linh hoạt không?",
    tip: '"That SAID" — a pivot phrase. Brief pause before it, slight stress. It signals polite pushback without aggression',
  },
  {
    id: 'c1-b2',
    level: 'C1',
    category: 'business',
    title: 'Salary negotiation: handling constraints',
    text: "I understand the salary band constraints, and I appreciate you going to bat for me. If there's limited room to move on base, would you be open to discussing a signing bonus or an accelerated review cycle to offset the gap?",
    translation: "Tôi hiểu các ràng buộc về dải lương, và tôi trân trọng việc bạn đã đứng ra vì tôi. Nếu không có nhiều chỗ về lương cơ bản, bạn có sẵn sàng thảo luận về bonus ký kết hoặc chu kỳ đánh giá nhanh hơn để bù đắp khoảng cách không?",
    tip: '"going to BAT for me" — baseball idiom: someone advocating for you. Stress "bat" to make the idiom clear',
  },
  {
    id: 'c1-b3',
    level: 'C1',
    category: 'business',
    title: 'Explaining a DB migration to non-technical stakeholders',
    text: "Think of it like renovating a kitchen without shutting down the restaurant. We're upgrading the foundation while keeping everything running — which means we need to be surgical about how we roll this out, because any misstep could ripple across the entire customer experience.",
    translation: "Hãy nghĩ về điều này như việc cải tạo nhà bếp mà không đóng cửa nhà hàng. Chúng tôi đang nâng cấp nền tảng trong khi vẫn giữ mọi thứ hoạt động — điều đó có nghĩa là chúng tôi cần cẩn thận như phẫu thuật, vì bất kỳ sai sót nào cũng có thể lan rộng ra toàn bộ trải nghiệm khách hàng.",
    tip: '"surGIcal" — stress the second syllable. Deliberate pace here — you\'re translating tech into human language',
  },
  {
    id: 'c1-b4',
    level: 'C1',
    category: 'business',
    title: 'Making the case for addressing technical debt',
    text: "Every shortcut we took to hit those early deadlines has been accruing interest. At some point the interest payments — in the form of bugs, slow features, and engineer frustration — cost more than just doing it right in the first place. That's where we are now.",
    translation: "Mỗi phím tắt chúng tôi thực hiện để đạt được những deadline ban đầu đã tích lũy lãi suất. Đến một lúc nào đó, khoản lãi — dưới dạng lỗi, tính năng chậm và sự thất vọng của kỹ sư — tốn kém hơn việc làm đúng ngay từ đầu. Đó là vị trí chúng ta đang ở bây giờ.",
    tip: '"acCRUing INterest" — the financial metaphor is the entire argument. Stress both words so non-technical people connect it',
  },
];

export const levelColors: Record<ShadowLevel, { bg: string; text: string; border: string; gradient: [string, string] }> = {
  A2: { bg: 'bg-emerald-500/20', text: 'text-emerald-300', border: 'border-emerald-500/30', gradient: ['#10B981', '#059669'] },
  B1: { bg: 'bg-blue-500/20', text: 'text-blue-300', border: 'border-blue-500/30', gradient: ['#3B82F6', '#6366F1'] },
  B2: { bg: 'bg-violet-500/20', text: 'text-violet-300', border: 'border-violet-500/30', gradient: ['#8B5CF6', '#EC4899'] },
  C1: { bg: 'bg-amber-500/20', text: 'text-amber-300', border: 'border-amber-500/30', gradient: ['#F59E0B', '#F97316'] },
};

export const categoryLabels: Record<ShadowCategory, { label: string; emoji: string }> = {
  office: { label: 'Office', emoji: '💼' },
  travel: { label: 'Travel', emoji: '✈️' },
  daily: { label: 'Daily', emoji: '☀️' },
  business: { label: 'Business', emoji: '📊' },
};
